function Data=buildBOIEventReviewData(Review,Index)
%BUILDBOIEVENTREVIEWDATA Saved ingredients and explicit arithmetic, both signs.
A=Review.Audit;assert(isscalar(Index)&&Index==fix(Index)&&Index>=1&&Index<=height(A));
row=A(Index,:);t=Review.Traces{Index};I=Review.AnalysisInfo;fs=I.AnalysisParams.fs;
N=I.NFrames;raw=double(t.Raw(:));frames=(1:N)';time=(frames-1)/fs;
baseline=false(N,1);baseline(t.CleanBaselineFrames)=true;
event=frames>=row.StartFrame&frames<=row.EndFrame;
detected=false(N,1);detected(t.DetectedFrames)=true;
q=nan(N,1);B=row.RecomputedBaseline;
if row.RecomputedStatus=="valid"&&isfinite(B)&&B>0,q=(raw-B)/B;end
replayed=NaN;
if all(isfinite(q(event)))
    if row.EventType=="sink",replayed=-min(q(event));else,replayed=max(q(event));end
end
same=(isnan(replayed)&&isnan(row.RecomputedAmplitude))|| ...
    (isfinite(replayed)&&abs(replayed-row.RecomputedAmplitude)<=1e-10*max(1,abs(row.RecomputedAmplitude)));
replayedBaseline=NaN;
if numel(t.CleanBaselineFrames)==row.BaselineWindowFrames
    replayedBaseline=mean(raw(baseline));
end
baselineSame=(isnan(replayedBaseline)&&isnan(B))|| ...
    (isfinite(replayedBaseline)&&isfinite(B)&&abs(replayedBaseline-B)<=1e-10*max(1,abs(B)));
Data=struct('Row',row,'Frames',table(frames,time,raw,baseline,event,detected,q, ...
    'VariableNames',{'Frame','ModeledTimeSec','PreservedInputMean','CleanBaseline','MeasurementWindow','NativeDetectedFrame','SignedFraction'}), ...
    'Footprint',t.Footprint,'ReplayedAmplitude',replayed,'ReplayMatches',same, ...
    'ReplayedBaseline',replayedBaseline,'BaselineReplayMatches',baselineSame);
[Data.BaselineDiagnostic,Data.Frames.DiagnosticLinearReference,Data.Frames.DiagnosticLinearSignedFraction]= ...
    buildBOIBaselineDiagnostic(Data,fs);
Data.BaselineDiagnostic.SavedAuditSHA256=Review.AuditSHA256;
Data.BaselineDiagnostic.SavedAuditPath=Review.AuditPath;
Data.ResearcherBoundaryReview=getBOIBoundaryReview(Review,Index);
[Data.TimingReview,timingFrames]=buildBOITimingReviewData(t,I,Review);
Data.TimingReview.SelectedEvent=table2struct(row(:,{'RecordingID','EventType','SiteID','EventID', ...
    'StartFrame','EndFrame','DetectedStartFrame','DetectedEndFrame'}));
Data.Frames=[Data.Frames timingFrames];
direction="";if row.WrongDirection,direction="DIRECTION DISAGREEMENT: preserved-input amplitude opposes the detector label. Retain its sign.";end
lines=[string(row.RecordingID)+" | "+row.EventType+" | site "+row.SiteID+" | event "+row.EventID; ...
    "Scientific eligibility: not established. "+direction; ...
    "Saved amplitude: "+row.StoredAmplitude+" fraction ("+100*row.StoredAmplitude+"%)."; ...
    "Audit amplitude: "+row.RecomputedAmplitude+" fraction. Replay from saved trace: "+replayed+"."; ...
    "Saved audit agreement: "+string(row.MeasurementMatches)+". Trace replay agreement: "+string(same)+"."; ...
    "Baseline status: "+row.RecomputedStatus+"; this is a numerical status, not scientific acceptance."; ...
    "B0 = "+B+" input units; "+numel(t.CleanBaselineFrames)+" clean samples / "+row.BaselineWindowFrames+" required."; ...
    "Baseline replay from clean samples: "+replayedBaseline+"; agreement: "+string(baselineSame)+"."; ...
    "q(t)=(I(t)-B0)/B0. Sink amplitude=-min(q); surge amplitude=max(q) within the measurement window."; ...
    "Measurement interval ["+(row.StartFrame-1)/fs+", "+row.EndFrame/fs+") s; frames "+row.StartFrame+"–"+row.EndFrame+" inclusive."; ...
    "Native detection interval ["+(row.DetectedStartFrame-1)/fs+", "+row.DetectedEndFrame/fs+") s."; ...
    "Trace bounds: red dashed = measurement interval; blue dotted = native detection interval."; ...
    "Sampling: "+fs+" Hz; "+string(Review.Acquisition.FrameTimingStatus)+". Time is modeled from frame index; embedded clocks are not substituted."; ...
    "Orange overlay is the fixed union footprint used for amplitude ("+numel(t.Footprint)+" pixels), not a native frame mask or tissue boundary."; ...
    "Per-frame native masks are not stored in this audit. Tissue occupancy/area cannot be inferred from the union overlay."; ...
    "Trace is measured from preserved input. Detection normalization and timing refinement are separate operations."; ...
    "Detection support profile: "+string(getBOISupportProfile(I))+". ROI normalization, when selected, may suppress responses shared across the ROI."; ...
    "Source identity, calibration, observable tissue, dynamic validity and physiological meaning require their own review."; ...
    "";"Saved acquisition issues:"];
for k=1:height(Review.QC)
    lines=[lines;Review.QC.IssueID(k)+": "+Review.QC.Message(k);"Action: "+Review.QC.Action(k)]; %#ok<AGROW>
end
lines=[lines;"";"Saved audit SHA256: "+string(Review.AuditSHA256); ...
    "Preserved source SHA256: "+string(I.RawSHA256);"Audit: "+string(Review.AuditPath)];
Data.Details=cellstr(lines);
Data.Details=[Data.Details;cellstr(["";"TIMING REVIEW: corrected intensity is primary; detection score supports interpretation; raw trace checks correction quality."; ...
    string(Data.TimingReview.Corrected.Message);string(Data.TimingReview.Filtered.Message);string(Data.TimingReview.Site.Message); ...
    string(Data.TimingReview.RemovedTrend.Message); ...
    "Timing view uses recording-frame sample positions: frame 1 = 0 s. This is distinct from the half-open measurement interval shown above."; ...
    "Saved site support may differ from the event footprint. No automatic boundary, fit, exclusion or relabeling is applied."])];
Data.Details=[Data.Details;cellstr(["";"BASELINE DIAGNOSTIC (review only): "+string(Data.BaselineDiagnostic.Message); ...
    "Open the Baseline diagnostic tab for the same samples, reference sensitivity and availability reason. No correction is applied."; ...
    "Diagnostic method: "+string(Data.BaselineDiagnostic.MethodID)+". "+string(Data.BaselineDiagnostic.NumericalInterpretation)])];
if isfield(Review,'WindowLinks')&&numel(Review.WindowLinks)>=Index&&~isempty(Review.WindowLinks{Index})
    Link=Review.WindowLinks{Index};Data.WindowLink=Link;
    Data.Details=[cellstr(["CONNECTED WINDOW: "+string(Link.StatsRecordingID)+" / "+string(Link.WindowID); ...
        "Window ["+Link.WindowStartSec+", "+Link.WindowEndSec+") s; onset included: "+string(Link.OnsetInWindow)+"; overlap: "+Link.OverlapSec+" s."; ...
        "Source audit ID: "+string(Link.AuditRecordingID)+". Mapping: "+string(Link.IdentityBasis); ...
        string(Link.Association);"Results SHA256: "+string(Link.ResultsSHA256)]);Data.Details];
end
Data.Frames.NativeMaskPixels=nan(N,1);
if isfield(Review,'NativeMasks')&&numel(Review.NativeMasks)>=Index&&~isempty(Review.NativeMasks{Index})
    attachment=Review.NativeMasks{Index};
    Data.NativeMaskAttachment=attachment;
    Data.Frames.NativeMaskPixels=cellfun(@numel,attachment.FramePixels);
    % Replace absence-specific text; retain the fixed-footprint distinction.
    remove=startsWith(string(Data.Details),'Per-frame native masks are not stored');
    Data.Details(remove)=[];
    Data.Details=[{['NATIVE MASK SNAPSHOT ATTACHED: ' attachment.Association]; ...
        'Native-mask counts are pixels, not calibrated area or reviewed tissue support.'; ...
        'Outside this native event run the mask is known empty, even if another event recurs at the same site.'}; ...
        Data.Details;{['Master SHA256: ' attachment.MasterSHA256];['Attached UTC: ' attachment.AttachedUTC]}];
end
end
