function E=buildBOIReviewedPocketEvidence(Review,Index,J)
%BUILDBOIREVIEWEDPOCKETEVIDENCE Source-bound saved ingredients, independent of legacy preview.
id='OxygenDynamics:PocketIdentityMismatch';
assert(strcmp(oxygenFileSHA256(Review.AuditPath),Review.AuditSHA256),id,'Audit changed; reopen it before pocket review.');
row=Review.Audit(Index,:);t=Review.Traces{Index};I=Review.AnalysisInfo;
assert(strcmp(J.Schema,'boi-reviewed-pocket-judgment-1')&&J.AuditRow==Index&&strcmp(J.AuditSHA256,Review.AuditSHA256)&& ...
    strcmp(J.RawSourceSHA256,I.RawSHA256)&&strcmp(J.FixedFootprintSHA256,boiPocketDigest(double(t.Footprint(:))))&& ...
    isequaln(J.SavedEvent,table2struct(row(:,{'RecordingID','EventType','SiteID','EventID'}))),id,'Judgment source/event/footprint differs.');
assert(strcmp(J.Interpretation,'researcher_reviewed_pocket')&&J.Revision>=1&&J.Revision==fix(J.Revision)&& ...
    ~isempty(strtrim(J.Reviewer))&&~isempty(strtrim(J.Reason))&&~isempty(J.RecordedUTC),id,'Explicit pocket judgment, reviewer and reason required.');
assert(ismember(J.EndpointStatus,{'recovery_observed','recovery_unresolved','recording_censored'})&& ...
    isequaln(J.BoundaryRevision,struct('Revision',J.Revision,'OnsetFrame',J.OnsetFrame,'ObservedEndFrame',J.ObservedEndFrame,'EndpointStatus',J.EndpointStatus))&& ...
    isequaln(J.ReferenceRevision,struct('Revision',J.Revision,'Frames',J.ReferenceFrames(:),'Suitability',J.ReferenceSuitability)), ...
    'OxygenDynamics:PocketRevisionMismatch','Boundary/reference revision differs from explicit judgment.');
assert(isscalar(J.OnsetFrame)&&isscalar(J.ObservedEndFrame)&&isfinite(J.OnsetFrame)&&isfinite(J.ObservedEndFrame)&& ...
    J.OnsetFrame==fix(J.OnsetFrame)&&J.ObservedEndFrame==fix(J.ObservedEndFrame)&&J.ObservedEndFrame>=J.OnsetFrame, ...
    'OxygenDynamics:InvalidPocketFrames','Explicit integer observation bounds required.');
assert(I.AnalysisParams.fs==1,'OxygenDynamics:PocketClock','This reviewed increment supports externally triggered 1 Hz only.');
raw=double(t.Raw(:));corrected=[];origin='not_saved';association=NaN;
% Bind to audited rows, not mutable UI copies. No source recording is read.
S=load(Review.AuditPath,'Traces','AnalysisInfo','Audit');
assert(isequaln(S.Traces{Index},t)&&isequaln(S.Audit(Index,:),row)&&strcmp(S.AnalysisInfo.RawSHA256,I.RawSHA256),id,'Saved ingredients differ from the opened audit.');
assert(numel(t.Footprint)==row.FootprintPixels&&numel(unique(t.Footprint))==numel(t.Footprint),id,'Fixed footprint differs.');
sameInput=isfield(I,'DenoisedFile')&&isempty(I.DenoisedFile)&&isfield(I,'DenoisedSHA256')&&isempty(I.DenoisedSHA256);
if sameInput&&isfield(t,'RawCubicTrend')&&~isempty(t.RawCubicTrend)
    assert(numel(t.RawCubicTrend)==numel(raw)&&isfield(t,'DetectionDetrended')&&numel(t.DetectionDetrended)==numel(raw),id,'Saved trend has no matching correction stage.');
    corrected=raw-double(t.RawCubicTrend(:));savedCorrected=double(t.DetectionDetrended(:));finite=isfinite(corrected)&isfinite(savedCorrected);
    if any(finite),association=max(abs(corrected(finite)-savedCorrected(finite)));end
    assert(~any(xor(isfinite(corrected),isfinite(t.DetectionDetrended(:))))&&(~isfinite(association)||association<=1e-4),id,'Saved correction association differs; no refit is allowed.');
    origin='saved_raw_cubic_trend_with_corrected_stage_association';
elseif sameInput&&isfield(t,'DetectionDetrended')&&isfield(Review,'AuditCreationReceipt')
    receipt=Review.AuditCreationReceipt;
    if isfield(receipt,'StageOrigin')&&strcmp(receipt.StageOrigin,'existing_in_memory_full_precision_stages')
        assert(strcmp(receipt.AuditSHA256,Review.AuditSHA256)&&strcmp(receipt.SourceSHA256,I.RawSHA256),id,'Correction receipt source differs.');
        corrected=double(t.DetectionDetrended(:));origin='receipted_saved_in_memory_corrected_stage';
    end
end
W=(J.OnsetFrame:J.ObservedEndFrame)';R=double(J.ReferenceFrames(:));
M=computeBOIReviewedPocketMeasures(raw,corrected,R,W,J.ReferenceSuitability,J.ClockAuthority);
qualification='Measured on saved sink footprint; reviewed pocket extent is not independently established.';
if row.EventType=="surge",qualification='Measured on saved surge footprint; pocket extent not independently established.';end
D=getBOIReviewedPocketDefinition;
E=struct('Schema','boi-reviewed-pocket-evidence-1','Definition',D,'ScientificStatus','researcher_selected_exploratory_optical_measure_not_physiological_validation', ...
    'AuditPath',Review.AuditPath,'AuditSHA256',Review.AuditSHA256,'AuditRow',Index,'RawSourceSHA256',I.RawSHA256, ...
    'OriginalAutomatic',table2struct(row),'Judgment',J,'JudgmentSHA256',boiPocketDigest(J), ...
    'FixedFootprint',double(t.Footprint(:)),'FixedFootprintSHA256',J.FixedFootprintSHA256,'FootprintOrigin',char(row.EventType), ...
    'FootprintQualification',qualification,'FrameSize',I.FrameSize,'PixelSizeUm',I.AnalysisParams.PixelSize, ...
    'EventFrames',W,'ReferenceFrames',R,'SampleHz',1,'FrameOrigin',1,'ModeledTimeFormula','Frame-1', ...
    'ObservedEndpointSpanSec',J.ObservedEndFrame-J.OnsetFrame,'ConfirmedPocketDurationSec',NaN, ...
    'Correction',struct('Origin',origin,'AuditSHA256',Review.AuditSHA256,'RawSourceSHA256',I.RawSHA256, ...
      'FixedFootprintSHA256',J.FixedFootprintSHA256,'SavedCorrectedSHA256',boiPocketDigest(corrected), ...
      'StageAssociationMaxAbsInputUnits',association,'NewFits',0), ...
    'Measures',M,'NativeOverlapContext','not_verified_by_this_saved_quantity_service', ...
    'AcquisitionEvidence',Review.Acquisition,'AcquisitionQC',table2struct(Review.QC),'AutomaticMeasurementsChanged',false, ...
    'DetectorRelabelled',false,'ExternalSourceVerification','saved_audit_association_only_source_recording_not_opened', ...
    'ImplementationSHA256',oxygenFileSHA256(which('buildBOIReviewedPocketEvidence')));
if isfield(Review,'HistoricalMetadata'),E.HistoricalMetadata=Review.HistoricalMetadata;end
% Full saved vectors support portable display/replay without the recording or fitting.
E.Ingredients=struct('Raw',raw,'Corrected',corrected,'CorrectionSHA256',boiPocketDigest(corrected),'FootprintSHA256',J.FixedFootprintSHA256);
E.IngredientsSHA256=boiPocketDigest(E.Ingredients);
% Portable reviewed evidence names the implementation that produced its values.
E.Software=struct('Function',{},'SHA256',{});
for name={'createBOIPocketJudgment','computeBOIReviewedPocketMeasures','buildBOIReviewedPocketEvidence', ...
        'getBOIReviewedPocketDefinition','validateBOIPocketEvidence','saveBOIReviewedPocketEvidence', ...
        'loadBOIReviewedPocketEvidence','attachBOIPocketEvidence','exportBOIReviewedPocketEvidence', ...
        'formatBOIPocketEvidence','verifyBOIReviewedPocketArithmetic','createBOIReviewedPocketPanel', ...
        'openBOIEventReview','openBOIReviewedPocketEvidence','exportBOIEventReview','loadBOIEventReview','boiPocketDigest'}
    E.Software(end+1)=struct('Function',name{1},'SHA256',oxygenFileSHA256(which(name{1}))); %#ok<AGROW>
end
end
