function Table_OxygenSurges_Out = createOxygenSurgeSummaryTable(Experiment_Surge,Mouse_Surge,Condition_Surge, ...
    DrugID_Surge,Genotype_Surge,Promoter_Surge,RecDuration_Surge,RecAreaSize_Surge,MeanCentroid_Surge_x, ...
    MeanCentroid_Surge_y,MeanOxySurgeArea_um,MeanOxySurgeFilledArea_um,MeanOxySurgeDiameter_um, ...
    MeanOxySurgePerimeter_um,MeanCircularity_Surge,MeanOxySurgeBoundingBox,NumOxySurgeEvents, ...
    Start_Surge,Duration_Surge,NormOxySurgeAmp,Size_Surge_modulation,OxySurge_Pxls_all)
%CREATEOXYGENSURGESUMMARYTABLE Build the recording-level oxygen-surge output table.

Table_OxygenSurges_Out = table(Experiment_Surge,Mouse_Surge,Condition_Surge,DrugID_Surge, ...
    Genotype_Surge,Promoter_Surge,RecDuration_Surge,RecAreaSize_Surge,MeanCentroid_Surge_x, ...
    MeanCentroid_Surge_y,MeanOxySurgeArea_um,MeanOxySurgeFilledArea_um,MeanOxySurgeDiameter_um, ...
    MeanOxySurgePerimeter_um,MeanCircularity_Surge,MeanOxySurgeBoundingBox,NumOxySurgeEvents, ...
    Start_Surge,Duration_Surge,NormOxySurgeAmp,Size_Surge_modulation,OxySurge_Pxls_all, ...
    'VariableNames',{'Experiment_Surge','Mouse_Surge','Condition_Surge','DrugID_Surge', ...
    'Genotype_Surge','Promoter_Surge','RecDuration_Surge','RecAreaSize_Surge', ...
    'MeanCentroid_Surge_x','MeanCentroid_Surge_y','MeanOxySurgeArea_um','MeanOxySurgeFilledArea_um', ...
    'MeanOxySurgeDiameter_um','MeanOxySurgePerimeter_um','MeanCircularity_Surge', ...
    'MeanOxySurgeBoundingBox','NumOxySurgeEvents','Start_Surge','Duration_Surge', ...
    'NormOxySurgeAmp','Size_Surge_modulation','OxySurge_Pxls_all'});

end
