function Table_OxygenSinks_Out = createOxygenSinkSummaryTable(Experiment,Mouse,Condition,DrugID,Genotype,Promoter, ...
    RecDuration,RecAreaSize,MeanCentroid_x,MeanCentroid_y,MeanOxySinkArea_um,MeanOxySinkFilledArea_um, ...
    MeanOxySinkDiameter_um,MeanOxySinkPerimeter_um,MeanCircularity,MeanOxySinkBoundingBox, ...
    NumOxySinkEvents,Start,Duration,NormOxySinkAmp,Size_modulation,OxySink_Pxls_all)
%CREATEOXYGENSINKSUMMARYTABLE Build the recording-level oxygen-sink output table.

Table_OxygenSinks_Out = table(Experiment,Mouse,Condition,DrugID,Genotype,Promoter, ...
    RecDuration,RecAreaSize,MeanCentroid_x,MeanCentroid_y,MeanOxySinkArea_um,MeanOxySinkFilledArea_um, ...
    MeanOxySinkDiameter_um,MeanOxySinkPerimeter_um,MeanCircularity,MeanOxySinkBoundingBox, ...
    NumOxySinkEvents,Start,Duration,NormOxySinkAmp,Size_modulation,OxySink_Pxls_all, ...
    'VariableNames',{'Experiment','Mouse','Condition','DrugID','Genotype','Promoter', ...
    'RecDuration','RecAreaSize','MeanCentroid_x','MeanCentroid_y','MeanOxySinkArea_um', ...
    'MeanOxySinkFilledArea_um','MeanOxySinkDiameter_um','MeanOxySinkPerimeter_um', ...
    'MeanCircularity','MeanOxySinkBoundingBox','NumOxySinkEvents','Start','Duration', ...
    'NormOxySinkAmp','Size_modulation','OxySink_Pxls_all'});

end
