function Options = createHypoxiaAmyloidRunOptions(RunConfig,Overwrite,RecordingIndex)
%CREATEHYPOXIAAMYLOIDRUNOPTIONS Translate wrapper configuration to module options.

if nargin<3
    RecordingIndex = 0;
end

Options = struct();
Options.OverwriteOutputs = Overwrite;
Options.SaveFigures = RunConfig.hypoxiaAmyloidSaveFigures;
Options.PairOptions = struct( ...
    'AmyloidThreshold',RunConfig.hypoxiaAmyloidAmyloidThreshold, ...
    'HypoxiaThreshold',RunConfig.hypoxiaAmyloidHypoxiaThreshold, ...
    'MinimumPlaqueAreaPixels',RunConfig.hypoxiaAmyloidMinimumPlaqueAreaPixels, ...
    'RegionSigmaMicrometers',RunConfig.hypoxiaAmyloidRegionSigmaMicrometers, ...
    'CoarseSigmaMicrometers',RunConfig.hypoxiaAmyloidCoarseSigmaMicrometers, ...
    'NumPermutations',RunConfig.hypoxiaAmyloidNumSpatialPermutations, ...
    'RandomSeed',RunConfig.hypoxiaAmyloidRandomSeed+RecordingIndex);
Options.PropertyOptions = struct( ...
    'NearThresholdMicrometers',RunConfig.hypoxiaAmyloidNearThresholdMicrometers, ...
    'SensitivityThresholdsMicrometers',RunConfig.hypoxiaAmyloidSensitivityThresholdsMicrometers, ...
    'MinimumObservationsPerStratum',RunConfig.hypoxiaAmyloidMinimumObservationsPerStratum, ...
    'DistanceVariable',RunConfig.hypoxiaAmyloidDistanceVariable);
end
