function [EventSnippetTables,EventSnippetSheetNames] = createStatsEventSnippetExports( ...
    ManualEvents,LPawEvents,RPawEvents,GroomEvents,PupilEvents,PuffEvents,WhiskEvents)
%CREATESTATSEVENTSNIPPETEXPORTS Prepare event-snippet export tables and sheet names.

EventSnippetTables = { ...
    createManualEventSnippetExportTable(ManualEvents), ...
    createEventSnippetExportTable(LPawEvents), ...
    createEventSnippetExportTable(RPawEvents), ...
    createEventSnippetExportTable(GroomEvents), ...
    createEventSnippetExportTable(PupilEvents), ...
    createEventSnippetExportTable(PuffEvents), ...
    createEventSnippetExportTable(WhiskEvents)};

EventSnippetSheetNames = {'ROI_MeanTraceSnip_ManEvents','ROI_MeanTraceSnip_LPawEvents', ...
    'ROI_MeanTraceSnip_RPawEvents','ROI_MeanTraceSnip_GroomEvents', ...
    'ROI_MeanTraceSnip_PupilEvents','ROI_MeanTraceSnip_PuffEvents', ...
    'ROI_MeanTraceSnip_WhiskEvents'};

end
