function [FiltersOxySinksMetrics,FiltersOxySurgesMetrics,FiltersROIsAndEvents] = ...
    createStatsAnalysisFilters(TableOxygenSinks,TableOxygenSurges,ROIsTraces, ...
    DrugsUnique,ConditionsUnique,StimUnique)
%CREATESTATSANALYSISFILTERS Build metric and ROI/event group filters.

FiltersOxySinksMetrics = createStatsGroupFilters(TableOxygenSinks.DrugID, ...
    TableOxygenSinks.Condition,TableOxygenSinks.PuffStim, ...
    DrugsUnique,ConditionsUnique,StimUnique,'mouseValues',TableOxygenSinks.Mouse);
FiltersOxySurgesMetrics = createStatsGroupFilters(TableOxygenSurges.DrugID, ...
    TableOxygenSurges.Condition,TableOxygenSurges.PuffStim, ...
    DrugsUnique,ConditionsUnique,StimUnique,'mouseValues',TableOxygenSurges.Mouse);

FiltersROIsAndEvents = createStatsGroupFilters(ROIsTraces(:,4),ROIsTraces(:,3), ...
    cell2mat(ROIsTraces(:,5)),DrugsUnique,ConditionsUnique,StimUnique, ...
    'withStimLabel','With_stimulation','withoutStimLabel','Without_stimulation');

end
