function Table_OxygenSinkEvents_Out = createOxygenSinkEventTable(EventExperiment,EventMouse,EventCondition, ...
    EventDrugID,EventGenotype,EventPromoter,EventPuffStim,SinkID,EventID,StartFrame,EndFrame, ...
    StartSec,EndSec,DurationFrames,DurationSec,EventNormOxySinkAmp,EventNormOxySinkAmpPercent, ...
    EventSize_modulation,EventDetectionOxySinkAmp,EventMeanOxySinkArea_um,EventMeanOxySinkFilledArea_um, ...
    EventMeanOxySinkDiameter_um,EventMeanOxySinkPerimeter_um,EventMeanCircularity,EventMeanCentroid_x, ...
    EventMeanCentroid_y)
%CREATEOXYGENSINKEVENTTABLE Build the event-level oxygen-sink output table.

Table_OxygenSinkEvents_Out = table(EventExperiment,EventMouse,EventCondition,EventDrugID, ...
    EventGenotype,EventPromoter,EventPuffStim,SinkID,EventID,StartFrame,EndFrame,StartSec,EndSec, ...
    DurationFrames,DurationSec,EventNormOxySinkAmp,EventNormOxySinkAmpPercent,EventSize_modulation, ...
    EventDetectionOxySinkAmp,EventMeanOxySinkArea_um,EventMeanOxySinkFilledArea_um, ...
    EventMeanOxySinkDiameter_um,EventMeanOxySinkPerimeter_um,EventMeanCircularity,EventMeanCentroid_x, ...
    EventMeanCentroid_y,'VariableNames',{'Experiment','Mouse','Condition','DrugID','Genotype', ...
    'Promoter','PuffStim','SinkID','EventID','StartFrame','EndFrame','StartSec','EndSec', ...
    'DurationFrames','DurationSec','NormOxySinkAmp','NormOxySinkAmpPercent','Size_modulation', ...
    'DetectionOxySinkAmp','MeanOxySinkArea_um','MeanOxySinkFilledArea_um','MeanOxySinkDiameter_um', ...
    'MeanOxySinkPerimeter_um','MeanCircularity','MeanCentroid_x','MeanCentroid_y'});

end
