function Table_OxygenSurgeEvents_Out = createOxygenSurgeEventTable(SurgeEventExperiment,SurgeEventMouse, ...
    SurgeEventCondition,SurgeEventDrugID,SurgeEventGenotype,SurgeEventPromoter,SurgeEventPuffStim, ...
    SurgeID,SurgeEventID,SurgeStartFrame,SurgeEndFrame,SurgeStartSec,SurgeEndSec,SurgeDurationFrames, ...
    SurgeDurationSec,EventNormOxySurgeAmp,EventNormOxySurgeAmpPercent,EventSize_Surge_modulation, ...
    EventMeanOxySurgeArea_um,EventMeanOxySurgeFilledArea_um,EventMeanOxySurgeDiameter_um, ...
    EventMeanOxySurgePerimeter_um,EventMeanCircularity_Surge,EventMeanCentroid_Surge_x, ...
    EventMeanCentroid_Surge_y)
%CREATEOXYGENSURGEEVENTTABLE Build the event-level oxygen-surge output table.

Table_OxygenSurgeEvents_Out = table(SurgeEventExperiment,SurgeEventMouse,SurgeEventCondition, ...
    SurgeEventDrugID,SurgeEventGenotype,SurgeEventPromoter,SurgeEventPuffStim,SurgeID,SurgeEventID, ...
    SurgeStartFrame,SurgeEndFrame,SurgeStartSec,SurgeEndSec,SurgeDurationFrames,SurgeDurationSec, ...
    EventNormOxySurgeAmp,EventNormOxySurgeAmpPercent,EventSize_Surge_modulation, ...
    EventMeanOxySurgeArea_um,EventMeanOxySurgeFilledArea_um,EventMeanOxySurgeDiameter_um, ...
    EventMeanOxySurgePerimeter_um,EventMeanCircularity_Surge,EventMeanCentroid_Surge_x, ...
    EventMeanCentroid_Surge_y,'VariableNames',{'Experiment','Mouse','Condition','DrugID','Genotype', ...
    'Promoter','PuffStim','SurgeID','EventID','StartFrame','EndFrame','StartSec','EndSec', ...
    'DurationFrames','DurationSec','NormOxySurgeAmp','NormOxySurgeAmpPercent','Size_Surge_modulation', ...
    'MeanOxySurgeArea_um','MeanOxySurgeFilledArea_um','MeanOxySurgeDiameter_um', ...
    'MeanOxySurgePerimeter_um','MeanCircularity_Surge','MeanCentroid_Surge_x','MeanCentroid_Surge_y'});

end
