function J=createBOIPocketJudgment(Review,Index,Onset,ObservedEnd,Reference,ReferenceState,EndpointState,Reviewer,Reason,ClockAuthority,Previous)
%CREATEBOIPOCKETJUDGMENT Explicit frames only; never inferred on row selection.
if nargin<11,Previous=[];end
row=Review.Audit(Index,:);t=Review.Traces{Index};revision=1;prior=[];
if ~isempty(Previous)
    assert(strcmp(Previous.AuditSHA256,Review.AuditSHA256)&&Previous.AuditRow==Index,'OxygenDynamics:PocketIdentityMismatch','Previous revision belongs to another audit/event.');
    revision=Previous.Judgment.Revision+1;prior=struct('JudgmentSHA256',Previous.JudgmentSHA256,'Revision',Previous.Judgment.Revision);
end
J=struct('Schema','boi-reviewed-pocket-judgment-1','Revision',revision,'PreviousRevision',prior, ...
    'Interpretation','researcher_reviewed_pocket','AuditRow',Index,'AuditSHA256',Review.AuditSHA256, ...
    'RawSourceSHA256',Review.AnalysisInfo.RawSHA256,'SavedEvent',table2struct(row(:,{'RecordingID','EventType','SiteID','EventID'})), ...
    'FixedFootprintSHA256',boiPocketDigest(double(t.Footprint(:))),'OnsetFrame',Onset,'ObservedEndFrame',ObservedEnd, ...
    'ReferenceFrames',double(Reference(:)),'ReferenceSuitability',char(ReferenceState),'EndpointStatus',char(EndpointState), ...
    'Reviewer',char(Reviewer),'Reason',char(Reason),'ClockAuthority',char(ClockAuthority), ...
    'RecordedUTC',char(datetime('now','TimeZone','UTC','Format','yyyy-MM-dd''T''HH:mm:ss''Z''')));
J.BoundaryRevision=struct('Revision',revision,'OnsetFrame',Onset,'ObservedEndFrame',ObservedEnd,'EndpointStatus',char(EndpointState));
J.ReferenceRevision=struct('Revision',revision,'Frames',double(Reference(:)),'Suitability',char(ReferenceState));
end
