function [ExportReady,GroupHeaders] = createStatsMetricWorkbookData(TableOxygenSinks, ...
    TableOxygenSurges,AdditionalOxygenSinkMetrics,AdditionalOxygenSurgeMetrics, ...
    FiltersOxySinksMetrics,FiltersOxySurgesMetrics)
%CREATESTATSMETRICWORKBOOKDATA Prepare grouped sink/surge metric export tables.

SinkMetricSources = [TableOxygenSinks(:,{'MeanOxySinkArea_um','MeanOxySinkFilledArea_um', ...
    'MeanOxySinkDiameter_um','MeanOxySinkPerimeter_um'}),AdditionalOxygenSinkMetrics];
SinkMetricNames = {'MeanOxySinkArea_um','MeanOxySinkFilledArea_um','MeanOxySinkDiameter_um', ...
    'MeanOxySinkPerimeter_um','OxySinkArea_Norm','OxySinkArea_Filled_Norm', ...
    'SinkSiteEventRate_per_min','MeanOxySinkEvent_Duration','MeanOxySinkEvent_NormAmp', ...
    'MeanOxySinkEvent_SizeModulation'};
[FilteredSinkData,FilteredSinkMice] = filterStatsMetricData(TableOxygenSinks.Mouse, ...
    SinkMetricSources,SinkMetricNames,FiltersOxySinksMetrics);

SurgeMetricSources = [TableOxygenSurges(:,{'MeanOxySurgeArea_um','MeanOxySurgeFilledArea_um', ...
    'MeanOxySurgeDiameter_um','MeanOxySurgePerimeter_um'}),AdditionalOxygenSurgeMetrics];
SurgeMetricNames = {'MeanOxySurgeArea_um','MeanOxySurgeFilledArea_um','MeanOxySurgeDiameter_um', ...
    'MeanOxySurgePerimeter_um','OxySurgeArea_Norm','OxySurgeArea_Filled_Norm', ...
    'SurgeSiteEventRate_per_min','MeanOxySurgeEvent_Duration','MeanOxySurgeEvent_NormAmp', ...
    'MeanOxySurgeEvent_SizeModulation'};
[FilteredSurgeData,FilteredSurgeMice] = filterStatsMetricData(TableOxygenSurges.Mouse, ...
    SurgeMetricSources,SurgeMetricNames,FiltersOxySurgesMetrics);

GroupHeaders = FiltersOxySinksMetrics(1:3,:);
ExportReady = cell(10,2);
ExportReady(:,1) = createStatsMetricExportTables(FilteredSinkData,FilteredSinkMice,FiltersOxySinksMetrics);
ExportReady(:,2) = createStatsMetricExportTables(FilteredSurgeData,FilteredSurgeMice,FiltersOxySurgesMetrics);

end
