function Receipt=exportBOIEventReview(Review,Index,OutputFolder,DictionaryPath)
%EXPORTBOIEVENTREVIEW Export saved ingredients to a NEW local review folder.
% Contains local paths; not a sanitized public export or scientific decision.
if nargin<4,DictionaryPath='';end
assert(~isfolder(OutputFolder)&&~isfile(OutputFolder),'OxygenDynamics:ReviewOutputExists','Choose a new folder; earlier review exports are preserved.');
assert(strcmp(oxygenFileSHA256(Review.AuditPath),Review.AuditSHA256), ...
    'OxygenDynamics:EventReviewChanged','Saved audit changed since opening. Reopen before exporting.');
if isfield(Review,'BoundaryReview')&&~isempty(Review.BoundaryReview)
    checked=loadBOIBoundaryReview(Review,Review.BoundaryReview.Path);
    assert(strcmp(checked.SHA256,Review.BoundaryReview.SHA256),'OxygenDynamics:BoundaryReviewChanged','Boundary review changed. Reload before exporting.');
    Review.BoundaryReview=checked;
end
pocket=[];
if isfield(Review,'PocketEvidence')&&numel(Review.PocketEvidence)>=Index&&~isempty(Review.PocketEvidence{Index})
    pocket=Review.PocketEvidence{Index};
    checked=loadBOIReviewedPocketEvidence(pocket.Path);
    assert(strcmp(checked.SHA256,pocket.SHA256),'OxygenDynamics:InvalidPocketEvidence','Saved pocket revision changed.');
    Review=attachBOIPocketEvidence(Review,Index,pocket.Path); % Pre-directory binding validation.
end
Data=buildBOIEventReviewData(Review,Index);
ReviewedReferencePreview=buildBOIReviewedReferencePreview(Review,Index);
ReviewedOpticalPreview=buildBOIReviewedOpticalPreview(Review,Index);
if isfield(Data,'WindowLink')
    assert(strcmp(oxygenFileSHA256(Data.WindowLink.ResultsPath),Data.WindowLink.ResultsSHA256), ...
        'OxygenDynamics:WindowReviewChanged','Linked statistics changed. Reopen the window and reconnect before exporting.');
end
native=[];
if isfield(Data,'NativeMaskAttachment'),native=validateBOINativeMaskSource(Review,Index);end
[~,dictionary,source]=getBOIMeasurementDictionary(DictionaryPath);
dictionaryText=fileread(source);dictionaryHash=oxygenFileSHA256(source);
role='current_definitions_context_only';if ~isempty(DictionaryPath),role='user_selected_saved_dictionary; run_correspondence_not_automatically_verified';end
mkdir(OutputFolder);
writetable(Data.Frames,fullfile(OutputFolder,'SelectedEventTrace.csv'));
[r,c]=ind2sub(Review.AnalysisInfo.FrameSize,Data.Footprint(:));
writetable(table(Data.Footprint(:),r,c,'VariableNames',{'MatlabLinearPixel','PixelRow','PixelColumn'}),fullfile(OutputFolder,'FixedAmplitudeFootprint.csv'));
if ~isempty(native)
    cells=native.FramePixels;counts=cellfun(@numel,cells);frame=repelem((1:numel(cells))',counts);
    pixels=vertcat(cells{:});[r,c]=ind2sub(native.FrameSize,pixels);
    writetable(table(frame,pixels,r,c,'VariableNames',{'Frame','MatlabLinearPixel','PixelRow','PixelColumn'}),fullfile(OutputFolder,'NativeEventFramePixels.csv'));
end
writeText(fullfile(OutputFolder,'BOIMeasurementDictionary.json'),dictionaryText);
writeText(fullfile(OutputFolder,'EventReview.txt'),strjoin(string(Data.Details),newline));
Receipt=struct('Schema','boi-event-review-export-9','CreatedUTC',char(datetime('now','TimeZone','UTC','Format','yyyy-MM-dd''T''HH:mm:ssXXX')), ...
    'ScientificStatus','not_established','SavedAuditPath',Review.AuditPath,'SavedAuditSHA256',Review.AuditSHA256, ...
    'SelectedEvent',table2struct(Data.Row),'ReplayAmplitude',Data.ReplayedAmplitude,'ReplayMatches',Data.ReplayMatches, ...
    'ReplayedBaseline',Data.ReplayedBaseline,'BaselineReplayMatches',Data.BaselineReplayMatches, ...
    'AnalysisInfo',Review.AnalysisInfo,'Acquisition',Review.Acquisition,'AcquisitionQC',Review.QC, ...
    'DictionaryVersion',dictionary.Version,'DictionarySHA256',dictionaryHash,'DictionaryRole',role, ...
    'NativeFrameMasks','not_present_in_saved_audit','SourceImageIncluded',false, ...
    'DetectorReruns',0,'StatisticsReruns',0,'BaselineDiagnostic',Data.BaselineDiagnostic,'TimingReview',Data.TimingReview);
Receipt.ReviewedReferencePreview=rmfield(ReviewedReferencePreview,{'Frames','Contributors'});
writeText(fullfile(OutputFolder,'ReviewedReferencePreview.json'),jsonencode(Receipt.ReviewedReferencePreview,'PrettyPrint',true));
if ~isempty(ReviewedReferencePreview.Windows)
    writetable(ReviewedReferencePreview.Frames,fullfile(OutputFolder,'ReviewedReferenceFrames.csv'));
    writetable(ReviewedReferencePreview.Contributors,fullfile(OutputFolder,'ReviewedReferenceContributors.csv'));
end
Receipt.ReviewedOpticalPreview=ReviewedOpticalPreview;
writeText(fullfile(OutputFolder,'ReviewedOpticalPreview.json'),jsonencode(ReviewedOpticalPreview,'PrettyPrint',true));
writeText(fullfile(OutputFolder,'ReviewedOpticalDictionary.json'),jsonencode(ReviewedOpticalPreview.Definition.Dictionary,'PrettyPrint',true));
writeText(fullfile(OutputFolder,'ReviewedOpticalContract.json'),jsonencode(ReviewedOpticalPreview.Definition.Contract,'PrettyPrint',true));
if ~isempty(ReviewedOpticalPreview.Intervals)
    M=ReviewedOpticalPreview.Intervals;
    rows=table((1:numel(M))',[M.OnsetFrame]',[M.RecoveryFrame]',string({M.Status})',[M.ReferenceSampleCount]',[M.ReferenceMean]', ...
        [M.MinimumSignedChangeFraction]',[M.MaximumSignedChangeFraction]',[M.SavedSignDirectionalAmplitudeFraction]',[M.SignedTraceIntegralSec]', ...
        [M.DurationSec]',[M.EndpointSpanSec]','VariableNames',{'Interval','OnsetFrame','RecoveryFrame','Status','ReferenceSamples','ReferenceMean', ...
        'MinimumSignedFraction','MaximumSignedFraction','SavedSignAmplitudeFraction','SignedIntegralSec','DurationSec','EndpointSpanSec'});
    writetable(rows,fullfile(OutputFolder,'ReviewedOpticalIntervals.csv'));
    frames=table();
    for j=1:numel(M)
        m=M(j);f=[m.ReferenceFrames;m.EventFrames];isRef=[true(size(m.ReferenceFrames));false(size(m.EventFrames))];
        v=[m.ReferenceValues;m.EventValues];numerator=[nan(size(m.ReferenceFrames));m.Numerator];q=[nan(size(m.ReferenceFrames));m.SignedFraction];
        frames=[frames;table(repmat(j,numel(f),1),f,(f-1)/ReviewedOpticalPreview.SampleHz,isRef,v, ...
            repmat(m.ReferenceMean,numel(f),1),numerator,q,'VariableNames',{'Interval','Frame','ModeledTimeSec','AcceptedReference','PreservedInputMean','ReferenceMean','Numerator','SignedFraction'})]; %#ok<AGROW>
    end
    writetable(frames,fullfile(OutputFolder,'ReviewedOpticalSamples.csv'));
end
writeText(fullfile(OutputFolder,'ReviewedOpticalMethods.txt'),sprintf(['Exploratory reviewed BOI optical calculation, draft 0.1.0. No global scientific adoption.\n' ...
    'Use the preserved-input mean on the original fixed native-event union footprint. B=mean of exactly the accepted reference samples.\n' ...
    'q=(I-B)/B on inclusive reviewed event frames. Signed minimum=min(q); signed maximum=max(q). Percent=100*fraction. All tied extremum frames are retained in JSON/MAT.\n' ...
    'Saved sink convention=-min(q); saved surge convention=max(q). Preserve negative values and detection labels. Integral=sum(q)/fs, in fraction seconds.\n' ...
    'Duration=(b-a+1)/fs; endpoint span=(b-a)/fs. This draft assumes external trigger fs=1 Hz; acquisition evidence/QC are retained and exposure remains separate.\n' ...
    'Exact selected reference counts remain explicit, including shorter references and native overlap. They do not change original automatic requirements.\n' ...
    'Missing accepted reference, nonfinite samples or nonpositive/nonfinite B withhold dependent results. A valid B is retained when event samples are missing. No partial samples or sign repair.\n' ...
    'CSV/MAT NaN and JSON null mean unavailable. ReviewedOpticalSamples.csv has reference and event rows separately; signed fractions/numerators are defined only for computed event rows.\n' ...
    'Exact judgment documents, boundary alternatives, definition documents, source hashes, fixed pixels and raw ingredients are in ReviewedOpticalPreview.json/MAT.\n' ...
    'The embedded definition contract retains its original proposal status; ImplementationStatus separately identifies this implemented preview.\n' ...
    'These are optical descriptions, not oxygen concentration, deficit, recognition acceptance or independent validation. Original automatic results remain unchanged.\n']));
Receipt.ResearcherBoundaryReview=Data.ResearcherBoundaryReview;
writeText(fullfile(OutputFolder,'ResearcherBoundaries.json'),jsonencode(Data.ResearcherBoundaryReview,'PrettyPrint',true));
if isfield(Review,'BoundaryReview')&&~isempty(Review.BoundaryReview)
    writeText(fullfile(OutputFolder,'ResearcherBoundaryHistory.json'),jsonencode(Review.BoundaryReview.Document,'PrettyPrint',true));
end
writeText(fullfile(OutputFolder,'TimingReview.json'),jsonencode(Data.TimingReview,'PrettyPrint',true));
writeText(fullfile(OutputFolder,'BaselineDiagnostic.json'),jsonencode(Data.BaselineDiagnostic,'PrettyPrint',true));
if ~isempty(native)
    Receipt.NativeFrameMasks='attached_master_snapshot';
    Receipt.NativeMaskEvidence=rmfield(native,'FramePixels');
end
if isfield(Data,'WindowLink'),Receipt.WindowLink=Data.WindowLink;end
if isfield(Review,'AuditCreationReceipt'),Receipt.AuditCreationReceipt=Review.AuditCreationReceipt;end
Receipt.ReviewImplementation=struct('Function',{},'SHA256',{});
for name={'computeBOIReviewedOpticalInterval','getBOIReviewedOpticalDefinition','buildBOIReviewedOpticalPreview','createBOIReviewedOpticalPanel','loadBOIReferenceJudgments','attachBOIReferenceSources','buildBOIReviewedReferencePreview','createBOIReviewedReferencePanel','getBOIBoundaryReview','loadBOIBoundaryReview','saveBOIBoundaryReview','validateBOIBoundaryAnnotation','createBOIBoundaryPanel','loadBOIEventReview','buildBOIEventReviewData','buildBOITimingReviewData','createBOITimingPanel','buildBOIBaselineDiagnostic','createBOIBaselinePanel','openBOIEventReview','exportBOIEventReview','getBOIMeasurementDictionary','attachBOINativeMasks','validateBOINativeMaskSource','linkBOIWindowEventReview'}
    Receipt.ReviewImplementation(end+1)=struct('Function',name{1},'SHA256',oxygenFileSHA256(which(name{1})));
end
if ~isempty(pocket)
    savedPocket=exportBOIReviewedPocketEvidence(pocket,fullfile(OutputFolder,'ReviewedPocket'));
    Receipt.ReviewedPocket=struct('Path','ReviewedPocket','ManifestSHA256',savedPocket.SHA256, ...
        'DefinitionID',savedPocket.Document.Definition.ID,'JudgmentSHA256',savedPocket.Document.JudgmentSHA256, ...
        'PrimaryStatus',savedPocket.Document.Measures.PrimaryStatus,'Suitability',savedPocket.Document.Judgment.ReferenceSuitability, ...
        'EndpointStatus',savedPocket.Document.Judgment.EndpointStatus,'FootprintQualification',savedPocket.Document.FootprintQualification, ...
        'Role','separate_saved_exploratory_revision_drafts_excluded');
end
% MAT preserves NaN and table types; JSON null means unavailable, never zero.
save(fullfile(OutputFolder,'SelectedEventReview.mat'),'Data','Receipt','ReviewedReferencePreview','ReviewedOpticalPreview');
writeText(fullfile(OutputFolder,'SelectedEventReview.json'),jsonencode(Receipt,'PrettyPrint',true));
writeText(fullfile(OutputFolder,'README.txt'),sprintf(['Local BOI event review; scientific eligibility is not established.\n' ...
    'SelectedEventTrace.csv holds all recorded frames, explicit sample membership and signed fractions.\n' ...
    'TimingReview.json records corrected-primary, detection-support and raw correction-quality roles, saved-stage availability and provenance.\n' ...
    'CorrectedIntensity, FilteredDetectionScore and SavedSiteTimingTrace are saved signals; absent/invalid stages stay unavailable, not substituted.\n' ...
    'ExistingRemovedTrend is raw minus saved corrected mean only when their shared input is recorded; it is not a new fit or amplitude baseline.\n' ...
    'Timing sample positions use Frame; ModeledTimeSec=(Frame-1)/SampleHz. Exposure duration is separate. Manual judgments remain separate from saved measurement bounds.\n' ...
    'ResearcherBoundaries.json contains only SAVED judgments for this event; unsaved UI drafts are excluded.\n' ...
    'ResearcherBoundaryHistory.json, when attached, retains all reviewed events and old/new annotations, reviewer, reason and UTC revision time.\n' ...
    'Researcher alternatives are discrete one-based frames; empty endpoints are unresolved. No amplitude or native-mask recalculation uses them.\n' ...
    'ReviewedReferencePreview.json records proposed A/B eligibility and separately attached researcher judgments, never a new mean or amplitude. Neither policy is adopted.\n' ...
    'When saved onsets exist, ReviewedReferenceFrames.csv and ReviewedReferenceContributors.csv explain sample eligibility and both-sign exclusions.\n' ...
    'ResearcherSelectedReference is 1 selected, 0 outside that saved selection, NaN when no judgment exists for this onset. Original judgment documents and source hashes accompany the preview.\n' ...
    'ReviewedOpticalPreview.json and the separate MAT variable contain new exploratory quantities under draft 0.1.0; see ReviewedOpticalMethods.txt. Original Data remains unchanged.\n' ...
    'Unknown native support stays NaN, not zero. Source hashes, saved revision, recovery contacts and alternatives accompany the preview.\n' ...
    'BaselineDiagnostic.json is a versioned review-only calculation; it never replaces the saved amplitude or mean baseline.\n' ...
    'Reference sensitivity is DifferenceFromAuditedAmplitude_pp: line minus the audited constant-reference amplitude on the same source.\n' ...
    'SavedMeasurementMatchesAudit and AuditAgreementMessage expose saved-versus-audited disagreement independently of trace replay.\n' ...
    'SavedBaseline and AuditedBaseline retain their distinct roles; missing historical StoredBaseline remains unavailable.\n' ...
    'DifferenceFromSavedAmplitude_pp is retained but may include audit disagreement; it is not the reference-sensitivity measure.\n' ...
    'DiagnosticLinearReference is present only on clean-baseline and measurement frames when a fit is available.\n' ...
    'DiagnosticLinearSignedFraction is present only on measurement frames when the whole alternative measurement is available.\n' ...
    'A nonpositive/nonfinite event reference withholds the entire alternative amplitude/integral; no clipping or earlier baseline search.\n' ...
    'Raw reference values may still be shown to explain an invalid extrapolation. Negative and very small values are retained.\n' ...
    'The original SignedFraction, selected saved event, dictionary and statistics are unchanged. MAT retains exact unavailable values and diagnostic metadata.\n' ...
    'CSV membership flags are 1 for included and 0 for excluded; use flag==1 when indexing after readtable.\n' ...
    'FixedAmplitudeFootprint.csv is the union used for amplitude, not a native frame mask or tissue boundary.\n' ...
    'If attached, NativeEventFramePixels.csv contains only the selected native event run.\n' ...
    'NativeMaskPixels in the trace CSV is NaN when unavailable, or a pixel count (including known zero outside the attached run).\n' ...
    'Native masks are detected event support, not reviewed anatomical tissue. Master association is recorded at attachment, not retroactively at the original audit.\n' ...
    'WindowLink, when present, identifies the originating statistics/window and event overlap; this association was checked when connecting the reviewers.\n' ...
    'Source image is not included. The audit contains saved quantitative traces; it is not a new analysis.\n' ...
    'NaN in MATLAB/CSV and null in JSON represent unavailable values, never zero.\n' ...
    'Dictionary role: %s. Selection alone does not establish the dictionary used by the audit.\n' ...
    'ReviewedPocket/, when present, is a separate explicitly SAVED 0.2.0 exploratory revision, exact samples and identity-bound manifest; drafts are excluded. Automatic/legacy results are unchanged.\n' ...
    'Original source paths and metadata are retained; review before public sharing.\n'],role));
files=dir(OutputFolder);manifest=struct('Name',{},'SHA256',{});
for k=1:numel(files)
    if ~files(k).isdir,manifest(end+1)=struct('Name',files(k).name,'SHA256',oxygenFileSHA256(fullfile(OutputFolder,files(k).name)));end %#ok<AGROW>
end
writeText(fullfile(OutputFolder,'ArtifactChecksums.json'),jsonencode(manifest,'PrettyPrint',true));
end
function writeText(path,value)
fid=fopen(path,'w');assert(fid>=0);cleanup=onCleanup(@()fclose(fid));fprintf(fid,'%s\n',value);
end
