function EventSnips = extractStatsBLIEventSnippets(ROIsTraces,ManualEvents, ...
    BehaviourLogicals,SampleFs,BehFs,PuffsFs,TimeWindows)
%EXTRACTSTATSBLIEVENTSNIPPETS Extract BLI manual and behaviour event snippets.

EventSnips = struct();
EventSnips.Manual = extractManualEventMeanTraceSnips( ...
    ROIsTraces,ManualEvents,SampleFs,str2double(TimeWindows{1}));
[EventSnips.LPaw,EventSnips.RPaw,EventSnips.Groom, ...
    EventSnips.Pupil,EventSnips.Puff,EventSnips.Whisk] = extractStatsBehaviourEventSnips( ...
    ROIsTraces,BehaviourLogicals,SampleFs,BehFs,PuffsFs,TimeWindows);

end
