function [LPawEvents,RPawEvents,GroomEvents,PupilEvents,PuffEvents,WhiskEvents] = ...
    extractStatsBehaviourEventSnips(ROIsTraces,BehaviourLogicals,SampleFs,BehFs,PuffsFs,TimeWindows)
%EXTRACTSTATSBEHAVIOUREVENTSNIPS Extract ROI mean snippets for behaviour events.

MovementWindowSec = str2double(TimeWindows{2});
PupilWindowSec = str2double(TimeWindows{3});
PuffWindowSec = str2double(TimeWindows{4});

LPawEvents = extractBehaviourEventMeanTraceSnips( ...
    ROIsTraces,BehaviourLogicals(:,1),SampleFs,BehFs,MovementWindowSec);
RPawEvents = extractBehaviourEventMeanTraceSnips( ...
    ROIsTraces,BehaviourLogicals(:,2),SampleFs,BehFs,MovementWindowSec);
GroomEvents = extractBehaviourEventMeanTraceSnips( ...
    ROIsTraces,BehaviourLogicals(:,3),SampleFs,BehFs,MovementWindowSec);
PupilEvents = extractBehaviourEventMeanTraceSnips( ...
    ROIsTraces,BehaviourLogicals(:,4),SampleFs,BehFs,PupilWindowSec);
PuffEvents = extractBehaviourEventMeanTraceSnips( ...
    ROIsTraces,BehaviourLogicals(:,5),SampleFs,PuffsFs,PuffWindowSec);
WhiskEvents = extractBehaviourEventMeanTraceSnips( ...
    ROIsTraces,BehaviourLogicals(:,6),SampleFs,BehFs,MovementWindowSec);

end
