function text=formatBOIPocketEvidence(E)
%FORMATBOIPOCKETEVIDENCE Human-readable methods with all scientific qualifiers.
M=E.Measures;J=E.Judgment;
lines=["# Researcher-reviewed pocket — exploratory optical evidence"; ...
    "";"Primary corrected signed trough: "+number(M.CorrectedSignedTroughPercent)+" % of positive raw reference intensity ("+string(M.PrimaryStatus)+")."; ...
    "Raw signed trough alongside: "+number(M.RawSignedTroughPercent)+" % ("+string(M.CompanionStatus)+")."; ...
    "Negative means downward optical excursion; neither value is oxygen percentage or an absolute pO2 measurement."; ...
    "";"Episode frames: "+frames(E.EventFrames)+". Reference frames: "+frames(E.ReferenceFrames)+" ("+M.ReferenceSampleCount+" samples)."; ...
    "Reference suitability: "+string(J.ReferenceSuitability)+". Ordinary fluctuations are allowed; no automatic replacement or sample exclusion."; ...
    "Endpoint: "+string(J.EndpointStatus)+"; observed end "+J.ObservedEndFrame+". Confirmed pocket duration is not established by this artifact."; ...
    "";"**"+string(E.FootprintQualification)+"**"; ...
    "Fixed footprint: "+numel(E.FixedFootprint)+" pixels; saved detector sign "+string(E.FootprintOrigin)+"."; ...
    "Original automatic amplitude: "+number(100*E.OriginalAutomatic.StoredAmplitude)+" %; status "+string(E.OriginalAutomatic.RecomputedStatus)+". Unchanged; saved-sign convention differs from signed trough."; ...
    "";"Primary = 100*min((corrected(W)-mean(corrected(R)))/mean(raw(R)))."; ...
    "Companion = 100*min((raw(W)-mean(raw(R)))/mean(raw(R))). Same explicit frames, footprint and positive raw denominator."; ...
    "Raw reference mean: "+number(M.RawReferenceMean)+"; corrected reference mean: "+number(M.CorrectedReferenceMean)+" input units."; ...
    "Correction origin: "+string(E.Correction.Origin)+". Saved ingredients only; no fitting, score substitution or universal decline assumption."; ...
    "Corrected minimum frames: "+frames(M.CorrectedMinimumFrames)+"; raw minimum frames: "+frames(M.RawMinimumFrames)+"."; ...
    "Clock: "+string(J.ClockAuthority)+"; frame 1 = modeled 0 s at 1 Hz; exposure duration is separate."; ...
    "";"Reviewer: "+string(J.Reviewer)+"; revision "+J.Revision+"; "+string(J.RecordedUTC)+"."; ...
    "Reason: "+string(J.Reason); ...
    "Audit SHA256: "+string(E.AuditSHA256);"Raw source SHA256: "+string(E.RawSourceSHA256); ...
    "Footprint SHA256: "+string(E.FixedFootprintSHA256);"Judgment SHA256: "+string(E.JudgmentSHA256); ...
    "Definition: "+string(E.Definition.ID); ...
    "";"Native overlap context: "+string(E.NativeOverlapContext)+". Spatial phase extent and broader-hyperemia/local-pocket mechanism remain unestablished."; ...
    "Saved values reopen without arithmetic replay. Export embeds exact samples and footprint. NaN/null means unavailable, never zero."; ...
    "Automatic results, detector provenance and legacy raw reviewed definition remain separate. No recording, detector or statistics execution; no automatic relabelling."; ...
    "This artifact carries local paths; it is a local/portable scientific-review export, not an approved public release."];
text=char(strjoin(lines,newline));
end
function s=number(x)
s="unavailable";if isfinite(x),s=string(sprintf('%.15g',x));end
end
function s=frames(f)
s="none";if ~isempty(f),s=strjoin(string(f(:)'),", ");end
end
