function B=getBOIBoundaryReview(Review,Index)
%GETBOIBOUNDARYREVIEW Select saved human history without altering measurements.
B=struct('Schema','boi-selected-researcher-boundaries-1','Status','not_reviewed', ...
    'Role','researcher judgment; separate from automatic measurements and native masks', ...
    'Annotation',[],'History',[],'ArtifactPath','','ArtifactSHA256','', ...
    'SavedAuditSHA256',Review.AuditSHA256,'RawSourceSHA256',Review.AnalysisInfo.RawSHA256, ...
    'FrameOrigin',1,'SampleHz',Review.AnalysisInfo.AnalysisParams.fs, ...
    'Event',table2struct(Review.Audit(Index,{'RecordingID','EventType','SiteID','EventID','StartFrame','EndFrame','DetectedStartFrame','DetectedEndFrame'}))); 
if ~isfield(Review,'BoundaryReview')||isempty(Review.BoundaryReview),return;end
S=Review.BoundaryReview;R=S.Document.Revisions;R=R([R.AuditRow]==Index);
B.ArtifactPath=S.Path;B.ArtifactSHA256=S.SHA256;
if isempty(R),return;end
B.Annotation=R(end).Annotation;B.Status=B.Annotation.Status;B.History=R;
end
