function [EventReview,AuditIndex]=linkBOIWindowEventReview(Review,WindowIndex,EventIndex,AuditPath,kind)
%LINKBOIWINDOWEVENTREVIEW Explicit, source-checked association made at review time.
if nargin<5,kind='sink';end
assert(strcmp(oxygenFileSHA256(Review.Path),Review.SHA256),'OxygenDynamics:WindowReviewChanged','Saved results changed. Reopen before connecting event evidence.');
D=buildBOIWindowReviewData(Review,WindowIndex,kind);
assert(isscalar(EventIndex)&&EventIndex==fix(EventIndex)&&EventIndex>=1&&EventIndex<=height(D.Events), ...
    'OxygenDynamics:WindowEventIdentity','Select an event in the window event table.');
EventReview=loadBOIEventReview(AuditPath);I=EventReview.AnalysisInfo;C=D.Contract;
assert(strcmp(I.RawSHA256,C.RawSHA256)&&I.NFrames==C.NFrames&&I.AnalysisParams.fs==C.SampleHz&& ...
    isequal(I.FrameSize,C.FrameSize)&&isfield(I.AnalysisParams,'PixelSize')&&I.AnalysisParams.PixelSize==C.PixelSizeUm, ...
    'OxygenDynamics:WindowEventSource','Audit source, frame grid, sampling or calibration differs from the window contract.');
for field={'SinkEligibleTissuePixels','SurgeEligibleTissuePixels'}
    assert(isfield(I,field{1})&&isequal(I.(field{1})(:),C.(field{1})(:)), ...
        'OxygenDynamics:WindowEventSource','Audit and saved window tissue support differ.');
end
snapshot=[];if isfield(I,'BOIAcquisitionMetadata'),snapshot=I.BOIAcquisitionMetadata;end
saved=[];if isfield(C,'AcquisitionSnapshot'),saved=C.AcquisitionSnapshot;end
assert(isequaln(snapshot,saved),'OxygenDynamics:WindowEventSource','Saved acquisition declarations differ.');
prefix='Sink';if strcmp(kind,'surge'),prefix='Surge';end
site=[prefix 'ID'];E=Review.(['Table_Oxygen' prefix 'Events_OutCombo']);row=D.Events(EventIndex,:);
k=find(string(E.RecordingID)==string(row.RecordingID)&E.(site)==row.(site)&E.EventID==row.EventID);
assert(isscalar(k),'OxygenDynamics:WindowEventIdentity','Require one saved event for the selected recording/site/event.');
E=E(k,:);sourceID=string(row.RecordingID);identityBasis='same_saved_recording_id';
if isfield(Review,'StatsInfo')&&isfield(Review.StatsInfo,'Recordings')&&ismember('StatsRecordingIndex',E.Properties.VariableNames)
    n=E.StatsRecordingIndex;
    assert(isscalar(n)&&n>=1&&n==fix(n)&&n<=numel(Review.StatsInfo.Recordings), ...
        'OxygenDynamics:WindowEventIdentity','Invalid saved recording-source index.');
    sourceID=string(Review.StatsInfo.Recordings(n).Folder);
    identityBasis='saved_StatsRecordingIndex_to_StatsInfo_Recordings_Folder';
end
A=EventReview.Audit;
AuditIndex=find(string(A.RecordingID)==sourceID&string(A.EventType)==string(kind)&A.SiteID==row.(site)&A.EventID==row.EventID);
assert(isscalar(AuditIndex),'OxygenDynamics:WindowEventIdentity', ...
    'No unique audit event matches the saved source-recording mapping, sign, site and event. Filename similarity is insufficient.');
A=A(AuditIndex,:);amp=['NormOxy' prefix 'Amp'];
required={'StartFrame','EndFrame','BaselineValue','BaselineStatus',amp};
assert(all(ismember(required,E.Properties.VariableNames))&&all(ismember({'StoredBaseline','StoredStatus'},A.Properties.VariableNames)), ...
    'OxygenDynamics:WindowEventIdentity','Saved event measurement fields are incomplete.');
assert(isequaln([E.StartFrame,E.EndFrame],[A.StartFrame,A.EndFrame])&& ...
    isequaln(E.BaselineValue,A.StoredBaseline)&&string(E.BaselineStatus)==string(A.StoredStatus)&& ...
    isequaln(E.(amp),A.StoredAmplitude)&&abs(E.StartSec-(A.StartFrame-1)/C.SampleHz)<1e-10&& ...
    abs(E.EndSec-A.EndFrame/C.SampleHz)<1e-10, ...
    'OxygenDynamics:WindowEventMeasurement','Saved event timing, baseline or amplitude differs from the audit.');
assert(strcmp(oxygenFileSHA256(Review.Path),Review.SHA256),'OxygenDynamics:WindowReviewChanged','Results changed during association. Reopen them.');
Link=struct('Schema','boi-window-event-link-1','LinkedUTC',char(datetime('now','TimeZone','UTC','Format','yyyy-MM-dd''T''HH:mm:ssXXX')), ...
    'ResultsPath',Review.Path,'ResultsSHA256',Review.SHA256,'AuditPath',EventReview.AuditPath, ...
    'AuditSHA256',EventReview.AuditSHA256,'SourceSHA256',C.RawSHA256, ...
    'StatsRecordingID',char(row.RecordingID),'AuditRecordingID',char(sourceID),'IdentityBasis',identityBasis, ...
    'WindowID',char(D.Window.WindowID),'WindowStartSec',D.Window.StartSec,'WindowEndSec',D.Window.EndSec, ...
    'EventType',char(kind),'SiteID',row.(site),'EventID',row.EventID, ...
    'OnsetInWindow',row.OnsetInWindow,'OverlapSec',row.OverlapSec,'OngoingAtWindowStart',row.OngoingAtWindowStart, ...
    'WindowSchema',char(D.Window.WindowAuditVersion),'WindowMetrics',table2struct(D.Metrics), ...
    'Association','Checked saved source mapping, grid, acquisition, tissue support and event timing/baseline/amplitude. Link created at review time; no historical audit-to-statistics checksum was present.', ...
    'ScientificStatus','not_established');
EventReview.WindowLinks=cell(height(EventReview.Audit),1);EventReview.WindowLinks{AuditIndex}=Link;
end
