function Review=loadBOIEventReview(AuditPath,MetadataPath)
%LOADBOIEVENTREVIEW Validate a saved audit; never recompute detection or stats.
AuditPath=char(java.io.File(char(AuditPath)).getCanonicalPath());
assert(~isfile(fullfile(fileparts(AuditPath),'AuditCreationFailure.json')), ...
    'OxygenDynamics:IncompleteEventAudit','Audit creation failed. Retain its failure record and create a new completed audit before inspection.');
before=oxygenFileSHA256(AuditPath);
S=load(AuditPath,'Audit','Traces','AnalysisInfo');
assert(all(isfield(S,{'Audit','Traces','AnalysisInfo'})), ...
    'OxygenDynamics:InvalidEventReview','Select event-amplitude-audit.mat with Audit, Traces and AnalysisInfo.');
A=S.Audit;T=S.Traces;I=S.AnalysisInfo;
historical=[];
if ~isfield(I,'FrameSize')
    assert(nargin>=2&&~isempty(MetadataPath),'OxygenDynamics:HistoricalDimensionsRequired', ...
        'This historical audit needs its explicitly selected, source-matched conversion report.');
    metadataHash=oxygenFileSHA256(MetadataPath);m=jsondecode(fileread(MetadataPath));
    assert(isfield(m,'Conversion')&&strcmp(m.Conversion.TiffSHA256,I.RawSHA256)&& ...
        numel(m.Conversion.MatlabInputShape)==3&&m.Conversion.MatlabInputShape(1)==I.NFrames, ...
        'OxygenDynamics:HistoricalMetadataMismatch','Conversion dimensions do not match this audit/source.');
    I.FrameSize=double(m.Conversion.MatlabInputShape(2:3))';
    historical=struct('Path',char(java.io.File(char(MetadataPath)).getCanonicalPath()), ...
        'SHA256',metadataHash,'RawSourceSHA256',I.RawSHA256,'FrameSize',I.FrameSize, ...
        'Role','source_matched_saved_dimensions_in_memory_only');
    assert(strcmp(metadataHash,oxygenFileSHA256(MetadataPath)),'OxygenDynamics:HistoricalMetadataMismatch','Metadata changed during loading.');
end
required={'RecordingID','EventType','SiteID','EventID','StartFrame','EndFrame', ...
    'DetectedStartFrame','DetectedEndFrame','FootprintPixels','BaselineWindowFrames', ...
    'RecomputedBaseline','RecomputedStatus','StoredAmplitude','RecomputedAmplitude', ...
    'MeasurementMatches','WrongDirection','SourceRawSHA256'};
assert(istable(A)&&all(ismember(required,A.Properties.VariableNames))&& ...
    iscell(T)&&numel(T)==height(A)&&isscalar(I)&& ...
    all(isfield(I,{'RawFile','RawSHA256','NFrames','FrameSize','AnalysisParams'})), ...
    'OxygenDynamics:InvalidEventReview','Audit fields or trace counts are incomplete.');
assert(all(ismember(string(A.EventType),["sink","surge"]))&& ...
    all(string(A.SourceRawSHA256)==string(I.RawSHA256)), ...
    'OxygenDynamics:InvalidEventReview','Only source-matched BOI sink/surge audit rows are supported.');
N=I.NFrames;sz=I.FrameSize;fs=I.AnalysisParams.fs;
assert(isscalar(N)&&isfinite(N)&&N>=1&&N==fix(N)&&numel(sz)==2&& ...
    all(isfinite(sz)&sz>=1&sz==fix(sz))&&isscalar(fs)&&isfinite(fs)&&fs>0, ...
    'OxygenDynamics:InvalidEventReview','Saved dimensions or sample rate are invalid.');
keys=string(A.RecordingID)+"|"+string(A.EventType)+"|"+string(A.SiteID)+"|"+string(A.EventID);
assert(numel(unique(keys))==height(A),'OxygenDynamics:InvalidEventReview','Duplicate saved event identities.');
for e=1:height(A)
    t=T{e};bounds=[A.StartFrame(e),A.EndFrame(e),A.DetectedStartFrame(e),A.DetectedEndFrame(e)];
    assert(isstruct(t)&&all(isfield(t,{'Raw','Footprint','CleanBaselineFrames','DetectedFrames'}))&& ...
        numel(t.Raw)==N&&all(isfinite(bounds)&bounds>=1&bounds<=N&bounds==fix(bounds))&& ...
        bounds(1)<=bounds(2)&&bounds(3)<=bounds(4), ...
        'OxygenDynamics:InvalidEventReview','Invalid saved trace or event bounds at row %d.',e);
    assert(validIndices(t.Footprint,prod(sz))&&~isempty(t.Footprint)&& ...
        numel(t.Footprint)==A.FootprintPixels(e)&&validIndices(t.CleanBaselineFrames,N)&& ...
        all(t.CleanBaselineFrames<A.StartFrame(e))&&validIndices(t.DetectedFrames,N)&& ...
        isequal(t.DetectedFrames(:),(bounds(3):bounds(4))'), ...
        'OxygenDynamics:InvalidEventReview','Invalid footprint or baseline/detection indices at row %d.',e);
end
snapshot=[];if isfield(I,'BOIAcquisitionMetadata'),snapshot=I.BOIAcquisitionMetadata;end
[Acquisition,QC]=resolveBOIAcquisitionMetadata(snapshot,N,fs,I.RawSHA256);
assert(~any(QC.IssueID=="R1-MODALITY"),'OxygenDynamics:EventReviewScope','Only BOI event review is in scope; this saved declaration identifies another modality.');
assert(strcmp(before,oxygenFileSHA256(AuditPath)), ...
    'OxygenDynamics:EventReviewChanged','Audit changed while being loaded. Reopen it.');
Review=struct('AuditPath',AuditPath,'AuditSHA256',before,'Audit',A,'Traces',{T}, ...
    'AnalysisInfo',I,'Acquisition',Acquisition,'QC',QC,'ScientificStatus','not_established');
if ~isempty(historical),Review.HistoricalMetadata=historical;end
receiptPath=fullfile(fileparts(AuditPath),'AuditCreationReceipt.json');
if isfile(receiptPath)
    receipt=jsondecode(fileread(receiptPath));
    assert(isfield(receipt,'Schema')&&strcmp(receipt.Schema,'boi-created-event-audit-1')&& ...
        strcmp(receipt.AuditSHA256,before)&&strcmp(receipt.SourceSHA256,I.RawSHA256)&& ...
        numel(receipt.MasterSHA256)==2,'OxygenDynamics:InvalidEventReview','Audit creation receipt differs from the selected audit/source.');
    Review.AuditCreationReceipt=receipt;
end
end
function yes=validIndices(values,limit)
yes=isnumeric(values)&&all(isfinite(values(:))&values(:)>=1&values(:)<=limit&values(:)==fix(values(:))) ...
    &&numel(unique(values))==numel(values);
end
