function Review=loadBOIWindowReview(Path)
%LOADBOIWINDOWREVIEW Read saved denominator evidence without live source lookup.
Path=char(java.io.File(char(Path)).getCanonicalPath());before=oxygenFileSHA256(Path);
names={'RecordingRegistry','RecordingWindowMetrics','BOIInputContracts','RecordingInputQC', ...
    'RecordingFrameExposure','WindowFrameIngredients','Table_OxygenSinkEvents_OutCombo'};
vars=whos('-file',Path);
assert(all(ismember(names,{vars.name})),'OxygenDynamics:WindowReviewMissingEvidence', ...
    'Select a BOI DataOutput.mat containing saved input contracts, window metrics, frame ingredients and sink event timing. Missing evidence is not zero.');
S=load(Path,names{:});R=S.RecordingRegistry;
extension={'SurgeRecordingWindowMetrics','SurgeWindowFrameIngredients'};
present=ismember(extension,{vars.name});
assert(~any(present)||all(present),'OxygenDynamics:WindowReviewMissingEvidence','Partial surge window extension; reopen a complete export.');
S.HasSurgeWindows=all(present);
if S.HasSurgeWindows
    assert(ismember('Table_OxygenSurgeEvents_OutCombo',{vars.name}),'OxygenDynamics:WindowReviewMissingEvidence','Surge event timing is required.');
    extra=load(Path,extension{:},'Table_OxygenSurgeEvents_OutCombo');
    for name=fieldnames(extra)',S.(name{1})=extra.(name{1});end
end
if ismember('StatsInfo',{vars.name}),extra=load(Path,'StatsInfo');S.StatsInfo=extra.StatsInfo;end
for signIndex=1:1+S.HasSurgeWindows
W=S.RecordingWindowMetrics;F=S.WindowFrameIngredients;E=S.Table_OxygenSinkEvents_OutCombo;
siteID='SinkID';schema="boi-window-exposure-1";
if signIndex==2
    W=S.SurgeRecordingWindowMetrics;F=S.SurgeWindowFrameIngredients;E=S.Table_OxygenSurgeEvents_OutCombo;
    siteID='SurgeID';schema="boi-surge-window-exposure-1";
    assert(istable(W)&&all(ismember({'EventType','CompositeStatus'},W.Properties.VariableNames))&& ...
        all(string(W.EventType)=="surge")&&all(string(W.CompositeStatus)=="not_defined_for_surge"), ...
        'OxygenDynamics:InvalidWindowReview','Surge sign and composite availability must be explicit.');
    A=S.RecordingWindowMetrics;
    assert(isequal(sortrows(W(:,{'RecordingID','WindowID','StartSec','EndSec'})),sortrows(A(:,{'RecordingID','WindowID','StartSec','EndSec'}))), ...
        'OxygenDynamics:WindowReviewIdentity','Both signs must reference the same requested windows.');
end
assert(istable(R)&&istable(W)&&istable(F)&&iscell(S.BOIInputContracts)&&numel(S.BOIInputContracts)==height(R)&& ...
    all(ismember({'RecordingID','RawSHA256','AnalysisStatus'},R.Properties.VariableNames))&& ...
    all(ismember({'RecordingID','WindowID','StartSec','EndSec','DurationSec','MeanOccupiedTissueFraction', ...
    'EventOnsets','ActiveEventSeconds','EventOnsetRate_per_mm2_per_min','MeanConcurrentEvents_per_mm2', ...
    'CoveredAreaTime_um2_sec','AnalyzedTissueTime_um2_sec','OccupancyStatus','OnsetPolicy','WindowAuditVersion'},W.Properties.VariableNames))&& ...
    all(ismember({'RecordingID','WindowID','Frame','ModeledStartSec','ModeledEndSec','WindowOverlapSec', ...
    'OccupiedArea_um2','AnalyzedArea_um2','CoveredAreaTime_um2_sec','AnalyzedTissueTime_um2_sec'},F.Properties.VariableNames)), ...
    'OxygenDynamics:InvalidWindowReview','Required identity or denominator fields are missing.');
assert(all(string(W.WindowAuditVersion)==schema),'OxygenDynamics:InvalidWindowReview','Unsupported saved window schema; do not infer its sign or exposure rules.');
assert(numel(unique(string(R.RecordingID)))==height(R)&& ...
    height(unique(W(:,{'RecordingID','WindowID'}),'rows'))==height(W)&& ...
    height(unique(F(:,{'RecordingID','WindowID','Frame'}),'rows'))==height(F)&& ...
    all(ismember(string(W.RecordingID),string(R.RecordingID))), ...
    'OxygenDynamics:WindowReviewIdentity','Recording/window/frame identities must be unique and resolve to the registry.');
assert(istable(E)&&all(ismember({'RecordingID',siteID,'EventID','StartSec','EndSec'},E.Properties.VariableNames))&& ...
    height(unique(E(:,{'RecordingID',siteID,'EventID'}),'rows'))==height(E), ...
    'OxygenDynamics:WindowReviewIdentity','Saved event timing/identity is missing or duplicated.');
Q=S.RecordingInputQC;X=S.RecordingFrameExposure;
assert(istable(Q)&&all(ismember({'RecordingID','IssueID','Message','Action'},Q.Properties.VariableNames))&& ...
    istable(X)&&all(ismember({'RecordingID','Frame','CameraExposureSec'},X.Properties.VariableNames))&& ...
    height(unique(X(:,{'RecordingID','Frame'}),'rows'))==height(X)&& ...
    all(ismember(string(E.RecordingID),string(R.RecordingID)))&& ...
    all(ismember(F(:,{'RecordingID','WindowID'}),W(:,{'RecordingID','WindowID'}),'rows')), ...
    'OxygenDynamics:WindowReviewIdentity','QC/exposure fields or ledger recording identities are incomplete.');
end % sign-specific ledgers
for k=1:height(R)
    c=S.BOIInputContracts{k};
    assert(isstruct(c)&&isscalar(c)&&all(isfield(c,{'Schema','RecordingID','RawSHA256','NFrames','SampleHz', ...
        'PixelSizeUm','FrameSize','SinkEligibleTissuePixels','SurgeEligibleTissuePixels','FrameTimingStatus','TissueValidityStatus'}))&& ...
        strcmp(c.Schema,'boi-recording-input-1')&&string(c.RecordingID)==string(R.RecordingID(k))&& ...
        string(c.RawSHA256)==string(R.RawSHA256(k)), ...
        'OxygenDynamics:WindowReviewIdentity','Contract source or recording identity differs from the registry.');
    assert(isscalar(c.NFrames)&&isfinite(c.NFrames)&&c.NFrames>=1&&c.NFrames==fix(c.NFrames)&& ...
        isscalar(c.SampleHz)&&isfinite(c.SampleHz)&&c.SampleHz>0&& ...
        isscalar(c.PixelSizeUm)&&isfinite(c.PixelSizeUm)&&c.PixelSizeUm>0&& ...
        numel(c.FrameSize)==2&&all(isfinite(c.FrameSize)&c.FrameSize>=1&c.FrameSize==fix(c.FrameSize)), ...
        'OxygenDynamics:InvalidWindowReview','Invalid saved frame grid or calibration.');
    for field={'SinkEligibleTissuePixels','SurgeEligibleTissuePixels'}
        p=c.(field{1});assert(isnumeric(p)&&all(isfinite(p(:))&p(:)>=1&p(:)<=prod(c.FrameSize)&p(:)==fix(p(:)))&& ...
            numel(unique(p))==numel(p),'OxygenDynamics:InvalidWindowReview','Invalid saved tissue pixels.');
    end
    if isfield(c,'AcquisitionSnapshot')&&isstruct(c.AcquisitionSnapshot)&&strcmp(c.AcquisitionSnapshot.State,'captured')
        d=jsondecode(c.AcquisitionSnapshot.RawJSON);
        assert(~isfield(d,'Modality')||strcmp(d.Modality,'BOI'),'OxygenDynamics:WindowReviewScope','Only BOI reviews are in scope.');
    end
end
assert(strcmp(before,oxygenFileSHA256(Path)),'OxygenDynamics:WindowReviewChanged','Saved results changed while loading. Reopen them.');
Review=S;Review.Path=Path;Review.SHA256=before;Review.ScientificStatus='not_established';
end
