function C=oxygenPipelineContract()
% Bump the relevant identity whenever a calculation or detection rule changes.
C=struct('Schema','3.0-dev','Detector','existing-v2-surge-physical-adjacent-4', ...
    'Measurement','event-footprint-surge-tracking-qc-5','Statistics','mouse-strict-tracking-qc-6', ...
    'Normalization','spatial-sd_then_temporal-sd');
end
