function C=oxygenPipelineContract()
% Bump the relevant identity whenever a calculation or detection rule changes.
C=struct('Schema','3.0-dev','Detector','existing-v2-sd-1', ...
    'Measurement','event-footprint-local-timing-2','Statistics','mouse-strict-3', ...
    'Normalization','spatial-sd_then_temporal-sd');
end
