function C=oxygenPipelineContract()
% Bump the relevant identity whenever a calculation or detection rule changes.
C=struct('Schema','3.0-dev','Detector','existing-v2-surge-shape-continuity-5', ...
    'Measurement','event-footprint-candidate-ledger-6','Statistics','mouse-strict-shape-gap-qc-7', ...
    'Normalization','spatial-sd_then_temporal-sd');
end
