function [CoreData,BLIData,BLIWorkbookData] = prepareStatsExportBundles(IsBLI,CoreInputs,BLIInputs,BLIWorkbookInputs)
%PREPARESTATSEXPORTBUNDLES Bundle common and BLI-only stats export data.

if nargin<3 || isempty(BLIInputs)
    BLIInputs = struct();
end
if nargin<4 || isempty(BLIWorkbookInputs)
    BLIWorkbookInputs = struct();
end

CoreData = createStatsCoreData(CoreInputs.TableOxygenSurges,CoreInputs.TableOxygenSurgeEvents, ...
    CoreInputs.TableOxygenSinks,CoreInputs.TableOxygenSinkEvents, ...
    CoreInputs.FiltersOxySinksMetrics,CoreInputs.FiltersOxySurgesMetrics, ...
    CoreInputs.FiltersROIsAndEvents,CoreInputs.ExportTraces,CoreInputs.NumOngoingOxysinks, ...
    CoreInputs.NumOngoingOxysinksPerMm2,CoreInputs.SinkCountAreaNormalization, ...
    CoreInputs.TotalSinkAreaNorm,CoreInputs.NumOngoingOxysurges,CoreInputs.TotalSurgeArea, ...
    CoreInputs.SinksRaster,CoreInputs.SurgesRaster,CoreInputs.StatsInfo);

BLIData = struct();
BLIWorkbookData = struct();
if IsBLI
    BLIData = createStatsBLIData(BLIInputs.BehaviourDataCombo,BLIInputs.BehaviourLogicals, ...
        BLIInputs.ROIsTraces,BLIInputs.ExportTraceCorrs,BLIInputs.TraceCorrs);
    BLIWorkbookData = createStatsBLIWorkbookData(BLIWorkbookInputs.AlignedSinkTraces, ...
        BLIWorkbookInputs.TraceCorrs,BLIWorkbookInputs.LPawBinnedTraces, ...
        BLIWorkbookInputs.RPawBinnedTraces,BLIWorkbookInputs.PupilBinnedTraces, ...
        BLIWorkbookInputs.PooledTraces,BLIWorkbookInputs.BehaviourLogicals, ...
        BLIWorkbookInputs.SampleFs,BLIWorkbookInputs.PuffsFs,BLIWorkbookInputs.FiguresOutputFolder);
end

end
