function BehaviourAnalysis = prepareStatsBehaviourAnalysisData(IsBLI,BehaviourInputs,TimeSeriesInputs)
%PREPARESTATSBEHAVIOURANALYSISDATA Prepare behaviour windows, logicals, and bins.

BehaviourAnalysis = struct();
BehaviourAnalysis.TimeWindows = selectStatsBehaviourTimeWindows( ...
    BehaviourInputs.DefaultTimeWindows,BehaviourInputs.Interactive, ...
    BehaviourInputs.BehaviourDataCombo,BehaviourInputs.ManualEvents);
BehaviourAnalysis.BehaviourLogicals = createBehaviourLogicalTraces( ...
    BehaviourInputs.BehaviourDataCombo,BehaviourInputs.BehFs);
[BehaviourAnalysis.BinsLPaw,BehaviourAnalysis.BinsRPaw,BehaviourAnalysis.BinsPupil] = ...
    createStatsBehaviourPercentileBins(BehaviourInputs.BehaviourDataCombo, ...
    BehaviourInputs.ROIsTraces,TimeSeriesInputs.NumOngoingOxysinks, ...
    TimeSeriesInputs.NumOngoingOxysinksPerMm2,TimeSeriesInputs.TotalSinkAreaNorm, ...
    TimeSeriesInputs.TotalSinkAreaUm, ...
    TimeSeriesInputs.NumOngoingOxysurges,TimeSeriesInputs.TotalSurgeArea,IsBLI);

end
