function [PooledTraces,Titles1,Titles2] = prepareStatsPooledTraceExports(IsBLI,PooledInputs,TimeSeriesInputs)
%PREPARESTATSPOOLEDTRACEEXPORTS Prepare trace titles and BLI pooled puff traces.

Titles1 = {'DrugID';'Condition';'Stimulation';'ROI Mean';'ROI CovCoef';'ROI Entropy'; ...
    'OxySinks HowMany';'OxySinksPer1mm2';'OxySinksArea_Norm'; ...
    'OxySurgesHowMany';'OxySurgesArea';'ROIdiff Mean';'ROIdiff CovCoef'; ...
    'ROIdiff Entropy';'OxySinksArea_um'};
Titles2 = {'DrugID';'Condition';'Stimulation';'ROI Mean vs CovCoef'; ...
    'ROI Mean vs Entropy';'CovCoef vs Entropy';'ROIdiff Mean vs diffCovCoef'; ...
    'ROIdiff Mean vs diffEntropy';'diffCovCoef vs diffEntropy'; ...
    'OxySinksArea vs CovCoef';'OxySinksArea vs Entropy'; ...
    'OxySurgesArea vs CovCoef';'OxySurgesArea vs Entropy'};

PooledTraces = {};
if IsBLI
    PooledTraces = createStatsPooledPuffTraces(PooledInputs.FiltersROIsAndEvents, ...
        PooledInputs.BehaviourDataCombo,PooledInputs.PuffsToUse,PooledInputs.SampleFs, ...
        PooledInputs.Mice,PooledInputs.ROIsTraces,TimeSeriesInputs.NumOngoingOxysinks, ...
        TimeSeriesInputs.TotalSinkAreaNorm,TimeSeriesInputs.TotalSinkAreaUm, ...
        TimeSeriesInputs.NumOngoingOxysinksPerMm2,TimeSeriesInputs.NumOngoingOxysurges, ...
        TimeSeriesInputs.TotalSurgeArea,PooledInputs.PuffsFs);
    PooledTraces = [Titles1,PooledTraces];
end

end
