function [Mask,Declaration] = resolveBOITissueSupport(Snapshot,FrameSize,RawSHA256)
%RESOLVEBOITISSUESUPPORT Validate a saved, source-bound static support decision.
% File presence records a declaration, not independent anatomical validation.
Mask=[];Declaration=struct();
if isempty(Snapshot) || strcmp(Snapshot.State,'not_supplied'),return;end
assert(strcmp(Snapshot.State,'captured'),'OxygenDynamics:InvalidTissueDeclaration','Unknown tissue snapshot state.');
Declaration=jsondecode(Snapshot.RawJSON);
fields={'Schema','Modality','RawSHA256','FrameSize','IndexConvention','MaskPixels', ...
    'ReviewStatus','DecisionID','Actor','Reason','Evidence','AlignmentEvidence','RecordedUTC'};
assert(isstruct(Declaration)&&isscalar(Declaration)&& ...
    isequal(sort(fieldnames(Declaration)),sort(fields(:))), ...
    'OxygenDynamics:InvalidTissueDeclaration','Tissue declaration fields are missing or unrecognized.');
for f=setdiff(fields,{'FrameSize','MaskPixels'})
    v=Declaration.(f{1});
    assert(ischar(v)&&isrow(v)&&~isempty(strtrim(v)), ...
        'OxygenDynamics:InvalidTissueDeclaration','%s must contain explicit text.',f{1});
end
assert(strcmp(Declaration.Schema,'boi-static-tissue-support-1')&&strcmp(Declaration.Modality,'BOI')&& ...
    strcmp(Declaration.IndexConvention,'MATLAB_one_based_column_major_row_column')&& ...
    strcmp(Declaration.ReviewStatus,'reviewed_for_static_support'), ...
    'OxygenDynamics:InvalidTissueDeclaration','Unsupported schema, modality, coordinates or review status.');
assert(strcmp(Declaration.RawSHA256,RawSHA256), ...
    'OxygenDynamics:TissueSourceMismatch','Tissue review belongs to different source pixels.');
assert(isnumeric(Declaration.FrameSize)&&isequal(Declaration.FrameSize(:)',double(FrameSize(:)')), ...
    'OxygenDynamics:TissueShapeMismatch','Tissue dimensions must exactly match the decoded source; no resizing or registration is inferred.');
v=Declaration.MaskPixels;
assert(isnumeric(v)&&isvector(v)&&~isempty(v)&&all(isfinite(v))&&all(v==fix(v))&& ...
    all(v>=1)&&all(v<=prod(FrameSize))&&numel(unique(v))==numel(v), ...
    'OxygenDynamics:InvalidTissueSupport','Reviewed support needs nonempty, unique, one-based native image indices.');
assert(~isempty(regexp(Declaration.RecordedUTC,'^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$','once')), ...
    'OxygenDynamics:InvalidTissueDeclaration','RecordedUTC must be an explicit UTC timestamp (YYYY-MM-DDTHH:MM:SSZ).');
Mask=false(FrameSize);Mask(v)=true;
end
