function [Resolved,QC] = resolveBOIAcquisitionMetadata(Snapshot,NFrames,SampleHz,RawSHA256)
%RESOLVEBOIACQUISITIONMETADATA Preserve declarations; never invent acquisition facts.
% Snapshot.RawJSON is the exact optional BOIInputMetadata.json read at master.
% Compatibility checks use 1 microsecond numeric tolerance, not biological QC.
Resolved=struct('Schema','boi-recording-input-1','MetadataState','not_recorded_at_master', ...
    'MetadataSHA256','','SourceID','unknown','SelectedSeries','unknown','SourceAxes','unknown', ...
    'FrameTimeReference','unknown','TimingEvidence','unknown','SamplingRateEvidence','unknown', ...
    'PixelSizeEvidence','unknown','ExposureEvidence','unknown','IntensityHistory','unknown', ...
    'MotionCorrectionHistory','unknown','Substrate','unknown','EvidenceOrigin','unknown', ...
    'RecordedUTC','unknown','TimeSinceApplicationSec',NaN, ...
    'DeclaredFrameTimesSec',nan(NFrames,1),'CameraExposureSec',nan(NFrames,1), ...
    'SourceClockTimesSec',nan(NFrames,1),'SourceClockReference','unknown','SourceClockEvidence','unknown', ...
    'SourceClockStatus','unvalidated','UniformSamplingConfirmed',false, ...
    'SourceReviewIssues',struct([]),'AcquisitionExtensionsVersion','source-clock-and-source-review-1', ...
    'DeclaredFrameValid',nan(NFrames,1),'FrameValidityStatus','all_frames_assumed_observable', ...
    'FrameTimingStatus','uniform_assumed_from_sampling_rate','ExposureStatus','unknown', ...
    'InputCompatible',true,'NumericalTimingToleranceSec',1e-6);
QC=table('Size',[0 5],'VariableTypes',repmat({'string'},1,5), ...
    'VariableNames',{'IssueID','Disposition','AffectedMeasurements','Message','Action'});
assert(isscalar(NFrames)&&NFrames>=1&&NFrames==fix(NFrames)&&isscalar(SampleHz)&&isfinite(SampleHz)&&SampleHz>0, ...
    'OxygenDynamics:InvalidInputContract','Positive frame count and sample rate are required.');
if ~isempty(Snapshot)
    assert(isstruct(Snapshot)&&isscalar(Snapshot)&&all(isfield(Snapshot,{'State','RawJSON','SHA256'})), ...
        'OxygenDynamics:InvalidInputMetadata','Invalid saved acquisition metadata snapshot.');
    Resolved.MetadataState=Snapshot.State;Resolved.MetadataSHA256=Snapshot.SHA256;
    if strcmp(Snapshot.State,'captured')
        D=jsondecode(Snapshot.RawJSON);
        allowed={'Schema','RawSHA256','Modality','SourceID','SelectedSeries','SourceAxes', ...
            'FrameTimesSec','FrameTimeReference','TimingEvidence','SamplingRateEvidence','PixelSizeEvidence', ...
            'CameraExposureSec','ExposureEvidence','IntensityHistory','MotionCorrectionHistory','Substrate', ...
            'TimeSinceApplicationSec','FrameValid','EvidenceOrigin','RecordedUTC', ...
            'SourceClockTimesSec','SourceClockReference','SourceClockEvidence','SourceClockStatus', ...
            'UniformSamplingConfirmed','ReviewIssues'};
        assert(isstruct(D)&&isscalar(D)&&all(ismember(fieldnames(D),allowed)), ...
            'OxygenDynamics:InvalidInputMetadata','Unknown metadata field or non-object JSON; check the input contract guide.');
        assert(isfield(D,'Schema')&&strcmp(D.Schema,'boi-acquisition-metadata-1')&& ...
            isfield(D,'RawSHA256')&&strcmp(D.RawSHA256,RawSHA256), ...
            'OxygenDynamics:InputMetadataSourceMismatch','Metadata schema or preserved TIFF checksum does not match.');
        textFields=setdiff(allowed,{'Schema','RawSHA256','Modality','FrameTimesSec','CameraExposureSec', ...
            'TimeSinceApplicationSec','FrameValid','SourceClockTimesSec','UniformSamplingConfirmed','ReviewIssues'});
        for k=1:numel(textFields)
            name=textFields{k};
            if isfield(D,name)
                assert((ischar(D.(name))&&isrow(D.(name)))||(isstring(D.(name))&&isscalar(D.(name))), ...
                    'OxygenDynamics:InvalidInputMetadata','Metadata descriptions must be scalar text.');
                assert(strlength(strtrim(string(D.(name))))>0,'OxygenDynamics:InvalidInputMetadata','Use unknown instead of empty metadata text.');
                Resolved.(name)=char(string(D.(name)));
            end
        end
        if isfield(D,'Modality') && ~strcmp(D.Modality,'BOI')
            Resolved.InputCompatible=false;
            QC(end+1,:)={"R1-MODALITY","hold_recording","BOI biological analysis", ...
                "The declared modality is outside this BOI-only input contract.","Use a separately justified support/control workflow; do not pool as BOI."};
        end
        assert(any(strcmp(Resolved.SourceClockStatus,{'unvalidated','known_unreliable'})), ...
            'OxygenDynamics:InvalidSourceClock','SourceClockStatus must be unvalidated or known_unreliable.');
        if isfield(D,'UniformSamplingConfirmed')
            v=D.UniformSamplingConfirmed;
            assert((islogical(v)||isnumeric(v))&&isscalar(v)&&ismember(v,[0 1]), ...
                'OxygenDynamics:InvalidSamplingEvidence','UniformSamplingConfirmed must be a Boolean.');
            Resolved.UniformSamplingConfirmed=logical(v);
            if Resolved.UniformSamplingConfirmed
                assert(~strcmp(Resolved.SamplingRateEvidence,'unknown'), ...
                    'OxygenDynamics:InvalidSamplingEvidence','Confirmed sampling requires acquisition evidence for the supplied sample rate.');
                Resolved.FrameTimingStatus='uniform_confirmed_from_acquisition_evidence';
            end
        end
        if isfield(D,'SourceClockTimesSec') && ~isempty(D.SourceClockTimesSec)
            v=D.SourceClockTimesSec;
            assert(isnumeric(v)&&isvector(v)&&numel(v)==NFrames&&all(isfinite(v))&& ...
                ~strcmp(Resolved.SourceClockReference,'unknown')&&~strcmp(Resolved.SourceClockEvidence,'unknown'), ...
                'OxygenDynamics:InvalidSourceClock','Source-clock observations require one finite value per frame, reference and evidence.');
            % Unvalidated/unreliable clocks can repeat or move backwards.
            % Preserve them in image order without treating them as frame timing.
            Resolved.SourceClockTimesSec=v(:);
            QC(end+1,:)={"R1-SOURCE-CLOCK","review","Temporal interpretation and image/acquisition alignment", ...
                "Source-clock metadata ("+string(Resolved.SourceClockStatus)+") are retained only as provenance and do not drive the analysis clock.", ...
                "Use the recorded acquisition evidence for sampling; do not promote these observations to image timestamps."};
        end
        if isfield(D,'ReviewIssues') && ~isempty(D.ReviewIssues)
            issues=D.ReviewIssues;
            required={'IssueID','Disposition','AffectedMeasurements','Message','Action','Evidence'};
            assert(isstruct(issues)&&isvector(issues)&&isequal(sort(fieldnames(issues)),sort(required(:))), ...
                'OxygenDynamics:InvalidSourceReview','Each source issue requires IssueID, Disposition, AffectedMeasurements, Message, Action and Evidence.');
            ids=strings(numel(issues),1);
            for j=1:numel(issues)
                for k=1:numel(required)
                    v=issues(j).(required{k});
                    assert(((ischar(v)&&isrow(v))||(isstring(v)&&isscalar(v)))&& ...
                        strlength(strtrim(string(v)))>0,'OxygenDynamics:InvalidSourceReview','Source issue fields must be nonempty scalar text.');
                end
                ids(j)=string(issues(j).IssueID);
                assert(startsWith(ids(j),"SOURCE-")&&strlength(ids(j))>7&& ...
                    any(string(issues(j).Disposition)==["review","hold_recording"]), ...
                    'OxygenDynamics:InvalidSourceReview','Use a SOURCE- issue ID and disposition review or hold_recording.');
                QC(end+1,:)={ids(j),string(issues(j).Disposition),string(issues(j).AffectedMeasurements), ...
                    string(issues(j).Message)+" Evidence: "+string(issues(j).Evidence),string(issues(j).Action)};
                if strcmp(issues(j).Disposition,'hold_recording'),Resolved.InputCompatible=false;end
            end
            assert(numel(unique(ids))==numel(ids),'OxygenDynamics:InvalidSourceReview','Source issue IDs must be unique.');
            Resolved.SourceReviewIssues=issues;
        end
        if isfield(D,'FrameTimesSec') && ~isempty(D.FrameTimesSec)
            v=D.FrameTimesSec;
            assert(isnumeric(v)&&isvector(v)&&numel(v)==NFrames&&all(isfinite(v))&&all(diff(v(:))>0), ...
                'OxygenDynamics:InvalidFrameTiming','Provide one finite strictly increasing timestamp per image frame.');
            assert(~strcmp(Resolved.FrameTimeReference,'unknown')&&~strcmp(Resolved.TimingEvidence,'unknown'), ...
                'OxygenDynamics:InvalidFrameTiming','Declared timestamps need their clock/reference meaning and evidence.');
            Resolved.DeclaredFrameTimesSec=v(:);
            expected=(0:NFrames-1)'/SampleHz;
            if any(abs(v(:)-v(1)-expected)>Resolved.NumericalTimingToleranceSec)
                Resolved.FrameTimingStatus='declared_nonuniform_or_rate_mismatch';Resolved.InputCompatible=false;
                QC(end+1,:)={"R1-TIMING","hold_recording","Current uniform-time detection, duration, baseline and exposure calculations", ...
                    "Declared image timestamps disagree with the uniform analysis clock; no timestamps were rounded or replaced.", ...
                    "Resolve image correspondence/rate or validate an explicit irregular-time method before running this pipeline."};
            else
                Resolved.FrameTimingStatus='declared_uniform_compatible';
            end
        end
        if isfield(D,'CameraExposureSec') && ~isempty(D.CameraExposureSec)
            v=D.CameraExposureSec;
            assert(isnumeric(v)&&isvector(v)&&(isscalar(v)||numel(v)==NFrames)&&all(isfinite(v))&&all(v>0), ...
                'OxygenDynamics:InvalidCameraExposure','Exposure must be positive seconds: one scalar or one value per frame.');
            if isscalar(v),v=repmat(v,NFrames,1);end
            Resolved.CameraExposureSec=v(:);Resolved.ExposureStatus='declared_not_substituted_for_frame_interval';
        end
        if isfield(D,'TimeSinceApplicationSec') && ~isempty(D.TimeSinceApplicationSec)
            v=D.TimeSinceApplicationSec;
            assert(isnumeric(v)&&isscalar(v)&&isfinite(v)&&v>=0,'OxygenDynamics:InvalidInputMetadata','Time since application must be nonnegative seconds.');
            Resolved.TimeSinceApplicationSec=v;
        end
        if isfield(D,'FrameValid') && ~isempty(D.FrameValid)
            v=D.FrameValid;
            assert((islogical(v)||isnumeric(v))&&isvector(v)&&numel(v)==NFrames&&all(ismember(v,[0 1])), ...
                'OxygenDynamics:InvalidFrameValidity','FrameValid must contain one Boolean per image frame.');
            Resolved.DeclaredFrameValid=double(v(:));Resolved.FrameValidityStatus='declared_all_frames_observable';
            if ~all(v)
                Resolved.FrameValidityStatus='declared_exclusions_not_supported';Resolved.InputCompatible=false;
                QC(end+1,:)={"R1-FRAME-EXCLUSION","hold_recording","Current temporal preprocessing, event identity, baselines and exposure", ...
                    "Excluded frames are declared, but this detector assumes a contiguous uniformly observed movie.", ...
                    "Assess missing-frame handling before analysis; do not delete frames or renumber the time axis."};
            end
        end
    else
        assert(strcmp(Snapshot.State,'not_supplied'),'OxygenDynamics:InvalidInputMetadata','Unknown acquisition snapshot state.');
    end
end
if strcmp(Resolved.FrameTimingStatus,'uniform_assumed_from_sampling_rate')
    QC(end+1,:)={"R1-TIMING-UNKNOWN","review","Duration, event rate, baseline windows and tissue-time", ...
        "Frame intervals are modeled from sampling rate; measured image timestamps were not recorded.", ...
        "Verify image-to-acquisition correspondence; retain descriptive values as conditional on uniform timing."};
end
if strcmp(Resolved.ExposureStatus,'unknown')
    QC(end+1,:)={"R1-EXPOSURE-UNKNOWN","review","Acquisition comparability and temporal interpretation", ...
        "Camera exposure duration is unknown; it has not been set equal to frame spacing.","Recover acquisition evidence where available; retain unknown otherwise."};
end
if strcmp(Resolved.IntensityHistory,'unknown')
    QC(end+1,:)={"R1-INTENSITY-UNKNOWN","review","Relative optical amplitude and acquisition comparisons", ...
        "Intensity preparation before the preserved TIFF is unknown; preserved input does not imply camera-raw data.", ...
        "Recover processing evidence or restrict quantitative comparisons; do not rescale to match expected biology."};
end
if strcmp(Resolved.FrameValidityStatus,'all_frames_assumed_observable')
    QC(end+1,:)={"R1-FRAME-VALIDITY","review","All temporal measurements and recording exposure", ...
        "Every image interval is assumed observable; no frame-level motion or missing-support review is recorded.", ...
        "Review acquisition and motion coverage before final measurement eligibility."};
end
end
