function saveOxygenTiffoutStacks(OutputFolders,DatafileID,IM_Notrend,IM_Notrend_dFoF_global, ...
    IM_Raw_dFoF_global,IM_Notrend_dFoF_frame,IM_Raw_dFoF_frame,IM_Zframetime_smoothed)
%SAVEOXYGENTIFFOUTSTACKS Save processed oxygen TIFF-output stacks.

SaveOptions = struct();
SaveOptions.overwrite = true;

saveastiff(scaleStackToUint16(IM_Notrend), ...
    fullfile(OutputFolders.ImagesProcessedPath,['IM_Notrend',DatafileID,'.tif']),SaveOptions);
saveastiff(scaleStackToUint16(IM_Notrend_dFoF_global), ...
    fullfile(OutputFolders.ImagesProcessedPath,['IM_Notrend_dFoF_global',DatafileID,'.tif']),SaveOptions);
saveastiff(scaleStackToUint16(IM_Raw_dFoF_global), ...
    fullfile(OutputFolders.ImagesProcessedPath,['IM_Raw_dFoF_global',DatafileID,'.tif']),SaveOptions);
saveastiff(scaleStackToUint16(IM_Notrend_dFoF_frame), ...
    fullfile(OutputFolders.ImagesProcessedPath,['IM_Notrend_dFoF_frame',DatafileID,'.tif']),SaveOptions);
saveastiff(scaleStackToUint16(IM_Raw_dFoF_frame), ...
    fullfile(OutputFolders.ImagesProcessedPath,['IM_Raw_dFoF_frame',DatafileID,'.tif']),SaveOptions);
saveastiff(scaleStackToUint16(IM_Zframetime_smoothed), ...
    fullfile(OutputFolders.ImagesProcessedPath,['IM_Conv',DatafileID,'.tif']),SaveOptions);

end
