function SinkTable = selectStatsSinkSummaryColumns(SinkTable)
%SELECTSTATSSINKSUMMARYCOLUMNS Keep the stats sink summary export schema.

SinkTable = SinkTable(:,{'RecDuration','RecAreaSize', ...
    'MeanCentroid_x','MeanCentroid_y','MeanOxySinkArea_um','MeanOxySinkFilledArea_um', ...
    'MeanOxySinkDiameter_um','MeanOxySinkPerimeter_um','MeanCircularity', ...
    'MeanOxySinkBoundingBox','NumOxySinkEvents','Start','Duration', ...
    'NormOxySinkAmp','Size_modulation','OxySink_Pxls_all'});
end
