function SurgeTable = selectStatsSurgeSummaryColumns(SurgeTable)
%SELECTSTATSSURGESUMMARYCOLUMNS Keep the stats surge summary export schema.

Extras = intersect({'EligibleTissuePixels','FramePixels','FrameSize','NFrames','SampleF','AnalysisSchemaVersion','SiteID'},SurgeTable.Properties.VariableNames,'stable');
ExtraTable = SurgeTable(:,Extras);
SurgeTable = SurgeTable(:,{'RecDuration_Surge','RecAreaSize_Surge', ...
    'MeanCentroid_Surge_x','MeanCentroid_Surge_y','MeanOxySurgeArea_um','MeanOxySurgeFilledArea_um', ...
    'MeanOxySurgeDiameter_um','MeanOxySurgePerimeter_um','MeanCircularity_Surge', ...
    'MeanOxySurgeBoundingBox','NumOxySurgeEvents','Start_Surge','Duration_Surge', ...
    'NormOxySurgeAmp','Size_Surge_modulation','OxySurge_Pxls_all'});
SurgeTable = [SurgeTable,ExtraTable];
end
