function SinkTable = selectStatsSinkSummaryColumns(SinkTable)
%SELECTSTATSSINKSUMMARYCOLUMNS Keep the stats sink summary export schema.

Extras = intersect({'EligibleTissuePixels','FramePixels','FrameSize','NFrames','SampleF','AnalysisSchemaVersion','SiteID'},SinkTable.Properties.VariableNames,'stable');
ExtraTable = SinkTable(:,Extras);
SinkTable = SinkTable(:,{'RecDuration','RecAreaSize', ...
    'MeanCentroid_x','MeanCentroid_y','MeanOxySinkArea_um','MeanOxySinkFilledArea_um', ...
    'MeanOxySinkDiameter_um','MeanOxySinkPerimeter_um','MeanCircularity', ...
    'MeanOxySinkBoundingBox','NumOxySinkEvents','Start','Duration', ...
    'NormOxySinkAmp','Size_modulation','OxySink_Pxls_all'});
SinkTable = [SinkTable,ExtraTable];
end
