function validateBOIPocketEvidence(E)
%VALIDATEBOIPOCKETEVIDENCE Integrity/identity gates only; no arithmetic replay.
id='OxygenDynamics:InvalidPocketEvidence';
assert(isstruct(E)&&isscalar(E)&&isfield(E,'Schema')&&strcmp(E.Schema,'boi-reviewed-pocket-evidence-1'), ...
    'OxygenDynamics:UnsupportedPocketSchema','Unsupported reviewed pocket evidence version.');
required={'Definition','AuditSHA256','RawSourceSHA256','AuditRow','OriginalAutomatic','Judgment','JudgmentSHA256', ...
    'FixedFootprint','FixedFootprintSHA256','EventFrames','ReferenceFrames','Correction','Ingredients','IngredientsSHA256','Measures'};
assert(all(isfield(E,required)),id,'Incomplete pocket evidence.');D=getBOIReviewedPocketDefinition;
assert(isequaln(E.Definition,D),id,'Definition differs from the version-bound contract.');
J=E.Judgment;
assert(strcmp(E.JudgmentSHA256,boiPocketDigest(J)),'OxygenDynamics:PocketRevisionMismatch','Judgment revision changed; save a new result.');
assert(isequal(E.EventFrames(:),(J.OnsetFrame:J.ObservedEndFrame)')&&isequal(E.ReferenceFrames(:),J.ReferenceFrames(:))&& ...
    strcmp(E.AuditSHA256,J.AuditSHA256)&&strcmp(E.RawSourceSHA256,J.RawSourceSHA256)&&E.AuditRow==J.AuditRow,id,'Event/reference/source binding differs.');
assert(isequaln(J.BoundaryRevision,struct('Revision',J.Revision,'OnsetFrame',J.OnsetFrame,'ObservedEndFrame',J.ObservedEndFrame,'EndpointStatus',J.EndpointStatus))&& ...
    isequaln(J.ReferenceRevision,struct('Revision',J.Revision,'Frames',J.ReferenceFrames(:),'Suitability',J.ReferenceSuitability)), ...
    'OxygenDynamics:PocketRevisionMismatch','Boundary/reference revision differs.');
fp=boiPocketDigest(double(E.FixedFootprint(:)));
assert(strcmp(fp,E.FixedFootprintSHA256)&&strcmp(fp,J.FixedFootprintSHA256)&&strcmp(fp,E.Ingredients.FootprintSHA256)&& ...
    strcmp(fp,E.Correction.FixedFootprintSHA256),'OxygenDynamics:PocketIdentityMismatch','Fixed footprint changed.');
assert(strcmp(E.IngredientsSHA256,boiPocketDigest(E.Ingredients))&& ...
    strcmp(E.Correction.SavedCorrectedSHA256,boiPocketDigest(E.Ingredients.Corrected))&& ...
    strcmp(E.Ingredients.CorrectionSHA256,E.Correction.SavedCorrectedSHA256)&& ...
    strcmp(E.Correction.AuditSHA256,E.AuditSHA256)&&strcmp(E.Correction.RawSourceSHA256,E.RawSourceSHA256), ...
    'OxygenDynamics:PocketIdentityMismatch','Correction/input identity differs.');
assert(~E.AutomaticMeasurementsChanged&&~E.DetectorRelabelled,id,'Reviewed artifact cannot replace automatic output.');
assert(strcmp(char(E.OriginalAutomatic.EventType),E.FootprintOrigin)&& ...
    isequaln(E.OriginalAutomatic.RecordingID,J.SavedEvent.RecordingID)&& ...
    E.OriginalAutomatic.SiteID==J.SavedEvent.SiteID&&E.OriginalAutomatic.EventID==J.SavedEvent.EventID,id,'Original event provenance differs.');
if strcmp(J.ReferenceSuitability,'provisional_local_state')&&isfinite(E.Measures.CorrectedSignedTroughPercent)
    assert(strcmp(E.Measures.PrimaryStatus,'conditional_exploratory'),id,'Provisional reference lost its conditional status.');
end
if ~strcmp(J.EndpointStatus,'recovery_observed'),assert(isnan(E.ConfirmedPocketDurationSec),id,'Unresolved recovery cannot become a confirmed duration.');end
end
