function Mask=validateBOISavedDetectionSupport(I)
% Bind restricted processing, eligibility and smoothing evidence to its source.
fields={'BOITissueSupport','FrameSize','RawSHA256','DetectionSupportAudit', ...
    'SinkEligibleTissuePixels','SurgeEligibleTissuePixels','AnalysisParams','TissueSupportAudit'};
assert(all(isfield(I,fields)),'OxygenDynamics:ReanalysisRequired','Restricted support evidence is missing.');
Mask=resolveBOITissueSupport(I.BOITissueSupport,I.FrameSize,I.RawSHA256);
validateBOIDetectionMask(Mask,I.FrameSize);
A=I.DetectionSupportAudit;
expected={'Schema','Profile','MaskPixels','NeighborWeightMap','KernelWidthPixels', ...
    'SpatialNormalization','TemporalNormalization','SpatialSmoothing','CandidatePolicy', ...
    'ExteriorFill','SinkImageBorderPixels','FinalContainment', ...
    'SpatialBinTracePolicy','SpatialBinOrigins','SpatialBinSizePixels'};
assert(all(isfield(A,expected)),'OxygenDynamics:ReanalysisRequired','Restricted processing audit is incomplete.');
width=2*I.AnalysisParams.smooth+1;
weight=conv2(double(Mask),ones(width)/width^2,'same');
assert(strcmp(A.Schema,'boi-detection-support-1')&&strcmp(A.Profile,'craniotomy-roi-1')&& ...
    isequal(A.MaskPixels,find(Mask))&&A.KernelWidthPixels==width&& ...
    isequal(A.NeighborWeightMap,weight)&&strcmp(A.FinalContainment,'exact_native_support_checked_both_signs'), ...
    'OxygenDynamics:ReanalysisRequired','Restricted support or smoothing evidence differs.');
policies=struct('SpatialNormalization','ROI_mean_sample_SD', ...
    'TemporalNormalization','per_included_pixel_mean_sample_SD', ...
    'SpatialSmoothing','included_neighbor_weight_normalized_same_kernel', ...
    'CandidatePolicy','sign_eligible_percentile_intersection_before_components', ...
    'ExteriorFill','zero_computational_sentinel_not_observation', ...
    'SpatialBinTracePolicy','included_pixels_only');
for field=fieldnames(policies)'
    assert(isequal(A.(field{1}),policies.(field{1})), ...
        'OxygenDynamics:ReanalysisRequired','Saved restricted processing policy differs: %s.',field{1});
end
assert(isfield(I.TissueSupportAudit,'NormalizationSupport')&& ...
    strcmp(I.TissueSupportAudit.NormalizationSupport,'craniotomy-roi-1'), ...
    'OxygenDynamics:ReanalysisRequired','Tissue and normalization support records differ.');
border=I.AnalysisParams.Pixel_frame;
assert(A.SinkImageBorderPixels==border,'OxygenDynamics:ReanalysisRequired','Sink border policy differs.');
sink=false(size(Mask));sink(border+1:end-border,border+1:end-border)=Mask(border+1:end-border,border+1:end-border);
assert(isequal(I.SurgeEligibleTissuePixels,find(Mask))&&isequal(I.SinkEligibleTissuePixels,find(sink)), ...
    'OxygenDynamics:ReanalysisRequired','Saved sign support differs from the source-bound ROI.');
end
