function Attachment=validateBOINativeMaskSource(Review,Index)
%VALIDATEBOINATIVEMASKSOURCE Withhold stale or unavailable attached support.
assert(isfield(Review,'NativeMasks')&&numel(Review.NativeMasks)>=Index&&~isempty(Review.NativeMasks{Index}), ...
    'OxygenDynamics:NativeMaskMissing','Attach a matching master to inspect native masks; missing support is not an empty mask.');
Attachment=Review.NativeMasks{Index};A=Review.Audit(Index,:);
assert(strcmp(Attachment.AuditSHA256,Review.AuditSHA256)&& ...
    string(Attachment.RecordingID)==A.RecordingID&&string(Attachment.EventType)==A.EventType&& ...
    Attachment.SiteID==A.SiteID&&Attachment.EventID==A.EventID, ...
    'OxygenDynamics:NativeMaskIdentity','Attached masks do not match the selected audit event.');
assert(isfile(Attachment.MasterPath),'OxygenDynamics:NativeMaskMissing','Attached master is unavailable. Reconnect it before native-mask display or export.');
assert(strcmp(oxygenFileSHA256(Attachment.MasterPath),Attachment.MasterSHA256), ...
    'OxygenDynamics:NativeMaskChanged','Attached master changed; reopen or reattach before native-mask display or export.');
end
