function writeStatsMetricDefinitionsSheet(OutputXlsx)
%WRITESTATSMETRICDEFINITIONSSHEET Write explicit metric definitions.

MetricName = { ...
    'MeanOxySinkEvent_NormAmp'; ...
    'NormOxySinkAmpPercent'; ...
    'BurdenAmplitudePercent'; ...
    'BurdenArea_um2'; ...
    'BurdenDuration_sec'; ...
    'PerEventBurdenContribution'; ...
    'PerEventBurdenContribution_per_mm2'; ...
    'BurdenRecordingDuration_sec'; ...
    'HypoxicBurden'; ...
    'HypoxicBurden_per_mm2'; ...
    'HypoxicBurden_per_sec'; ...
    'HypoxicBurden_per_min'; ...
    'HypoxicBurden_per_mm2_per_sec'; ...
    'HypoxicBurden_per_mm2_per_min'; ...
    'Burden_Occupancy'; ...
    'Burden_RankAmplitude'; ...
    'Burden_AmplitudeComposite'; ...
    'HypoxicBurdenOverTime'; ...
    'HypoxicBurdenPerMm2OverTime'; ...
    'OxySinksPer1mm2'; ...
    'FOVEdge_um'; ...
    'Kappa_1000umPerFOVEdge'; ...
    'AreaCorrectionFactor_1mm2'};
OutputLocation = { ...
    'ROI/sink summary sheets'; ...
    'OxySinkEvents and hypoxic burden event rows'; ...
    'HypoxicBurden_EventBased'; ...
    'HypoxicBurden_EventBased'; ...
    'HypoxicBurden_EventBased'; ...
    'HypoxicBurden_EventBased'; ...
    'HypoxicBurden_EventBased'; ...
    'HypoxicBurden_EventBased'; ...
    'HypoxicBurden_ByRecording'; ...
    'HypoxicBurden_ByRecording'; ...
    'HypoxicBurden_ByRecording'; ...
    'HypoxicBurden_ByRecording'; ...
    'HypoxicBurden_ByRecording'; ...
    'HypoxicBurden_ByRecording'; ...
    'HypoxicBurden_ByRecording'; ...
    'HypoxicBurden_ByRecording'; ...
    'HypoxicBurden_ByRecording'; ...
    'HypoxicBurden_TimeSeries'; ...
    'HypoxicBurden_TimeSeries'; ...
    'OxySinksPer1mm2 trace sheets'; ...
    'SinkCountNormFactors'; ...
    'SinkCountNormFactors'; ...
    'SinkCountNormFactors'};
MetricBasis = { ...
    'ROI/sink-based mean'; ...
    'Event-based'; ...
    'Event-based'; ...
    'Event-based when event-specific area is matched'; ...
    'Event-based'; ...
    'Event-based'; ...
    'Event-based normalized to 1 mm^2 recording area'; ...
    'Recording-level duration source for time normalization'; ...
    'Recording/FOV-level sum of event rows'; ...
    'Recording-level sum normalized to 1 mm^2 recording area'; ...
    'Recording-level burden rate'; ...
    'Recording-level burden rate'; ...
    'Recording-level FOV-normalized burden rate'; ...
    'Recording-level FOV-normalized burden rate'; ...
    'Recording-level interface-contract burden variant'; ...
    'Recording-level interface-contract sensitivity variant'; ...
    'Recording-level interface-contract amplitude composite'; ...
    'Frame-level event-burden trace'; ...
    'Frame-level FOV-normalized event-burden trace'; ...
    'Frame-level recording-area normalized count'; ...
    'Recording/FOV-level'; ...
    'Recording/FOV-level'; ...
    'Recording/FOV-level'};
Formula = { ...
    'mean event normalized amplitude within one sink ROI'; ...
    'event normalized amplitude expressed as percent'; ...
    'Positive drop percent; sign conversion only with explicit negative_drop_percent provenance'; ...
    'Native area matched by RecordingID/SinkID/EventID'; ...
    'event duration in seconds'; ...
    'BurdenAmplitudePercent * BurdenArea_um2 * BurdenDuration_sec'; ...
    'PerEventBurdenContribution * (1e6 / BurdenRecordingArea_um2)'; ...
    'TableOxygenSinks.RecDuration matched to event rows'; ...
    'sum PerEventBurdenContribution across events in the recording/FOV'; ...
    'sum PerEventBurdenContribution_per_mm2 across events in the recording/FOV'; ...
    'HypoxicBurden / BurdenRecordingDuration_sec'; ...
    'HypoxicBurden * 60 / BurdenRecordingDuration_sec'; ...
    'HypoxicBurden_per_mm2 / BurdenRecordingDuration_sec'; ...
    'HypoxicBurden_per_mm2 * 60 / BurdenRecordingDuration_sec'; ...
    'sum(BurdenDuration_sec) * (1e6 / RecordingArea_um2) * (60 / RecordingDuration_sec)'; ...
    'sum(BurdenDuration_sec * within-recording amplitude quantile) * (1e6 / RecordingArea_um2) * (60 / RecordingDuration_sec)'; ...
    'sum(BurdenAmplitudePercent * BurdenArea_um2 * BurdenDuration_sec)'; ...
    'sum(active PerEventBurdenContribution / event duration)'; ...
    'sum(active PerEventBurdenContribution_per_mm2 / event duration)'; ...
    'active sink count per frame * AreaCorrectionFactor_1mm2'; ...
    'sqrt(RecordingArea_um2)'; ...
    '1000 / FOVEdge_um'; ...
    'Kappa_1000umPerFOVEdge ^ 2'};
Units = { ...
    'fraction'; ...
    'percent'; ...
    'percent positive drop'; ...
    'um^2'; ...
    'seconds'; ...
    'percent * um^2 * seconds'; ...
    'percent * um^2 * seconds per 1 mm^2'; ...
    'seconds'; ...
    'percent * um^2 * seconds'; ...
    'percent * um^2 * seconds per 1 mm^2'; ...
    'percent * um^2'; ...
    'percent * um^2 * seconds per minute'; ...
    'percent * um^2 per 1 mm^2'; ...
    'percent * um^2 * seconds per 1 mm^2 per minute'; ...
    'event-seconds per 1 mm^2 per minute'; ...
    'rank-weighted event-seconds per 1 mm^2 per minute'; ...
    'percent * um^2 * seconds'; ...
    'percent * um^2'; ...
    'percent * um^2 per 1 mm^2'; ...
    'count per 1 mm^2'; ...
    'um'; ...
    'unitless'; ...
    'unitless'};
Notes = { ...
    'This is not an individual-event row; it summarizes events within an ROI.'; ...
    'Use this for individual event amplitude when available.'; ...
    'Stored positive so larger values mean larger oxygen drops.'; ...
    'Native EventArea_um2 is used when unmatched; missing native measurements remain NaN.'; ...
    'Derived from event start/end or duration columns.'; ...
    'Primary individual-event hypoxic burden contribution.'; ...
    'Individual-event contribution scaled to a common recording area of 1 mm^2.'; ...
    'Preferred source is the recording duration saved in the oxygen sink summary table.'; ...
    'Main per-recording hypoxic burden summary; this is total burden in the recorded FOV.'; ...
    'Use this to compare hypoxic burden across recordings with different FOV sizes.'; ...
    'Use this to compare recordings with different recording durations.'; ...
    'Same time normalization as per-second, reported on a per-minute scale.'; ...
    'Use this when both recording duration and FOV size differ.'; ...
    'Recommended compact burden-rate metric for mixed FOV and recording duration datasets.'; ...
    'Concurrent event-time density, not tissue occupancy or absolute oxygen deficit.'; ...
    'Sensitivity variant using within-recording rank/quantile-transformed amplitude; relative within animal only.'; ...
    'Original amplitude x area x duration composite; valid within matched-acquisition cohorts only.'; ...
    'Frame-wise burden signal inside the recorded FOV; built from active individual event rows and not converted to a per-minute rate.'; ...
    'Recommended frame-wise burden signal for EEG/ECG or sleep-state alignment when FOV sizes differ; not converted to a per-minute rate.'; ...
    'Used to compare pocket counts across recordings with different FOV size.'; ...
    'Equivalent square edge of eligible tissue area; does not imply a square FOV.'; ...
    'Correction factor described as kappa = 1000 / FOV edge.'; ...
    'Multiplies raw frame-level counts to a 1 mm^2 area basis.'};

Definitions = table(MetricName,OutputLocation,MetricBasis,Formula,Units,Notes);
RecurrenceDefinitions = {
    'DetectedEvents','EventMeasurementQC','Native detection runs','Number of retained runs','runs','Includes flagged close runs; not a count of confirmed independent physiological episodes.';
    'CloseNativeRun','OxySinkEvents / OxySurgeEvents','Native run proximity','Either neighboring empty-frame gap < CloseNativeGapThresholdSec','Boolean','Both neighbors are flagged; no automatic deletion, merging or amplitude exclusion.';
    'PreviousNativeGapSec / NextNativeGapSec','OxySinkEvents / OxySurgeEvents','Same final site and event sign within recording','(Next native start - preceding native end - 1) / SampleF','seconds','Uses native masks, not refined timing. No neighbor is NaN; other sites do not trigger the flag.';
    'CloseNativeGapThresholdSec','OxySinkEvents / OxySurgeEvents','Development review threshold','sinkCloseNativeGapSec / surgeCloseNativeGapSec (both default 20)','seconds','Strictly shorter gaps are flagged. This is not a validated biological separation threshold.';
    'RecurrenceStatus','OxySinkEvents / OxySurgeEvents','Review status','close_native_runs_review or no_close_native_neighbor','text','Neither status confirms separate physiological events; candidate fragmentation remains possible.';
    'CloseNativeRunEvents','EventMeasurementQC','Recording run count by event sign','sum(CloseNativeRun)','runs','Counts both members of a close pair. These runs remain in descriptive event totals.';
    'RecurrenceNotAssessedEvents','EventMeasurementQC','Assessment coverage','Number of runs lacking recurrence assessment','runs','Both event signs are assessed in current outputs. Missing assessment is distinct from no close neighbor; zero-event recordings have zero unassessed events.';
    'TimingResolved','OxySinkEvents','Algorithmic boundary resolution','Both return crossings found and native trace below return level','Boolean','Does not confirm physiological independence. Close runs can have resolved timing; amplitude baseline QC is separate.'};
SurgeDefinitions = {
    'ContactFrameCount','OxySurgeEvents / SurgeCandidateRunQC','Native candidate frames touching a split/merge overlap','Number of unique contact endpoint frames in this run','frames','Includes contacts to rejected candidates. A frame counts once even with several edges. Does not exclude or join events.';
    'ContactFrames / ContactDurationSec / ContactFrameFraction','OxySurgeEvents / SurgeCandidateRunQC','Contact endpoint exposure','Semicolon-separated 1-based frames; count / SampleF; count / native duration in frames','frames / seconds / fraction','Both endpoints of a contact are annotated when they belong to the run. Seconds use frame-count duration, not elapsed endpoint separation.';
    'ContactFrameFootprintFraction','OxySurgeEvents / SurgeCandidateRunQC','Whole-candidate footprint at contact endpoints','Unique pixels in contact-frame masks / unique pixels in all native run masks','fraction','This describes candidate support exposed to contact. It is not the fraction of contaminated pixels or an oxygen measurement; repeated pixels count once.';
    'ContactEdgeCount / LinkedContactEdgeCount','OxySurgeEvents / SurgeCandidateRunQC','Incident contact connections','Count distinct incident contact edges / those chosen by the tracker','edges','A linked edge within one run counts once here, although both endpoint frames are annotated. Shared edges can contribute to both runs; do not sum as unique recording contacts.';
    'ContactNeighborCandidateRunIDs / ContactWithRejectedCandidate','OxySurgeEvents / SurgeCandidateRunQC','Other candidate runs connected by contact','Unique other candidate IDs; whether any of those runs fails duration qualification','IDs / Boolean','Recording-local IDs include rejected fragments. No inferred ancestry or physiological independence. Resolve pooled recording paths through StatsInfo.Recordings.';
    'SurgeTrackingEdges','Per-record CSV and surge MAT','All nonzero adjacent-frame overlaps, including unlinked edges','Endpoint candidate IDs, frame indices, shared pixels, areas, coverage, partner counts, eligibility, chosen link and contact flags','mixed','Endpoint event/site IDs are provided only for retained runs. RecordingID plus candidate ID identifies a run; short rejected siblings remain inspectable.';
    'SurgeContactFrames','Per-record CSV and surge MAT','One row per candidate run and contact endpoint frame','CandidateRunID + Frame; TimeSec=(Frame-1)/SampleF; candidate area=CandidatePixels*PixelSize^2','frames / seconds / square micrometers','Describes whole candidate masks, not just intersecting pixels. Includes retained and rejected runs; absent rows mean no contact only for assessed current outputs.';
    'ContactTrackingEvents / ContactTrackingNotAssessedEvents','EventMeasurementQC','Retained-event contact assessment','Count retained runs with contact frames / runs lacking detailed contact metadata','runs','Current surge outputs are assessed. Sink contact tracking is unassessed. Neither column counts independent physiological episodes.';
    'ContactWithRejectedCandidateEvents','EventMeasurementQC','Retained runs touching rejected candidates','sum(ContactWithRejectedCandidate) over retained events','runs','Rejected candidates themselves do not enter detected-event totals.';
    'ContactEventFrames','EventMeasurementQC','Contact exposure summed over retained runs','sum(ContactFrameCount)','event-frames','Two events contacting in one image frame contribute two event-frames. This is not the number of affected recording frames or the number of events.';
    'ContactEventDurationSec','EventMeasurementQC','Contact exposure summed over retained runs','sum(ContactDurationSec)','event-seconds','May count the same recording time for multiple events. No new event, exclusion or amplitude correction is inferred.';
    'ShapeChangeLinkCount / ShapeChangeLinkFrames','OxySurgeEvents / per-record SurgeCandidateRunQC','Adjacent links using the shape fallback','Count / semicolon-separated right-hand frame numbers','links / frames','Exactly one overlapping candidate partner at each endpoint; does not allow missing-frame bridging.';
    'TrackingContainmentFraction / TrackingMaxAreaRatio','OxySurgeEvents','Isolated shape-change limits','intersection / min(area) >= 0.8 and max(area) / min(area) <= 2','fraction / ratio','Applies only when primary mutual coverage fails. Limits are development assumptions, not biological calibration.';
    'PotentialGapContinuation','OxySurgeEvents / per-record SurgeCandidateRunQC','Geometric review flag','Candidate endpoint mutual coverage >= 0.6 across 1 to floor(2 * SampleF) empty frames','Boolean','Can involve rejected short runs or different final sites. No run is merged, extended or excluded by this flag.';
    'CandidateRunID / KeptAsEvent / RejectionReason','Per-record SurgeCandidateRunQC.csv and surge MAT','All tracked candidate runs before duration filtering','One local candidate ID; contiguous duration >= ceil(10 * SampleF) is retained','ID / Boolean / text','Rejected candidates have no SurgeID/EventID and are not events in pooled statistics. Includes short terminal fragments.';
    'PreviousCandidateRunID / NextCandidateRunID','Per-record SurgeGapReview.csv and surge MAT','Possible short-gap pair','Recording-local candidate IDs with gap length and endpoint coverage','IDs','Review candidates only; a detection dropout and real return can produce identical masks. Ledger remains per recording.';
    'ShapeChangeLinkedEvents / ShapeChangeTrackingNotAssessedEvents','EventMeasurementQC','Retained-event shape tracking QC','Count runs using fallback / runs lacking assessment','runs','Rejected candidates are absent from event totals. Current sink tracking is not assessed by the surge rule.';
    'PotentialGapContinuationEvents / GapReviewNotAssessedEvents','EventMeasurementQC','Retained-event gap review QC','Count flagged runs / runs lacking assessment','runs','May flag a retained event next to a rejected candidate; does not count confirmed physiological continuations.';
    'TrackingMethod / TrackingOverlapFraction','OxySurgeEvents','Adjacent-frame native runs','Mutual coverage >= 0.6, or isolated containment >= 0.8 with area ratio <= 2','fraction','One-to-one region matching; no missing-frame bridging. This is not a physiological boundary estimate.';
    'SiteAssignmentMethod / SiteOverlapFraction','OxySurgeEvents','Recurring spatial site','Mutual overlap with first retained event footprint >= surgeSiteOverlapFraction (0.6)','fraction','Site anchor is fixed. Same-site runs require at least one empty frame; grouping preserves event count.';
    'AmbiguousTracking','OxySurgeEvents','Possible split or merge contact','More than one spatially overlapping predecessor or successor candidate','Boolean','Includes nonzero overlaps below the match threshold and candidates later rejected by duration. Flagged runs remain included; no lineage claim.';
    'SiteAssignmentAmbiguous','OxySurgeEvents','Multiple eligible site anchors','More than one eligible fixed anchor at assignment','Boolean','Best overlap is used, ties use earliest site ID. Unflagged does not prove biological site identity.';
    'AmbiguousTrackingEvents / TrackingNotAssessedEvents','EventMeasurementQC','Tracking QC by recording and sign','Count flagged runs / runs without tracking assessment','runs','Current surge outputs are assessed; sink tracking is not assessed by this rule. Zero-event recordings have zero counts.';
    'AmbiguousSiteAssignmentEvents / SiteAssignmentNotAssessedEvents','EventMeasurementQC','Site-assignment QC by recording and sign','Count ambiguous assignments / runs without assignment assessment','runs','This assessment currently covers surge sites. Counts do not identify independent physiological events.';
    'NormOxySurgeAmp','OxySurgeEvents','Preserved-input event-footprint peak','max((signal - clean pre-event baseline) / baseline)','fraction','0.2 means a 20 percent optical increase. Negative values remain negative. Missing/contaminated baselines are unavailable; not calibrated oxygen concentration.';
    'NormOxySurgeAmpPercent','OxySurgeEvents','Same event-footprint amplitude','100 * NormOxySurgeAmp','percent','No ratio of z-scores, absolute-value correction or post-event baseline is used.';
    'MeanOxySurgeEvent_NormAmp','Surge site summary','Mean of available event amplitudes at one site','mean(finite NormOxySurgeAmp)','fraction','This is a site summary, not an individual event or a mouse-weighted group estimate.';
    'TimingMethod','OxySurgeEvents','Native detection timing','native_mask_bounds_not_refined','text','Surge timing has not been refined to physiological onset/return. Native bounds can truncate smooth signals.';
    'TouchesRecordingStart / TouchesRecordingEnd','OxySurgeEvents','Acquisition boundary contact','native start == 1 / native end == NFrames','Boolean','Flags possible truncation by the recording boundary; it does not establish true onset or return.'};
Definitions=[Definitions;cell2table(SurgeDefinitions,'VariableNames',Definitions.Properties.VariableNames)];
Definitions = [Definitions;cell2table(RecurrenceDefinitions,'VariableNames',Definitions.Properties.VariableNames)];
writetable(Definitions,OutputXlsx,'Sheet','MetricDefinitions');

end
