function writeStatsMetricDefinitionsSheet(OutputXlsx)
%WRITESTATSMETRICDEFINITIONSSHEET Write explicit metric definitions.

MetricName = { ...
    'MeanOxySinkEvent_NormAmp'; ...
    'NormOxySinkAmpPercent'; ...
    'BurdenAmplitudePercent'; ...
    'BurdenArea_um2'; ...
    'BurdenDuration_sec'; ...
    'PerEventBurdenContribution'; ...
    'PerEventBurdenContribution_per_mm2'; ...
    'BurdenRecordingDuration_sec'; ...
    'HypoxicBurden'; ...
    'HypoxicBurden_per_mm2'; ...
    'HypoxicBurden_per_sec'; ...
    'HypoxicBurden_per_min'; ...
    'HypoxicBurden_per_mm2_per_sec'; ...
    'HypoxicBurden_per_mm2_per_min'; ...
    'Burden_Occupancy'; ...
    'Burden_RankAmplitude'; ...
    'Burden_AmplitudeComposite'; ...
    'HypoxicBurdenOverTime'; ...
    'HypoxicBurdenPerMm2OverTime'; ...
    'OxySinksPer1mm2'; ...
    'FOVEdge_um'; ...
    'Kappa_1000umPerFOVEdge'; ...
    'AreaCorrectionFactor_1mm2'};
OutputLocation = { ...
    'ROI/sink summary sheets'; ...
    'OxySinkEvents and hypoxic burden event rows'; ...
    'HypoxicBurden_EventBased'; ...
    'HypoxicBurden_EventBased'; ...
    'HypoxicBurden_EventBased'; ...
    'HypoxicBurden_EventBased'; ...
    'HypoxicBurden_EventBased'; ...
    'HypoxicBurden_EventBased'; ...
    'HypoxicBurden_ByRecording'; ...
    'HypoxicBurden_ByRecording'; ...
    'HypoxicBurden_ByRecording'; ...
    'HypoxicBurden_ByRecording'; ...
    'HypoxicBurden_ByRecording'; ...
    'HypoxicBurden_ByRecording'; ...
    'HypoxicBurden_ByRecording'; ...
    'HypoxicBurden_ByRecording'; ...
    'HypoxicBurden_ByRecording'; ...
    'HypoxicBurden_TimeSeries'; ...
    'HypoxicBurden_TimeSeries'; ...
    'OxySinksPer1mm2 trace sheets'; ...
    'SinkCountNormFactors'; ...
    'SinkCountNormFactors'; ...
    'SinkCountNormFactors'};
MetricBasis = { ...
    'ROI/sink-based mean'; ...
    'Event-based'; ...
    'Event-based'; ...
    'Event-based when event-specific area is matched'; ...
    'Event-based'; ...
    'Event-based'; ...
    'Event-based normalized to 1 mm^2 recording area'; ...
    'Recording-level duration source for time normalization'; ...
    'Recording/FOV-level sum of event rows'; ...
    'Recording-level sum normalized to 1 mm^2 recording area'; ...
    'Recording-level burden rate'; ...
    'Recording-level burden rate'; ...
    'Recording-level FOV-normalized burden rate'; ...
    'Recording-level FOV-normalized burden rate'; ...
    'Recording-level interface-contract burden variant'; ...
    'Recording-level interface-contract sensitivity variant'; ...
    'Recording-level interface-contract amplitude composite'; ...
    'Frame-level event-burden trace'; ...
    'Frame-level FOV-normalized event-burden trace'; ...
    'Frame-level recording-area normalized count'; ...
    'Recording/FOV-level'; ...
    'Recording/FOV-level'; ...
    'Recording/FOV-level'};
Formula = { ...
    'mean event normalized amplitude within one sink ROI'; ...
    'event normalized amplitude expressed as percent'; ...
    'Positive drop percent; sign conversion only with explicit negative_drop_percent provenance'; ...
    'Native area matched by RecordingID/SinkID/EventID'; ...
    'event duration in seconds'; ...
    'BurdenAmplitudePercent * BurdenArea_um2 * BurdenDuration_sec'; ...
    'PerEventBurdenContribution * (1e6 / BurdenRecordingArea_um2)'; ...
    'TableOxygenSinks.RecDuration matched to event rows'; ...
    'sum PerEventBurdenContribution across events in the recording/FOV'; ...
    'sum PerEventBurdenContribution_per_mm2 across events in the recording/FOV'; ...
    'HypoxicBurden / BurdenRecordingDuration_sec'; ...
    'HypoxicBurden * 60 / BurdenRecordingDuration_sec'; ...
    'HypoxicBurden_per_mm2 / BurdenRecordingDuration_sec'; ...
    'HypoxicBurden_per_mm2 * 60 / BurdenRecordingDuration_sec'; ...
    'sum(BurdenDuration_sec) * (1e6 / RecordingArea_um2) * (60 / RecordingDuration_sec)'; ...
    'sum(BurdenDuration_sec * within-recording amplitude quantile) * (1e6 / RecordingArea_um2) * (60 / RecordingDuration_sec)'; ...
    'sum(BurdenAmplitudePercent * BurdenArea_um2 * BurdenDuration_sec)'; ...
    'sum(active PerEventBurdenContribution / event duration)'; ...
    'sum(active PerEventBurdenContribution_per_mm2 / event duration)'; ...
    'active sink count per frame * AreaCorrectionFactor_1mm2'; ...
    'sqrt(RecordingArea_um2)'; ...
    '1000 / FOVEdge_um'; ...
    'Kappa_1000umPerFOVEdge ^ 2'};
Units = { ...
    'fraction'; ...
    'percent'; ...
    'percent positive drop'; ...
    'um^2'; ...
    'seconds'; ...
    'percent * um^2 * seconds'; ...
    'percent * um^2 * seconds per 1 mm^2'; ...
    'seconds'; ...
    'percent * um^2 * seconds'; ...
    'percent * um^2 * seconds per 1 mm^2'; ...
    'percent * um^2'; ...
    'percent * um^2 * seconds per minute'; ...
    'percent * um^2 per 1 mm^2'; ...
    'percent * um^2 * seconds per 1 mm^2 per minute'; ...
    'event-seconds per 1 mm^2 per minute'; ...
    'rank-weighted event-seconds per 1 mm^2 per minute'; ...
    'percent * um^2 * seconds'; ...
    'percent * um^2'; ...
    'percent * um^2 per 1 mm^2'; ...
    'count per 1 mm^2'; ...
    'um'; ...
    'unitless'; ...
    'unitless'};
Notes = { ...
    'This is not an individual-event row; it summarizes events within an ROI.'; ...
    'Use this for individual event amplitude when available.'; ...
    'Stored positive so larger values mean larger oxygen drops.'; ...
    'Native EventArea_um2 is used when unmatched; missing native measurements remain NaN.'; ...
    'Derived from event start/end or duration columns.'; ...
    'Primary individual-event hypoxic burden contribution.'; ...
    'Individual-event contribution scaled to a common recording area of 1 mm^2.'; ...
    'Preferred source is the recording duration saved in the oxygen sink summary table.'; ...
    'Main per-recording hypoxic burden summary; this is total burden in the recorded FOV.'; ...
    'Use this to compare hypoxic burden across recordings with different FOV sizes.'; ...
    'Use this to compare recordings with different recording durations.'; ...
    'Same time normalization as per-second, reported on a per-minute scale.'; ...
    'Use this when both recording duration and FOV size differ.'; ...
    'Recommended compact burden-rate metric for mixed FOV and recording duration datasets.'; ...
    'Concurrent event-time density, not tissue occupancy or absolute oxygen deficit.'; ...
    'Sensitivity variant using within-recording rank/quantile-transformed amplitude; relative within animal only.'; ...
    'Original amplitude x area x duration composite; valid within matched-acquisition cohorts only.'; ...
    'Frame-wise burden signal inside the recorded FOV; built from active individual event rows and not converted to a per-minute rate.'; ...
    'Recommended frame-wise burden signal for EEG/ECG or sleep-state alignment when FOV sizes differ; not converted to a per-minute rate.'; ...
    'Used to compare pocket counts across recordings with different FOV size.'; ...
    'Equivalent square edge of eligible tissue area; does not imply a square FOV.'; ...
    'Correction factor described as kappa = 1000 / FOV edge.'; ...
    'Multiplies raw frame-level counts to a 1 mm^2 area basis.'};

Definitions = table(MetricName,OutputLocation,MetricBasis,Formula,Units,Notes);
RecurrenceDefinitions = {
    'DetectedEvents','EventMeasurementQC','Native detection runs','Number of retained runs','runs','Includes flagged close runs; not a count of confirmed independent physiological episodes.';
    'CloseNativeRun','OxySinkEvents','Native run proximity','Either neighboring empty-frame gap < CloseNativeGapThresholdSec','Boolean','Both neighbors are flagged; no automatic deletion, merging or amplitude exclusion.';
    'PreviousNativeGapSec / NextNativeGapSec','OxySinkEvents','Same final site within recording','(Next native start - preceding native end - 1) / SampleF','seconds','Uses native masks, not refined timing. No neighbor is NaN; other sites do not trigger the flag.';
    'CloseNativeGapThresholdSec','OxySinkEvents','Development review threshold','sinkCloseNativeGapSec (default 20)','seconds','Strictly shorter gaps are flagged. This is not a validated biological separation threshold.';
    'RecurrenceStatus','OxySinkEvents','Review status','close_native_runs_review or no_close_native_neighbor','text','Neither status confirms separate physiological events; candidate fragmentation remains possible.';
    'CloseNativeRunEvents','EventMeasurementQC','Recording sink-run count','sum(CloseNativeRun)','runs','Counts both members of a close pair. These runs remain in descriptive event totals.';
    'RecurrenceNotAssessedEvents','EventMeasurementQC','Assessment coverage','Number of runs lacking recurrence assessment','runs','Surges are not assessed by this sink proximity rule. Zero-event recordings have zero unassessed events.';
    'TimingResolved','OxySinkEvents','Algorithmic boundary resolution','Both return crossings found and native trace below return level','Boolean','Does not confirm physiological independence. Close runs can have resolved timing; amplitude baseline QC is separate.'};
Definitions = [Definitions;cell2table(RecurrenceDefinitions,'VariableNames',Definitions.Properties.VariableNames)];
writetable(Definitions,OutputXlsx,'Sheet','MetricDefinitions');

end
