function writeStatsMetricBasisSheet(OutputXlsx)
%WRITESTATSMETRICBASISSHEET Add a compact guide to ROI/event metric basis.

WorkbookItem = { ...
    'OxySinkArea_um to OxySinkPerimeter_um'; ...
    'OxySinkArea_Norm and OxySinkArea_Filled_Norm'; ...
    'MeanOxySinkEvent_Duration, MeanOxySinkEvent_NormAmp, MeanOxySinkEvent_SizeMod'; ...
    'HypoxicBurden'; ...
    'HypoxicBurden_per_mm2'; ...
    'HypoxicBurden_per_sec and HypoxicBurden_per_min'; ...
    'HypoxicBurden_per_mm2_per_sec and HypoxicBurden_per_mm2_per_min'; ...
    'Burden_Occupancy'; ...
    'Burden_RankAmplitude'; ...
    'Burden_AmplitudeComposite'; ...
    'HypoxicBurdenOverTime and HypoxicBurdenPerMm2OverTime'; ...
    'OxySinksPer1mm2'; ...
    'SinkCountNormFactors sheet'; ...
    'OxySinkEvents sheet'; ...
    'SortedSinkEventMetrics.xlsx'};
MetricBasis = { ...
    'ROI/sink-based'; ...
    'ROI/sink-based'; ...
    'ROI/sink-based mean of events within each sink'; ...
    'Recording/FOV-level total burden'; ...
    'Recording-area normalized burden'; ...
    'Recording-duration normalized burden'; ...
    'Recording-area and recording-duration normalized burden'; ...
    'Recording-level amplitude-free burden contract metric'; ...
    'Recording-level within-recording relative-amplitude contract metric'; ...
    'Recording-level amplitude x area x duration contract metric'; ...
    'Frame-level burden time series from individual event rows'; ...
    'Recording-area normalized time series'; ...
    'Recording-level normalization factors'; ...
    'Event rows, with morphology inherited from the parent sink ROI'; ...
    'Event-based, with morphology recalculated for each individual event'};
Notes = { ...
    'One value per detected oxygen sink ROI.'; ...
    'One normalized value per detected oxygen sink ROI.'; ...
    'Each value summarizes all events detected inside one sink ROI.'; ...
    'Sum of percent drop x event area x event duration across all events in one recording/FOV.'; ...
    'HypoxicBurden scaled by 1e6 / RecordingArea_um2 to compare recordings on a 1 mm2 area basis.'; ...
    'HypoxicBurden divided by recording duration, reported per second and per minute.'; ...
    'HypoxicBurden_per_mm2 divided by recording duration, reported per second and per minute.'; ...
    'Default cross-genotype/cross-cohort burden variant: event frequency x mean duration, normalized per mm2 and per minute.'; ...
    'Sensitivity burden variant: count x duration x within-recording amplitude quantile, normalized per mm2 and per minute. Relative within animal only.'; ...
    'Original composite burden variant: amplitude x area x duration. Use only within matched-acquisition cohorts.'; ...
    'One row per frame/time point; sums active event contribution divided by event duration. The per-mm2 version applies FOV normalization but is not per-minute normalized.'; ...
    'Raw active hypoxic pocket count per frame multiplied by (1000 / sqrt(RecordingArea_um2))^2.'; ...
    'Shows recording area, FOV edge estimate, kappa, and the 1 mm2 area correction factor.'; ...
    'Useful for event timing/amplitude; morphology columns describe the parent ROI.'; ...
    'Use this file when each hypoxic event, not each sink ROI, should be the analysis unit.'};

BasisTable = table(WorkbookItem,MetricBasis,Notes);
writetable(BasisTable,OutputXlsx,'Sheet','MetricBasis');
end
