function writeStatsNormalizationGuideSheet(OutputXlsx)
%WRITESTATSNORMALIZATIONGUIDESHEET Document normalization status of outputs.

MetricOrSheet = { ...
    'OxySinkArea_um, OxySinkFilledArea_um, OxySinkDiameter_um, OxySinkPerimeter_um'; ...
    'OxySinkArea_Norm, OxySinkArea_Filled_Norm'; ...
    'NumOxySinkEvents_Norm'; ...
    'MeanOxySinkEvent_Duration'; ...
    'MeanOxySinkEvent_NormAmp'; ...
    'OxySurgeArea_um, OxySurgeFilledArea_um, OxySurgeDiameter_um, OxySurgePerimeter_um'; ...
    'OxySurgeArea_Norm, OxySurgeArea_Filled_Norm'; ...
    'NumOxySurgeEvents_Norm'; ...
    'OxySinkEvents'; ...
    'OxySurgeEvents'; ...
    'HypoxicBurden'; ...
    'HypoxicBurden_per_mm2'; ...
    'HypoxicBurden_per_sec, HypoxicBurden_per_min'; ...
    'HypoxicBurden_per_mm2_per_sec, HypoxicBurden_per_mm2_per_min'; ...
    'Burden_Occupancy'; ...
    'Burden_RankAmplitude'; ...
    'Burden_AmplitudeComposite'; ...
    'HypoxicBurdenOverTime, HypoxicBurdenPerMm2OverTime'; ...
    'PerEventBurdenContribution'; ...
    'PerEventBurdenContribution_per_mm2'; ...
    'PerEventBurdenContribution_per_sec, PerEventBurdenContribution_per_min'; ...
    'PerEventBurdenContribution_per_mm2_per_sec, PerEventBurdenContribution_per_mm2_per_min'; ...
    'OxySinks HowMany / NumOngoingOxysinks'; ...
    'OxySinksPer1mm2 / NumOngoingOxysinksPerMm2'; ...
    'OxySinksArea_Norm / TotalSinkArea_Norm'; ...
    'OxySinksArea_um / TotalSinkArea_um'; ...
    'OxySurgesHowMany / NumOngoingOxysurges'; ...
    'OxySurgesArea / TotalSurgeArea'; ...
    'ROI Mean, ROI CovCoef, ROI Entropy'; ...
    'Aligned sink traces and event snippets'; ...
    'Behaviour-binned trace sheets'};

OutputLocation = { ...
    'Oxygen sink metric sheets'; ...
    'Oxygen sink metric sheets'; ...
    'NumOxySinkEvents_Norm'; ...
    'MeanOxySinkEvent_Duration'; ...
    'MeanOxySinkEvent_NormAmp'; ...
    'Oxygen surge metric sheets'; ...
    'Oxygen surge metric sheets'; ...
    'NumOxySurgeEvents_Norm'; ...
    'OxySinkEvents'; ...
    'OxySurgeEvents'; ...
    'HypoxicBurden_ByRecording'; ...
    'HypoxicBurden_ByRecording'; ...
    'HypoxicBurden_ByRecording'; ...
    'HypoxicBurden_ByRecording'; ...
    'HypoxicBurden_ByRecording'; ...
    'HypoxicBurden_ByRecording'; ...
    'HypoxicBurden_ByRecording'; ...
    'HypoxicBurden_TimeSeries'; ...
    'HypoxicBurden_EventBased'; ...
    'HypoxicBurden_EventBased'; ...
    'HypoxicBurden_EventBased'; ...
    'HypoxicBurden_EventBased'; ...
    'Pooled traces / DataOutput.mat'; ...
    'Pooled traces / DataOutput.mat'; ...
    'Pooled traces / DataOutput.mat'; ...
    'Pooled traces / DataOutput.mat'; ...
    'Pooled traces / DataOutput.mat'; ...
    'Pooled traces / DataOutput.mat'; ...
    'ROI trace and grouped metric sheets'; ...
    'BLI trace/event-snippet sheets'; ...
    'BLI binned trace sheets'};

AnalysisUnit = { ...
    'Sink ROI'; 'Sink ROI'; 'Sink ROI'; 'Sink ROI event summary'; 'Sink ROI event summary'; ...
    'Surge ROI'; 'Surge ROI'; 'Surge ROI'; 'Individual sink event'; 'Individual surge event'; ...
    'Recording/FOV'; 'Recording/FOV'; 'Recording/FOV'; 'Recording/FOV'; ...
    'Recording/FOV'; 'Recording/FOV'; 'Recording/FOV'; ...
    'Frame/time point'; ...
    'Individual sink event'; 'Individual sink event'; 'Individual sink event'; 'Individual sink event'; ...
    'Frame/time point'; 'Frame/time point'; 'Frame/time point'; 'Frame/time point'; ...
    'Frame/time point'; 'Frame/time point'; 'ROI/time point'; 'Event-aligned trace'; 'Behaviour percentile bin'};

AreaNormalization = { ...
    'No'; ...
    'Yes: divided by RecAreaSize'; ...
    'No'; ...
    'No'; ...
    'Not applicable: amplitude fraction/percent'; ...
    'No'; ...
    'Yes: divided by RecAreaSize_Surge'; ...
    'No'; ...
    'No for morphology columns unless using event-specific Area_norm'; ...
    'No for morphology columns'; ...
    'No: total burden in recorded FOV'; ...
    'Yes: scaled by 1e6 / BurdenRecordingArea_um2'; ...
    'No'; ...
    'Yes: scaled by 1e6 / BurdenRecordingArea_um2'; ...
    'Yes: scaled by 1e6 / BurdenRecordingArea_um2'; ...
    'Yes: scaled by 1e6 / BurdenRecordingArea_um2'; ...
    'No: original area is part of the composite'; ...
    'Raw trace and FOV-normalized trace are both provided'; ...
    'No'; ...
    'Yes: scaled by 1e6 / BurdenRecordingArea_um2'; ...
    'No'; ...
    'Yes: scaled by 1e6 / BurdenRecordingArea_um2'; ...
    'No'; ...
    'Yes: active count scaled to 1 mm2'; ...
    'Yes: active sink area divided by recording area'; ...
    'No: um2 total active sink area'; ...
    'No'; ...
    'Partly unclear: active surge area, not currently per-mm2 normalized'; ...
    'Not applicable'; ...
    'Not applicable unless trace is an area/count trace'; ...
    'Depends on source trace'};

TimeNormalization = { ...
    'No'; ...
    'No'; ...
    'Yes: events per minute'; ...
    'No: duration itself is reported'; ...
    'Not applicable'; ...
    'No'; ...
    'No'; ...
    'Yes, but currently events per second because no *60 factor is applied'; ...
    'No: event rows include timing but are not rates'; ...
    'No: event rows include timing but are not rates'; ...
    'No: total across whole recording'; ...
    'No: total across whole recording'; ...
    'Yes: per second and per minute'; ...
    'Yes: per second and per minute'; ...
    'Yes: per minute'; ...
    'Yes: per minute'; ...
    'No: total across whole recording'; ...
    'Frame-level, not summarized per minute'; ...
    'No: contribution of one event'; ...
    'No: contribution of one event, area-normalized only'; ...
    'Yes: divided by recording duration'; ...
    'Yes: divided by recording duration'; ...
    'Frame-level, not summarized per minute'; ...
    'Frame-level, not summarized per minute'; ...
    'Frame-level, not summarized per minute'; ...
    'Frame-level, not summarized per minute'; ...
    'Frame-level, not summarized per minute'; ...
    'Frame-level, not summarized per minute'; ...
    'Frame-level trace feature'; ...
    'Event-aligned, not recording-rate normalized'; ...
    'Behaviour-bin mean, not recording-rate normalized'};

NormalizationStatus = { ...
    'Raw physical size'; ...
    'Area-normalized'; ...
    'Time-normalized only'; ...
    'Event-duration descriptor'; ...
    'Amplitude-normalized only'; ...
    'Raw physical size'; ...
    'Area-normalized'; ...
    'Time-normalized, but unit naming should be reviewed'; ...
    'Event-level raw/provenance table'; ...
    'Event-level raw/provenance table'; ...
    'Unnormalized total'; ...
    'Area-normalized total'; ...
    'Time-normalized total'; ...
    'Area- and time-normalized total'; ...
    'Area- and time-normalized occupancy burden; amplitude-free'; ...
    'Area- and time-normalized rank-amplitude burden; relative within recording'; ...
    'Unnormalized original amplitude composite'; ...
    'Frame-level burden trace; includes FOV-normalized version'; ...
    'Event contribution'; ...
    'Area-normalized event contribution'; ...
    'Time-rate event contribution'; ...
    'Area- and time-rate event contribution'; ...
    'Unnormalized frame count'; ...
    'Area-normalized frame count'; ...
    'Area-normalized frame area'; ...
    'Unnormalized frame area'; ...
    'Unnormalized frame count'; ...
    'Incomplete for FOV comparison'; ...
    'Signal feature'; ...
    'Trace export'; ...
    'Behaviour-conditioned trace export'};

RecommendedForComparison = { ...
    'Use only when pixel size/FOV context is comparable, or pair with normalized area outputs.'; ...
    'Useful across FOV sizes; still ROI-level, not event-level.'; ...
    'Useful across recording durations; not FOV-normalized.'; ...
    'Useful as event duration descriptor, not burden/frequency.'; ...
    'Useful for raw-amplitude comparison because it is normalized to local raw baseline.'; ...
    'Use only when pixel size/FOV context is comparable.'; ...
    'Useful across FOV sizes; still ROI-level.'; ...
    'Review whether per-minute scaling should match sink event frequency.'; ...
    'Use event rows for event-level amplitude/timing; use event-specific metrics for event morphology.'; ...
    'Use for surge event timing/amplitude; surge event area is still parent-ROI morphology.'; ...
    'Use for total burden in the recorded FOV only.'; ...
    'Use when FOV sizes differ but recording durations are equal.'; ...
    'Use when recording durations differ but FOV sizes are equal.'; ...
    'Recommended main burden-rate metric when both FOV and duration differ.'; ...
    'Default burden variant for cross-genotype/cross-cohort comparisons.'; ...
    'Sensitivity variant; relative within animal only, not absolute amplitude comparison.'; ...
    'Use only within matched-acquisition cohorts.'; ...
    'Use HypoxicBurdenPerMm2OverTime for EEG/ECG/sleep-state alignment across recordings with different FOVs.'; ...
    'Use for single-event contribution, not recording-level comparison.'; ...
    'Use when comparing single events across FOV sizes.'; ...
    'Use cautiously; event-rate contribution is mostly provenance for recording rates.'; ...
    'Use cautiously; the recording-level rate is usually easier to interpret.'; ...
    'Use OxySinksPer1mm2 for FOV-normalized count comparison.'; ...
    'Recommended for frame-level pocket-count comparison across FOVs.'; ...
    'Useful for frame-level area burden fraction; not explicitly per minute.'; ...
    'Use TotalSinkArea_Norm for FOV-normalized area comparison.'; ...
    'Consider adding OxySurgesPer1mm2 if surge count comparison across FOVs matters.'; ...
    'Consider adding TotalSurgeArea_Norm for FOV-normalized surge area comparison.'; ...
    'Use as signal-quality or trace feature, not event burden.'; ...
    'Use for shape/timing of event-aligned responses, not total burden.'; ...
    'Use for behaviour dependence; normalization follows the input trace.'};

Guide = table(MetricOrSheet,OutputLocation,AnalysisUnit,AreaNormalization,TimeNormalization, ...
    NormalizationStatus,RecommendedForComparison);
writetable(Guide,OutputXlsx,'Sheet','NormalizationGuide');

end
