function writeStatsMetricDefinitionsSheet(OutputXlsx)
%WRITESTATSMETRICDEFINITIONSSHEET Write explicit metric definitions.

MetricName = { ...
    'MeanOxySinkEvent_NormAmp'; ...
    'NormOxySinkAmpPercent'; ...
    'BurdenAmplitudePercent'; ...
    'BurdenArea_um2'; ...
    'BurdenDuration_sec'; ...
    'PerEventBurdenContribution'; ...
    'HypoxicBurden'; ...
    'OxySinksPer1mm2'; ...
    'FOVEdge_um'; ...
    'Kappa_1000umPerFOVEdge'; ...
    'AreaCorrectionFactor_1mm2'};
OutputLocation = { ...
    'ROI/sink summary sheets'; ...
    'OxySinkEvents and hypoxic burden event rows'; ...
    'HypoxicBurden_EventBased'; ...
    'HypoxicBurden_EventBased'; ...
    'HypoxicBurden_EventBased'; ...
    'HypoxicBurden_EventBased'; ...
    'HypoxicBurden_ByRecording'; ...
    'OxySinksPer1mm2 trace sheets'; ...
    'SinkCountNormFactors'; ...
    'SinkCountNormFactors'; ...
    'SinkCountNormFactors'};
MetricBasis = { ...
    'ROI/sink-based mean'; ...
    'Event-based'; ...
    'Event-based'; ...
    'Event-based when event-specific area is matched'; ...
    'Event-based'; ...
    'Event-based'; ...
    'Recording/FOV-level sum of event rows'; ...
    'Frame-level recording-area normalized count'; ...
    'Recording/FOV-level'; ...
    'Recording/FOV-level'; ...
    'Recording/FOV-level'};
Formula = { ...
    'mean event normalized amplitude within one sink ROI'; ...
    'event normalized amplitude expressed as percent'; ...
    'NormOxySinkAmpPercent * -1 when oxygen drops are negative'; ...
    'EventSpecificMetrics.Area_um matched by Mouse/SinkID/EventID'; ...
    'event duration in seconds'; ...
    'BurdenAmplitudePercent * BurdenArea_um2 * BurdenDuration_sec'; ...
    'sum PerEventBurdenContribution across events in the recording/FOV'; ...
    'active sink count per frame * AreaCorrectionFactor_1mm2'; ...
    'sqrt(RecordingArea_um2)'; ...
    '1000 / FOVEdge_um'; ...
    'Kappa_1000umPerFOVEdge ^ 2'};
Units = { ...
    'fraction or percent depending on source sheet'; ...
    'percent'; ...
    'percent positive drop'; ...
    'um^2'; ...
    'seconds'; ...
    'percent * um^2 * seconds'; ...
    'percent * um^2 * seconds'; ...
    'count per 1 mm^2'; ...
    'um'; ...
    'unitless'; ...
    'unitless'};
Notes = { ...
    'This is not an individual-event row; it summarizes events within an ROI.'; ...
    'Use this for individual event amplitude when available.'; ...
    'Stored positive so larger values mean larger oxygen drops.'; ...
    'Falls back to ROI-level MeanOxySinkArea_um only if no event-specific match exists; fallback rows are flagged.'; ...
    'Derived from event start/end or duration columns.'; ...
    'Primary individual-event hypoxic burden contribution.'; ...
    'Main per-recording hypoxic burden summary.'; ...
    'Used to compare pocket counts across recordings with different FOV size.'; ...
    'Square field-of-view edge inferred from recording area.'; ...
    'Correction factor described as kappa = 1000 / FOV edge.'; ...
    'Multiplies raw frame-level counts to a 1 mm^2 area basis.'};

Definitions = table(MetricName,OutputLocation,MetricBasis,Formula,Units,Notes);
writetable(Definitions,OutputXlsx,'Sheet','MetricDefinitions');

end
