function writeStatsMetricBasisSheet(OutputXlsx)
%WRITESTATSMETRICBASISSHEET Add a compact guide to ROI/event metric basis.

WorkbookItem = { ...
    'OxySinkArea_um to OxySinkPerimeter_um'; ...
    'OxySinkArea_Norm and OxySinkArea_Filled_Norm'; ...
    'MeanOxySinkEvent_Duration, MeanOxySinkEvent_NormAmp, MeanOxySinkEvent_SizeMod'; ...
    'OxySinksPer1mm2'; ...
    'SinkCountNormFactors sheet'; ...
    'OxySinkEvents sheet'; ...
    'SortedSinkEventMetrics.xlsx'};
MetricBasis = { ...
    'ROI/sink-based'; ...
    'ROI/sink-based'; ...
    'ROI/sink-based mean of events within each sink'; ...
    'Recording-area normalized time series'; ...
    'Recording-level normalization factors'; ...
    'Event rows, with morphology inherited from the parent sink ROI'; ...
    'Event-based, with morphology recalculated for each individual event'};
Notes = { ...
    'One value per detected oxygen sink ROI.'; ...
    'One normalized value per detected oxygen sink ROI.'; ...
    'Each value summarizes all events detected inside one sink ROI.'; ...
    'Raw active hypoxic pocket count per frame multiplied by (1000 / sqrt(RecordingArea_um2))^2.'; ...
    'Shows recording area, FOV edge estimate, kappa, and the 1 mm2 area correction factor.'; ...
    'Useful for event timing/amplitude; morphology columns describe the parent ROI.'; ...
    'Use this file when each hypoxic event, not each sink ROI, should be the analysis unit.'};

BasisTable = table(WorkbookItem,MetricBasis,Notes);
writetable(BasisTable,OutputXlsx,'Sheet','MetricBasis');
end
