function Bundle=createBOIG4EvidenceBundle(OutputFolder,RunPath,AutomaticEventRow,ReviewedAuditPath,ReviewedEventRow,BoundaryPath,ReferencePath,PreviousBundlePath)
%CREATEBOIG4EVIDENCEBUNDLE Export two saved numerical replays and one linked review.
% No detection, statistics, source-image reconstruction or reviewed amplitude.
setupOxygenDynamicsPath;
if nargin<8,PreviousBundlePath='';end
OutputFolder=char(OutputFolder);
assert(~isfolder(OutputFolder)&&~isfile(OutputFolder), ...
    'OxygenDynamics:G4OutputExists','Choose a new evidence folder; existing outputs are immutable.');
localMapPath=[OutputFolder '.local-sources.json'];
assert(~isfile(localMapPath),'OxygenDynamics:G4OutputExists','The separate local source map already exists.');

Run=loadBOIRecordingRun(RunPath);
Auto=loadBOIEventReview(Run.Paths.EventAudit);
assert(isnumeric(AutomaticEventRow)&&isscalar(AutomaticEventRow)&&AutomaticEventRow==fix(AutomaticEventRow)&& ...
    AutomaticEventRow>=1&&AutomaticEventRow<=height(Auto.Audit), ...
    'OxygenDynamics:G4EventRow','Choose one saved automatic event row.');
event=Auto.Audit(AutomaticEventRow,:);trace=Auto.Traces{AutomaticEventRow};
assert(event.EventType=="sink"&&event.RecomputedStatus=="valid"&&isfinite(event.StoredAmplitude)&& ...
    numel(trace.CleanBaselineFrames)==event.BaselineWindowFrames, ...
    'OxygenDynamics:G4MissingIngredient','The chosen automatic event lacks a complete finite baseline/amplitude.');
baselineFrames=double(trace.CleanBaselineFrames(:));
measureFrames=(double(event.StartFrame):double(event.EndFrame))';
raw=double(trace.Raw(:));baselineValues=raw(baselineFrames);eventValues=raw(measureFrames);
B0=mean(baselineValues);
if event.EventType=="sink",[extreme,offset]=min(eventValues);amplitude=-(extreme-B0)/B0;
else,[extreme,offset]=max(eventValues);amplitude=(extreme-B0)/B0;end
assert(isfinite(B0)&&B0>0&&isfinite(amplitude)&& ...
    closeEnough(amplitude,event.StoredAmplitude)&&closeEnough(amplitude,event.RecomputedAmplitude)&& ...
    closeEnough(B0,event.RecomputedBaseline), ...
    'OxygenDynamics:G4ReplayMismatch','Saved event ingredients do not reproduce the automatic measurement.');

S=load(Run.Paths.DataOutput,'RecordingWindowMetrics','WindowFrameIngredients');
assert(all(isfield(S,{'RecordingWindowMetrics','WindowFrameIngredients'}))&& ...
    istable(S.RecordingWindowMetrics)&&istable(S.WindowFrameIngredients), ...
    'OxygenDynamics:G4MissingIngredient','Saved recording window ingredients are unavailable.');
W=S.RecordingWindowMetrics;F=S.WindowFrameIngredients;
requiredW={'RecordingID','WindowID','StartSec','EndSec','AreaUm2','MeanOccupiedTissueFraction', ...
    'CoveredAreaTime_um2_sec','AnalyzedTissueTime_um2_sec','OccupancyStatus','ExposureBasis'};
requiredF={'RecordingID','WindowID','Frame','ModeledStartSec','ModeledEndSec','WindowOverlapSec', ...
    'OccupiedArea_um2','AnalyzedArea_um2','CoveredAreaTime_um2_sec','AnalyzedTissueTime_um2_sec','OccupancyStatus'};
assert(all(ismember(requiredW,W.Properties.VariableNames))&&all(ismember(requiredF,F.Properties.VariableNames)), ...
    'OxygenDynamics:G4MissingIngredient','Saved recording summary fields are incomplete.');
selected=W(string(W.WindowID)=="whole_recording",:);
assert(height(selected)==1,'OxygenDynamics:G4MissingIngredient','Require one saved whole-recording sink window.');
frames=F(string(F.WindowID)=="whole_recording"&string(F.RecordingID)==string(selected.RecordingID),:);
assert(strcmp(string(event.RecordingID),string(selected.RecordingID))&& ...
    ~isempty(frames)&&isequal(double(frames.Frame(:)),(1:height(frames))')&& ...
    closeEnough(sum(frames.WindowOverlapSec),selected.EndSec-selected.StartSec)&& ...
    all(string(frames.OccupancyStatus)==string(selected.OccupancyStatus)), ...
    'OxygenDynamics:G4MissingIngredient','Whole-recording per-frame ingredients are incomplete or mismatched.');
frameCsvPath=fullfile(fileparts(Run.Paths.DataOutput),'WindowFrameIngredients.csv');
assert(isfile(frameCsvPath),'OxygenDynamics:G4MissingIngredient','Saved frame-ingredient CSV is missing.');
csv=readtable(frameCsvPath,'TextType','string');
csv=csv(string(csv.WindowID)=="whole_recording"&string(csv.RecordingID)==string(selected.RecordingID),:);
assert(height(csv)==height(frames)&&isequaln(csv.Frame,frames.Frame)&& ...
    isequaln(csv.CoveredAreaTime_um2_sec,frames.CoveredAreaTime_um2_sec)&& ...
    isequaln(csv.AnalyzedTissueTime_um2_sec,frames.AnalyzedTissueTime_um2_sec), ...
    'OxygenDynamics:G4ReplayMismatch','Saved frame CSV differs from the saved statistics ingredients.');
covered=sum(frames.CoveredAreaTime_um2_sec);tissue=sum(frames.AnalyzedTissueTime_um2_sec);
fraction=covered/tissue;
assert(isfinite(tissue)&&tissue>0&&isfinite(fraction)&& ...
    closeEnough(covered,selected.CoveredAreaTime_um2_sec)&& ...
    closeEnough(tissue,selected.AnalyzedTissueTime_um2_sec)&& ...
    closeEnough(fraction,selected.MeanOccupiedTissueFraction), ...
    'OxygenDynamics:G4ReplayMismatch','Saved frame ingredients do not reproduce the recording summary.');

Review=loadBOIEventReview(ReviewedAuditPath);
assert(isnumeric(ReviewedEventRow)&&isscalar(ReviewedEventRow)&&ReviewedEventRow==fix(ReviewedEventRow)&& ...
    ReviewedEventRow>=1&&ReviewedEventRow<=height(Review.Audit), ...
    'OxygenDynamics:G4EventRow','Choose one saved reviewed event row.');
Review.BoundaryReview=loadBOIBoundaryReview(Review,BoundaryPath);
Review=loadBOIReferenceJudgments(Review,ReferencePath);
Boundary=getBOIBoundaryReview(Review,ReviewedEventRow);
judgments=Review.ReferenceJudgments([Review.ReferenceJudgments.AuditRow]==ReviewedEventRow);
assert(~isempty(Boundary.Annotation)&&isscalar(judgments)&& ...
    isequal(judgments.OnsetFrame,Boundary.Annotation.PreferredOnsetFrame), ...
    'OxygenDynamics:G4ReviewMismatch','Boundary and reference choices are not one linked saved decision.');
J=judgments.Document;reviewed=Review.Audit(ReviewedEventRow,:);
assert(reviewed.RecomputedStatus~="valid"&&~isfinite(reviewed.StoredAmplitude)&& ...
    ~isfinite(reviewed.RecomputedAmplitude), ...
    'OxygenDynamics:G4ReviewMismatch','This bounded review example must retain its unavailable automatic amplitude.');

dictionaryPath=fullfile(fileparts(Run.Paths.DataOutput),'BOIMeasurementDictionary.json');
[~,dictionary]=getBOIMeasurementDictionary(dictionaryPath);
definitions=dictionary.Measurements;
ids=string({definitions.MeasurementID});
assert(sum(ids=="BOI-M06")==1&&sum(ids=="BOI-M01")==1, ...
    'OxygenDynamics:G4MissingIngredient','Saved dictionary lacks the two named measurement definitions.');

Bundle=struct('Schema','boi-g4-evidence-1','CreatedUTC',utcNow(), ...
    'PackageRole','bounded_separate_examples_not_a_single_recording_result', ...
    'ScientificStatus','not_established','CalculationRole','saved_automatic_replay_only', ...
    'DictionaryVersion',dictionary.Version, ...
    'Definitions',[definitions(ids=="BOI-M06"),definitions(ids=="BOI-M01")]);
Bundle.Sources=struct('AutomaticRunSHA256',oxygenFileSHA256(Run.ManifestPath), ...
    'AutomaticAuditSHA256',Auto.AuditSHA256,'AutomaticRawSHA256',Run.SourceSHA256, ...
    'AutomaticDataOutputSHA256',oxygenFileSHA256(Run.Paths.DataOutput), ...
    'FrameIngredientsSHA256',oxygenFileSHA256(frameCsvPath), ...
    'DictionarySHA256',oxygenFileSHA256(dictionaryPath), ...
    'ReviewedAuditSHA256',Review.AuditSHA256,'ReviewedRawSHA256',Review.AnalysisInfo.RawSHA256, ...
    'BoundarySHA256',Review.BoundaryReview.SHA256,'ReferenceSHA256',judgments.SHA256);
Bundle.AutomaticEvent=struct('MeasurementID','BOI-M06','EventType',char(event.EventType), ...
    'SiteID',event.SiteID,'EventID',event.EventID,'AuditRow',AutomaticEventRow, ...
    'MeasurementStartFrame',event.StartFrame,'MeasurementEndFrame',event.EndFrame, ...
    'NativeStartFrame',event.DetectedStartFrame,'NativeEndFrame',event.DetectedEndFrame, ...
    'FootprintPixels',event.FootprintPixels,'SampleHz',Auto.AnalysisInfo.AnalysisParams.fs, ...
    'PixelSizeUm',Run.Request.Options.PixelSizeUm,'SupportProfile',Run.SupportProfile, ...
    'FrameTimingStatus',char(Run.Request.InputReview.Acquisition.FrameTimingStatus), ...
    'BaselineFrames',baselineFrames,'BaselineValues',baselineValues, ...
    'MeasurementFrames',measureFrames,'MeasurementValues',eventValues, ...
    'BaselineInputUnits',event.RecomputedBaseline,'ExtremeFrame',measureFrames(offset), ...
    'ExtremeInputUnits',extreme,'SavedAmplitudeFraction',event.StoredAmplitude, ...
    'ReplayAmplitudeFraction',amplitude,'Availability',char(event.RecomputedStatus), ...
    'SourceSignal','preserved_input_fixed_union_footprint');
Bundle.RecordingSummary=struct('MeasurementID','BOI-M01','Sign','sink', ...
    'WindowID','whole_recording','StartSec',selected.StartSec,'EndSec',selected.EndSec, ...
    'SampleHz',Run.Request.Options.SampleHz,'PixelSizeUm',Run.Request.Options.PixelSizeUm, ...
    'SupportProfile',Run.SupportProfile, ...
    'FrameTimingStatus',char(Run.Request.InputReview.Acquisition.FrameTimingStatus), ...
    'StaticAnalyzedAreaUm2',selected.AreaUm2, ...
    'Frame',frames.Frame,'ModeledStartSec',frames.ModeledStartSec, ...
    'ModeledEndSec',frames.ModeledEndSec,'WindowOverlapSec',frames.WindowOverlapSec, ...
    'OccupiedAreaUm2',frames.OccupiedArea_um2,'AnalyzedAreaUm2',frames.AnalyzedArea_um2, ...
    'CoveredAreaTimeUm2Sec',frames.CoveredAreaTime_um2_sec, ...
    'AnalyzedTissueTimeUm2Sec',frames.AnalyzedTissueTime_um2_sec, ...
    'SavedCoveredAreaTimeUm2Sec',selected.CoveredAreaTime_um2_sec, ...
    'SavedAnalyzedTissueTimeUm2Sec',selected.AnalyzedTissueTime_um2_sec, ...
    'SavedFraction',selected.MeanOccupiedTissueFraction,'ReplayFraction',fraction, ...
    'OccupancyStatus',char(selected.OccupancyStatus), ...
    'ExposureBasis',char(selected.ExposureBasis));
history=Boundary.History;
H=struct('Revision',{},'PreviousEventRevision',{},'Annotation',{},'PreviousAnnotation',{},'CreatedUTC',{});
for k=1:numel(history)
    H(end+1)=struct('Revision',history(k).Revision, ...
        'PreviousEventRevision',history(k).PreviousEventRevision, ...
        'Annotation',history(k).Annotation,'PreviousAnnotation',history(k).PreviousAnnotation, ...
        'CreatedUTC',history(k).CreatedUTC); %#ok<AGROW>
end
tissueDecision=struct('Status','not_captured','Reason','No saved tissue decision was attached.');
if isfield(Review.AnalysisInfo,'BOITissueSupport')&& ...
        isfield(Review.AnalysisInfo.BOITissueSupport,'RawJSON')&& ...
        ~isempty(Review.AnalysisInfo.BOITissueSupport.RawJSON)
    T=jsondecode(Review.AnalysisInfo.BOITissueSupport.RawJSON);
    tissueDecision=struct('Status',char(T.ReviewStatus),'DecisionID',char(T.DecisionID), ...
        'Actor',char(T.Actor),'Reason',char(T.Reason),'RecordedUTC',char(T.RecordedUTC), ...
        'SupportProfile',char(Review.AnalysisInfo.BOISupportProfile), ...
        'SupportSHA256',char(Review.AnalysisInfo.BOITissueSupport.SHA256), ...
        'MaskPixelCount',numel(T.MaskPixels));
end
Bundle.ReviewedEvent=struct('EventType',char(reviewed.EventType),'SiteID',reviewed.SiteID, ...
    'EventID',reviewed.EventID,'AuditRow',ReviewedEventRow, ...
    'AutomaticStartFrame',reviewed.StartFrame,'AutomaticEndFrame',reviewed.EndFrame, ...
    'AutomaticBaselineStatus',char(reviewed.RecomputedStatus), ...
    'AutomaticCleanBaselineFrames',numel(Review.Traces{ReviewedEventRow}.CleanBaselineFrames), ...
    'AutomaticRequiredBaselineFrames',reviewed.BaselineWindowFrames, ...
    'AutomaticAmplitudeFraction',reviewed.StoredAmplitude, ...
    'ReviewedAmplitudeFraction',NaN,'ReviewedAmplitudeStatus','not_calculated', ...
    'BoundaryStatus',Boundary.Status,'BoundaryAnnotation',Boundary.Annotation, ...
    'BoundaryHistory',H,'ReferenceDecisionID',char(J.DecisionID), ...
    'ReferenceReviewer',char(J.Reviewer),'ReferenceRecordedUTC',char(J.RecordedUTC), ...
    'ReferenceOnsetFrame',judgments.OnsetFrame,'ReferenceFrames',judgments.Frames, ...
    'ReferenceStatus',char(J.ReferenceJudgment),'TissueDecision',tissueDecision);
Bundle.PreviousBundleSHA256='';
if ~isempty(PreviousBundlePath)
    previous=loadBOIG4EvidenceBundle(PreviousBundlePath);
    assert(strcmp(previous.Sources.AutomaticRunSHA256,Bundle.Sources.AutomaticRunSHA256)&& ...
        strcmp(previous.Sources.ReviewedAuditSHA256,Bundle.Sources.ReviewedAuditSHA256), ...
        'OxygenDynamics:G4ReviewMismatch','A revision must retain both automatic source identities.');
    Bundle.PreviousBundleSHA256=oxygenFileSHA256(fullfile(char(PreviousBundlePath),'Evidence.json'));
end

mkdir(OutputFolder);
writeBOIRunJSON(fullfile(OutputFolder,'Evidence.json'),Bundle);
writeReadable(fullfile(OutputFolder,'Evidence.md'),Bundle);
local=struct('Schema','boi-g4-local-source-map-1','PrivateLocalPaths',true, ...
    'AutomaticRun',Run.ManifestPath,'AutomaticAudit',Run.Paths.EventAudit, ...
    'AutomaticDataOutput',Run.Paths.DataOutput,'ReviewedAudit',Review.AuditPath, ...
    'Boundary',Review.BoundaryReview.Path,'Reference',judgments.Path);
writeBOIRunJSON(localMapPath,local);
index=struct('Schema','boi-g4-evidence-index-1','Status','complete', ...
    'EvidenceFile','Evidence.json','EvidenceSHA256',oxygenFileSHA256(fullfile(OutputFolder,'Evidence.json')), ...
    'ReadableFile','Evidence.md','ReadableSHA256',oxygenFileSHA256(fullfile(OutputFolder,'Evidence.md')));
writeBOIRunJSON(fullfile(OutputFolder,'BundleIndex.json'),index);
end

function yes=closeEnough(actual,saved)
yes=isfinite(actual)&&isfinite(saved)&&abs(actual-saved)<=1e-12*max(1,abs(saved));
end

function value=utcNow()
value=char(datetime('now','TimeZone','UTC','Format','yyyy-MM-dd''T''HH:mm:ss''Z'''));
end

function writeReadable(path,D)
fid=fopen(path,'w');assert(fid>=0,'OxygenDynamics:G4WriteFailed','Cannot write readable G4 evidence.');
cleanup=onCleanup(@()fclose(fid));
E=D.AutomaticEvent;R=D.RecordingSummary;J=D.ReviewedEvent;
M06=D.Definitions(1);M01=D.Definitions(2);
fprintf(fid,'# BOI saved review and measurement evidence\n\n');
fprintf(fid,'Saved dictionary version: %s. Definitions remain draft; numerical replay is not physiological validation.\n\n',D.DictionaryVersion);
fprintf(fid,'Automatic event (BOI-M06): %s site %d/event %d; frames %d–%d; amplitude %.17g fraction (%.17g%%).\n\n', ...
    E.EventType,E.SiteID,E.EventID,E.MeasurementStartFrame,E.MeasurementEndFrame,E.SavedAmplitudeFraction,100*E.SavedAmplitudeFraction);
fprintf(fid,'Preserved-input fixed-footprint mean; %d pixels. Baseline: %d clean frames, B0 %.17g input units. Extreme: frame %d, %.17g input units. Replay -(extreme-B0)/B0 = %.17g fraction.\n', ...
    E.FootprintPixels,numel(E.BaselineFrames),E.BaselineInputUnits,E.ExtremeFrame,E.ExtremeInputUnits,E.ReplayAmplitudeFraction);
fprintf(fid,'Effective settings: %.17g Hz (%s), %.17g µm/pixel, support %s. Units: %s. Limit: %s\n\n', ...
    E.SampleHz,E.FrameTimingStatus,E.PixelSizeUm,E.SupportProfile,M06.Units,M06.ClaimLimits);
fprintf(fid,'Recording summary (BOI-M01): whole-recording sink mean occupied tissue fraction %.17g (%.17g%%). Covered area-time %.17g µm²·s / analyzed tissue-time %.17g µm²·s; %d modeled frames. Status: %s.\n\n', ...
    R.SavedFraction,100*R.SavedFraction,R.SavedCoveredAreaTimeUm2Sec,R.SavedAnalyzedTissueTimeUm2Sec,numel(R.Frame),R.OccupancyStatus);
fprintf(fid,'Effective settings: %.17g Hz (%s), %.17g µm/pixel, support %s; static analyzed area %.17g µm². Units: %s. Limit: %s\n\n', ...
    R.SampleHz,R.FrameTimingStatus,R.PixelSizeUm,R.SupportProfile,R.StaticAnalyzedAreaUm2,M01.Units,M01.ClaimLimits);
fprintf(fid,'Separate C02 reviewed event: %s site %d/event %d, audit row %d. Automatic amplitude unavailable: %s (%d/%d clean baseline frames). Reviewed amplitude not calculated.\n\n', ...
    J.EventType,J.SiteID,J.EventID,J.AuditRow,J.AutomaticBaselineStatus,J.AutomaticCleanBaselineFrames,J.AutomaticRequiredBaselineFrames);
fprintf(fid,'Researcher boundary status: %s; preferred onset %d; onset alternatives %s; recovery alternatives %s; no preferred recovery when the saved field is empty. Reference decision %s selects %d frames for this onset only.\n\n', ...
    J.BoundaryStatus,J.BoundaryAnnotation.PreferredOnsetFrame,mat2str(J.BoundaryAnnotation.OnsetFrames), ...
    mat2str(J.BoundaryAnnotation.RecoveryFrames),J.ReferenceDecisionID,numel(J.ReferenceFrames));
fprintf(fid,'Review reason: %s\n\n',J.BoundaryAnnotation.Reason);
fprintf(fid,'Tissue decision: %s; %s Uncertain edges remain uncertain.\n\n',J.TissueDecision.Status,J.TissueDecision.Reason);
fprintf(fid,'The ID400 measurement examples and C02 review have different source identities; they are separate examples, not a combined recording result.\n\n');
fprintf(fid,'The source paths are intentionally outside this shareable folder. Evidence.json holds portable source hashes, saved per-frame ingredients, both definitions, decision history and availability reasons. The separate .local-sources.json file in the parent is private and must not be shared.\n\n');
fprintf(fid,'Scientific status: not established. Automatic results, researcher choices and proposed reference policy remain distinct. No detector, statistics or reviewed-amplitude calculation was run to create this bundle.\n');
end
