function Run=loadBOIRecordingRun(Path)
%LOADBOIRECORDINGRUN Reopen a complete indexed result without computation.
setupOxygenDynamicsPath;
if isfolder(Path),Path=fullfile(Path,'BOIRun.mat');end
Path=char(java.io.File(char(Path)).getCanonicalPath());root=fileparts(Path);
statusPath=fullfile(root,'RunStatus.json');
assert(isfile(statusPath),'OxygenDynamics:IncompleteRun','Missing run status; select a completed BOIRun.mat.');
status=jsondecode(fileread(statusPath));
assert(isfield(status,'Status')&&strcmp(status.Status,'complete'), ...
    'OxygenDynamics:IncompleteRun','Run is incomplete or failed; its partial outputs are not a completed result.');
S=load(Path,'Run');
assert(isfield(S,'Run')&&isstruct(S.Run)&&isscalar(S.Run)&& ...
    all(isfield(S.Run,{'Schema','Status','Artifacts','SourceSHA256','SupportProfile'}))&& ...
    strcmp(S.Run.Schema,'boi-recording-run-1')&&strcmp(S.Run.Status,'complete'), ...
    'OxygenDynamics:InvalidRun','Unsupported run index.');
Run=S.Run;A=Run.Artifacts;
roles={'Request','EventAudit','SinkMaster','SurgeMaster','DataOutput','Workbook','AnalysisManifest','AuditReceipt','CodeManifest'};
assert(isstruct(A)&&all(isfield(A,{'Role','Path','SHA256'}))&& ...
    isequal(sort({A.Role}),sort(roles)),'OxygenDynamics:InvalidRun','Missing or duplicate run artifacts.');
Run.Paths=struct();
for k=1:numel(A)
    p=char(java.io.File(fullfile(root,A(k).Path)).getCanonicalPath());
    assert(startsWith(p,[root filesep])&&isfile(p), ...
        'OxygenDynamics:RunArtifactMissing','Missing or invalid %s artifact: %s.',A(k).Role,A(k).Path);
    assert(strcmp(oxygenFileSHA256(p),A(k).SHA256), ...
        'OxygenDynamics:RunArtifactChanged','Saved %s artifact has changed. Keep the original and create a separate revision.',A(k).Role);
    Run.Paths.(A(k).Role)=p;
end
Q=load(Run.Paths.Request,'Request');
requiredOptions={'RecordingFolder','OutputFolder','SampleHz','PixelSizeUm','SupportProfile', ...
    'Mouse','Condition','DrugID','Genotype','Promoter'};
assert(isfield(Q,'Request')&&isstruct(Q.Request)&&isscalar(Q.Request)&& ...
    all(isfield(Q.Request,{'Schema','Options','InputReview'}))&& ...
    strcmp(Q.Request.Schema,'boi-recording-request-1')&& ...
    all(isfield(Q.Request.Options,requiredOptions)), ...
    'OxygenDynamics:InvalidRun','Saved request is incomplete or unsupported.');
Run.Request=Q.Request;
R=loadBOIEventReview(Run.Paths.EventAudit);
assert(strcmp(R.AnalysisInfo.RawSHA256,Run.SourceSHA256)&& ...
    strcmp(getBOISupportProfile(R.AnalysisInfo),Run.SupportProfile)&& ...
    strcmp(Run.Request.InputReview.RawSHA256,Run.SourceSHA256)&& ...
    strcmp(Run.Request.Options.SupportProfile,Run.SupportProfile), ...
    'OxygenDynamics:InvalidRun','Run, request and review source/support differ.');
Run.ManifestPath=Path;Run.Directory=root;
Run.EventCount=height(R.Audit);
Run.CorrectedTraceStatus='captured';
for k=1:numel(R.Traces)
    t=R.Traces{k};
    if ~isfield(t,'DetectionDetrended')||numel(t.DetectionDetrended)~=R.AnalysisInfo.NFrames|| ...
        ~isfield(t,'Filtered')||numel(t.Filtered)~=R.AnalysisInfo.NFrames
        Run.CorrectedTraceStatus='not_saved';break
    end
end
if Run.EventCount==0,Run.CorrectedTraceStatus='no_detected_events';end
end
