function Bundle=loadBOIG4EvidenceBundle(Folder)
%LOADBOIG4EVIDENCEBUNDLE Reopen a portable G4 snapshot without source recompute.
setupOxygenDynamicsPath;
Folder=char(java.io.File(char(Folder)).getCanonicalPath());
indexPath=fullfile(Folder,'BundleIndex.json');
assert(isfile(indexPath),'OxygenDynamics:G4IncompleteBundle','No completed G4 evidence index was found.');
I=jsondecode(fileread(indexPath));
assert(isstruct(I)&&all(isfield(I,{'Schema','Status','EvidenceFile','EvidenceSHA256','ReadableFile','ReadableSHA256'}))&& ...
    strcmp(I.Schema,'boi-g4-evidence-index-1')&&strcmp(I.Status,'complete')&& ...
    strcmp(I.EvidenceFile,'Evidence.json')&&strcmp(I.ReadableFile,'Evidence.md'), ...
    'OxygenDynamics:G4IncompleteBundle','The G4 evidence index is incomplete or unsupported.');
assert(isfile(fullfile(Folder,I.EvidenceFile))&&isfile(fullfile(Folder,I.ReadableFile)), ...
    'OxygenDynamics:G4IncompleteBundle','A completed G4 evidence file is missing.');
assert(strcmp(oxygenFileSHA256(fullfile(Folder,I.EvidenceFile)),I.EvidenceSHA256)&& ...
    strcmp(oxygenFileSHA256(fullfile(Folder,I.ReadableFile)),I.ReadableSHA256), ...
    'OxygenDynamics:G4ChangedBundle','The saved G4 evidence has changed; reopen the original revision.');
Bundle=jsondecode(fileread(fullfile(Folder,I.EvidenceFile)));
assert(isstruct(Bundle)&&all(isfield(Bundle,{'Schema','Sources','AutomaticEvent','RecordingSummary','ReviewedEvent','Definitions'}))&& ...
    strcmp(Bundle.Schema,'boi-g4-evidence-1')&& ...
    strcmp(Bundle.PackageRole,'bounded_separate_examples_not_a_single_recording_result')&& ...
    strcmp(Bundle.ReviewedEvent.ReviewedAmplitudeStatus,'not_calculated'), ...
    'OxygenDynamics:G4IncompleteBundle','The saved G4 evidence is incomplete or unsupported.');
Bundle.BundleFolder=Folder;
end
