function [Fig,UI]=openBOIG4EvidenceBundle(Folder)
%OPENBOIG4EVIDENCEBUNDLE View a saved portable evidence snapshot, read-only.
setupOxygenDynamicsPath;
if nargin<1||isempty(Folder)
    Folder=uigetdir(pwd,'Choose a completed BOI evidence bundle folder');
    if isequal(Folder,0),Fig=[];UI=[];return;end
end
D=loadBOIG4EvidenceBundle(Folder);
E=D.AutomaticEvent;R=D.RecordingSummary;J=D.ReviewedEvent;
Fig=uifigure('Name','BOI saved review evidence','Position',[110 90 1000 720]);
tabs=uitabgroup(Fig,'Position',[10 10 980 700]);
makeTab(tabs,'Overview',{ ...
    'Saved evidence; no source recomputation or scientific acceptance.', ...
    'ID400 automatic measurements and the C02 researcher review are separate examples.', ...
    sprintf('Automatic %s site %d/event %d amplitude: %.17g fraction.',E.EventType,E.SiteID,E.EventID,E.SavedAmplitudeFraction), ...
    sprintf('Whole-recording sink occupied tissue fraction: %.17g.',R.SavedFraction), ...
    sprintf('C02 %s site %d/event %d: automatic amplitude unavailable (%s); reviewed amplitude not calculated.', ...
        J.EventType,J.SiteID,J.EventID,J.AutomaticBaselineStatus), ...
    'All source identities are portable hashes in the saved evidence. Private local paths remain outside this folder.'});
makeTab(tabs,'Automatic event',{ ...
    sprintf('BOI-M06 | %s site %d/event %d | frames %d–%d',E.EventType,E.SiteID,E.EventID,E.MeasurementStartFrame,E.MeasurementEndFrame), ...
    sprintf('Preserved-input fixed footprint: %d pixels; baseline samples: %d.',E.FootprintPixels,numel(E.BaselineFrames)), ...
    sprintf('Baseline %.17g input units; extreme at frame %d = %.17g.',E.BaselineInputUnits,E.ExtremeFrame,E.ExtremeInputUnits), ...
    sprintf('Saved amplitude %.17g fraction; independent saved-ingredient replay %.17g.',E.SavedAmplitudeFraction,E.ReplayAmplitudeFraction), ...
    'This is relative optical change, not oxygen concentration.'});
makeTab(tabs,'Recording summary',{ ...
    'BOI-M01 | whole-recording sink mean occupied tissue fraction', ...
    sprintf('Modeled window [%.17g, %.17g) s; %d saved frame rows.',R.StartSec,R.EndSec,numel(R.Frame)), ...
    sprintf('Covered area-time %.17g µm²·s / analyzed tissue-time %.17g µm²·s.',R.SavedCoveredAreaTimeUm2Sec,R.SavedAnalyzedTissueTimeUm2Sec), ...
    sprintf('Saved fraction %.17g; independent saved-ingredient replay %.17g.',R.SavedFraction,R.ReplayFraction), ...
    ['Status: ' R.OccupancyStatus '. Static tissue and uniform frame intervals; dynamic validity unresolved.']});
makeTab(tabs,'Researcher review',{ ...
    sprintf('C02 %s site %d/event %d | audit row %d',J.EventType,J.SiteID,J.EventID,J.AuditRow), ...
    sprintf('Automatic amplitude unavailable: %d/%d clean prebaseline frames; %s.', ...
        J.AutomaticCleanBaselineFrames,J.AutomaticRequiredBaselineFrames,J.AutomaticBaselineStatus), ...
    'Reviewed amplitude: not calculated.', ...
    sprintf('Onset alternatives %s; preferred %s. Recovery alternatives %s; preferred %s.', ...
        mat2str(J.BoundaryAnnotation.OnsetFrames),mat2str(J.BoundaryAnnotation.PreferredOnsetFrame), ...
        mat2str(J.BoundaryAnnotation.RecoveryFrames),mat2str(J.BoundaryAnnotation.PreferredRecoveryFrame)), ...
    sprintf('Reference decision %s selected %d frames for the preferred onset only.',J.ReferenceDecisionID,numel(J.ReferenceFrames)), ...
    ['Tissue decision: ' J.TissueDecision.Status '. ' J.TissueDecision.Reason], ...
    ['Researcher reason: ' J.BoundaryAnnotation.Reason]});
makeTab(tabs,'Source identities',{ ...
    ['Automatic run SHA256: ' D.Sources.AutomaticRunSHA256], ...
    ['Automatic audit SHA256: ' D.Sources.AutomaticAuditSHA256], ...
    ['Automatic raw SHA256: ' D.Sources.AutomaticRawSHA256], ...
    ['Reviewed audit SHA256: ' D.Sources.ReviewedAuditSHA256], ...
    ['Reviewed raw SHA256: ' D.Sources.ReviewedRawSHA256], ...
    ['Boundary SHA256: ' D.Sources.BoundarySHA256], ...
    ['Reference SHA256: ' D.Sources.ReferenceSHA256], ...
    ['Dictionary SHA256: ' D.Sources.DictionarySHA256]});
UI=struct('Bundle',D,'Tabs',tabs);
end

function makeTab(group,name,lines)
tab=uitab(group,'Title',name);
grid=uigridlayout(tab,[1 1]);grid.Padding=[10 10 10 10];
uitextarea(grid,'Editable','off','Value',lines);
end
