function TestResult = testHypoxiaAmyloidAnalysis()
%TESTHYPOXIAAMYLOIDANALYSIS Focused synthetic tests for plaque-distance analysis.

setupOxygenDynamicsPath();
testPairAnalysis();
testEventProperties();
testNoPlaqueBehavior();
testOptionalCsvColumn();
testRecordingAdapter();
testAmyloidOnlyModeResolution();

TestResult = struct('Passed',true,'Timestamp', ...
    char(datetime('now','Format','yyyy-MM-dd HH:mm:ss')));
fprintf('Hypoxia-amyloid synthetic tests passed.\n');
end

function testPairAnalysis()

Hypoxia = false(20,20,8);
Hypoxia(4:6,4:6,2:4) = true;
Amyloid = ones(20,20);
Amyloid(3:5,3:5) = 10;
Options = struct('PixelSizeMicrometers',1,'AmyloidThreshold',0.5, ...
    'HypoxiaThreshold',0.05,'MinimumPlaqueAreaPixels',2, ...
    'RegionSigmaMicrometers',1,'CoarseSigmaMicrometers',4, ...
    'NumPermutations',20,'RandomSeed',7);

First = analyzeHypoxiaAmyloidPair(Hypoxia,Amyloid,Options);
Second = analyzeHypoxiaAmyloidPair(Hypoxia,Amyloid,Options);
assert(any(First.amyloid_mask(:)) && any(First.hypoxia_mask(:)), ...
    'Synthetic pair analysis did not detect expected masks.');
assert(isequaln(First.null_overlap_fraction,Second.null_overlap_fraction), ...
    'Spatial permutations were not deterministic for a fixed seed.');
assert(isequaln(First.null_correlation,Second.null_correlation), ...
    'Correlation permutations were not deterministic for a fixed seed.');
assert(isequaln(First.null_shifts_pixels,Second.null_shifts_pixels) && ...
    size(First.null_shifts_pixels,1)==Options.NumPermutations, ...
    'Circular-shift coordinates were not retained reproducibly.');

mustError(@() analyzeHypoxiaAmyloidPair(Hypoxia,ones(19,20),Options), ...
    'HypoxiaAmyloid:DimensionMismatch');
end

function testEventProperties()

[SinkStack,OxySinkAreaAll,SinkTable] = syntheticSinkData();
[Footprints,TrackedPixels] = reconstructHypoxicEventFootprints( ...
    SinkStack,OxySinkAreaAll,SinkTable);
assert(numel(Footprints)==3 && nnz(~cellfun(@isempty,TrackedPixels))==6, ...
    'Event-footprint reconstruction returned unexpected event/frame counts.');

PlaqueMask = false(20,20);
PlaqueMask(3:4,3:4) = true;
Options = struct('NearThresholdMicrometers',5, ...
    'SensitivityThresholdsMicrometers',[2 5 10], ...
    'MinimumObservationsPerStratum',1, ...
    'DistanceVariable','EdgeDistance_um', ...
    'SpatialNullShiftsPixels',[0 0; 3 4]);
Analysis = analyzeHypoxiaAmyloidEventProperties(Footprints,SinkTable, ...
    PlaqueMask,1,2,Options);

assert(height(Analysis.EventTable)==3 && height(Analysis.PocketTable)==2, ...
    'Amplitude-free event/pocket tables have unexpected sizes.');
assert(Analysis.EventTable.EdgeDistance_um(1)==1, ...
    'Nearest edge-to-edge distance was not calculated as expected.');
assert(Analysis.EventTable.DurationSec(1)==1 && ...
    Analysis.EventTable.Area_um2(1)==4, ...
    'Duration or event area calibration was incorrect.');
assert(Analysis.PocketTable.RecurrenceCount(1)==2 && ...
    Analysis.PocketTable.RecurrenceCount(2)==1, ...
    'Recurrence was not summarized once per tracked pocket.');
assert(height(Analysis.Summary.Correlations)==3 && ...
    height(Analysis.Summary.Thresholds)==9, ...
    'Continuous or threshold-sensitivity summaries are incomplete.');
assert(height(Analysis.SpatialNull)==18 && ...
    all(ismember(["Duration","SpatialSize","Recurrence"], ...
    unique(Analysis.SpatialNull.Property))), ...
    'Property-specific circular-shift null rows are incomplete.');
end

function testNoPlaqueBehavior()

[SinkStack,OxySinkAreaAll,SinkTable] = syntheticSinkData();
[Footprints,~] = reconstructHypoxicEventFootprints( ...
    SinkStack,OxySinkAreaAll,SinkTable);
Analysis = analyzeHypoxiaAmyloidEventProperties(Footprints,SinkTable, ...
    false(20,20),1,2,struct('MinimumObservationsPerStratum',1));
assert(all(isnan(Analysis.EventTable.EdgeDistance_um)) && ...
    all(isnan(Analysis.PocketTable.EdgeDistance_um)), ...
    'No-plaque distances must remain NaN.');
assert(all(isnan(Analysis.Summary.Correlations.SpearmanRho)), ...
    'No-plaque correlations must remain NaN.');
end

function testOptionalCsvColumn()

Required = table({'R1'},{''},{''},{''},{'M1'},{'APP'},{'C'},{'D'}, ...
    {'P'},1,2.5,'VariableNames',requiredWrapperInputColumns());
[~,~,~,~,~,~,~,~,~,~,~,AmyloidFiles] = unpackWrapperInputTable(Required);
assert(isempty(AmyloidFiles{1}), ...
    'Missing optional AmyloidFile column should resolve to blank values.');

Required.AmyloidFile = {'methoxy.tif'};
[~,~,~,~,~,~,~,~,~,~,~,AmyloidFiles] = unpackWrapperInputTable(Required);
assert(strcmp(AmyloidFiles{1},'methoxy.tif'), ...
    'Optional AmyloidFile column was not unpacked correctly.');
end

function testAmyloidOnlyModeResolution()

Config = struct('interactive',false,'reanalyseExisting',false, ...
    'overwritePreviousAnalysis',false,'analysisMode','Hypoxia-amyloid only');
[Mode,Reanalyse,Overwrite] = resolveWrapperRunChoices(Config);
assert(strcmp(Mode,'Hypoxia-amyloid only') && strcmp(Reanalyse,'N') && ...
    strcmp(Overwrite,'N'), ...
    'Hypoxia-amyloid only wrapper mode did not resolve correctly.');
end

function testRecordingAdapter()

Root = fullfile(tempdir,['HypoxiaAmyloidTest_', ...
    char(datetime('now','Format','yyyyMMddHHmmssSSS'))]);
RecordingFolder = fullfile(Root,'Mouse1','Recording1');
SinksFolder = fullfile(RecordingFolder,'OxygenSinks_Output');
mkdir(SinksFolder);
Cleanup = onCleanup(@() removeTestFolder(Root));

[SinkStack,OxySinkArea_all,Table_OxygenSinks_Out] = syntheticSinkData();
saveastiff(uint16(SinkStack),fullfile(SinksFolder,'IM_OxySinks_BWSmoke.tif'), ...
    struct('overwrite',true));
save(fullfile(SinksFolder,'OxygenSinks_UrefinedSmoke.mat'), ...
    'Table_OxygenSinks_Out','OxySinkArea_all');

Amyloid = uint16(ones(20,20)*100);
Amyloid(3:4,3:4) = 1000;
AmyloidFile = fullfile(RecordingFolder,'methoxy_x04.tif');
imwrite(Amyloid,AmyloidFile);
AmyloidFolder = fullfile(RecordingFolder,'methoxy');
mkdir(AmyloidFolder);
FolderAmyloidFile = fullfile(AmyloidFolder,'methoxy_x04.tif');
imwrite(Amyloid,FolderAmyloidFile);
assert(strcmp(resolveOptionalRecordingFile('methoxy',RecordingFolder), ...
    FolderAmyloidFile), ...
    'Amyloid folder input did not resolve its single TIFF.');

Metadata = createRecordingMetadata('Mouse1','APP','None', ...
    'FourMonthAPP','MethoxyX04');
Options = struct('OverwriteOutputs',true,'SaveFigures',true, ...
    'PairOptions',struct('AmyloidThreshold',0.5,'NumPermutations',5, ...
    'RegionSigmaMicrometers',1,'CoarseSigmaMicrometers',4), ...
    'PropertyOptions',struct('NearThresholdMicrometers',5, ...
    'SensitivityThresholdsMicrometers',[2 5 10], ...
    'MinimumObservationsPerStratum',1, ...
    'DistanceVariable','CentroidDistance_um'));
Result = runHypoxiaAmyloidRecordingAnalysis(RecordingFolder,'methoxy', ...
    Metadata,2,1,Options);

assert(isfile(fullfile(Result.OutputFolder,'HypoxiaAmyloid_EventMetrics.csv')) && ...
    isfile(fullfile(Result.OutputFolder,'HypoxiaAmyloid_Result.mat')) && ...
    isfile(fullfile(Result.OutputFolder,'HypoxiaAmyloid_QC.png')) && ...
    isfile(fullfile(Result.OutputFolder, ...
    'HypoxiaAmyloid_PropertySpatialNull.csv')) && ...
    height(Result.Properties.EventTable)==3 && Result.Age=="4 months", ...
    'Recording adapter did not create the expected event outputs.');

CohortOptions = struct('PropertyOptions',Options.PropertyOptions, ...
    'NumPermutations',50,'BootstrapIterations',50,'RandomSeed',3);
Cohort = runHypoxiaAmyloidCohortSummary({Result},Root,CohortOptions);
assert(isfile(fullfile(Cohort.OutputFolder,'AnimalCorrelations.csv')) && ...
    isfile(fullfile(Cohort.OutputFolder,'PerPocketTable.csv')) && ...
    isfile(fullfile(Cohort.OutputFolder,'AnimalInclusion.csv')) && ...
    isfile(fullfile(Cohort.OutputFolder,'GroupResults.csv')) && ...
    isfile(fullfile(Cohort.OutputFolder,'GroupDefinitions.csv')) && ...
    isfile(fullfile(Cohort.OutputFolder,'AnalysisAvailability.csv')) && ...
    isfile(fullfile(Cohort.OutputFolder,'TreatmentComparisonResults.csv')) && ...
    isfile(fullfile(Cohort.OutputFolder,'FactorialInteractionResults.csv')) && ...
    isfile(fullfile(Cohort.OutputFolder,'AgeComparisonResults.csv')) && ...
    isfile(fullfile(Cohort.OutputFolder, ...
    'HypoxiaAmyloid_Figure2Candidate.png')) && ...
    any(Cohort.GroupResults.Scope=="None | APP") && ...
    all(ismember({'Condition','DrugID','AnalysisGroup'}, ...
    Cohort.AnimalThresholds.Properties.VariableNames)), ...
    'Cohort aggregation did not create the expected animal-level outputs.');
end

function [SinkStack,OxySinkAreaAll,SinkTable] = syntheticSinkData()

SinkStack = false(20,20,10);
NearPixels = blockPixels([5 4],20);
FarPixels = blockPixels([15 15],20);
SinkStack(NearPixels+20*20*(2-1)) = true;
SinkStack(NearPixels+20*20*(3-1)) = true;
SinkStack(FarPixels+20*20*(5-1)) = true;
SinkStack(FarPixels+20*20*(6-1)) = true;
SinkStack(NearPixels+20*20*(8-1)) = true;
SinkStack(NearPixels+20*20*(9-1)) = true;

OxySinkAreaAll = cell(2,10);
OxySinkAreaAll(1,[2 3 8 9]) = {4};
OxySinkAreaAll(2,[5 6]) = {4};
SinkTable = table([2;1],{[2 2];2},{NearPixels;FarPixels}, ...
    'VariableNames',{'NumOxySinkEvents','Duration','OxySink_Pxls_all'});
end

function Pixels = blockPixels(TopLeft,ImageHeight)

Rows = TopLeft(1)+(0:1);
Cols = TopLeft(2)+(0:1);
[ColGrid,RowGrid] = meshgrid(Cols,Rows);
Pixels = sub2ind([ImageHeight ImageHeight],RowGrid(:),ColGrid(:));
end

function mustError(FunctionHandle,ExpectedIdentifier)

DidError = false;
try
    FunctionHandle();
catch ME
    DidError = strcmp(ME.identifier,ExpectedIdentifier);
end
assert(DidError,'Expected error %s was not raised.',ExpectedIdentifier);
end

function removeTestFolder(Folder)

if isfolder(Folder)
    rmdir(Folder,'s');
end
end
