function Result=runG4SavedEvidenceCheck(EvidenceRoot)
%RUNG4SAVEDEVIDENCECHECK Finite saved-result checks; no detector or statistics run.
setupOxygenDynamicsPath;
root=fileparts(fileparts(fileparts(mfilename('fullpath'))));
project=fileparts(root);
if nargin<1,EvidenceRoot=fullfile(project,'reference-validation','software-g4-evidence-20260927');end
folder=fullfile(EvidenceRoot,'relocated-final');
D=loadBOIG4EvidenceBundle(folder);
assert(~isfile(fullfile(folder,'saved-bundle-final.local-sources.json')), ...
    'OxygenDynamics:G4Check','Portable copy unexpectedly includes a private source map.');
assert(~contains(fileread(fullfile(folder,'Evidence.json')),'/Users/')&& ...
    ~contains(fileread(fullfile(folder,'Evidence.md')),'/Users/'), ...
    'OxygenDynamics:G4Check','Shareable evidence contains a private absolute path.');
E=D.AutomaticEvent;R=D.RecordingSummary;J=D.ReviewedEvent;
assert(strcmp(E.EventType,'sink')&&E.SiteID==1&&E.EventID==3&& ...
    isequal(E.BaselineFrames(:),(411:430)')&&E.ExtremeFrame==435&& ...
    E.MeasurementStartFrame==431&&E.MeasurementEndFrame==457, ...
    'OxygenDynamics:G4Check','Automatic event identity or saved ingredients differ.');
baseline=mean(E.BaselineValues);eventValue=min(E.MeasurementValues);
amplitude=-(eventValue-baseline)/baseline;
assert(abs(amplitude-E.SavedAmplitudeFraction)<1e-12&& ...
    abs(amplitude-0.055522971205831419)<1e-12, ...
    'OxygenDynamics:G4Check','Automatic event replay differs.');
assert(strcmp(R.MeasurementID,'BOI-M01')&&strcmp(R.WindowID,'whole_recording')&& ...
    strcmp(R.Sign,'sink')&&numel(R.Frame)==600, ...
    'OxygenDynamics:G4Check','Recording summary identity differs.');
fraction=sum(R.CoveredAreaTimeUm2Sec)/sum(R.AnalyzedTissueTimeUm2Sec);
assert(abs(fraction-R.SavedFraction)<1e-12&& ...
    abs(fraction-0.0060960622231134576)<1e-12, ...
    'OxygenDynamics:G4Check','Recording summary replay differs.');
assert(J.AuditRow==186&&J.SiteID==15&&J.EventID==36&& ...
    strcmp(J.AutomaticBaselineStatus,'insufficient_clean_prebaseline')&& ...
    J.AutomaticCleanBaselineFrames==14&&J.AutomaticRequiredBaselineFrames==20&& ...
    isempty(J.AutomaticAmplitudeFraction)&&isempty(J.ReviewedAmplitudeFraction)&& ...
    strcmp(J.ReviewedAmplitudeStatus,'not_calculated'), ...
    'OxygenDynamics:G4Check','C02 amplitude availability changed.');
assert(isequal(J.BoundaryAnnotation.OnsetFrames(:),[1149;1154])&& ...
    isequal(J.BoundaryAnnotation.RecoveryFrames(:),[1166;1167])&& ...
    J.BoundaryAnnotation.PreferredOnsetFrame==1154&& ...
    isempty(J.BoundaryAnnotation.PreferredRecoveryFrame)&& ...
    numel(J.BoundaryHistory)==2&& ...
    J.BoundaryHistory(1).Annotation.PreferredOnsetFrame==1153&& ...
    J.BoundaryHistory(2).Annotation.PreferredOnsetFrame==1154&& ...
    isequal(J.ReferenceFrames(:),(1134:1153)'), ...
    'OxygenDynamics:G4Check','C02 judgment history or reference selection differs.');
assert(contains(J.TissueDecision.Reason,'uncertain boundary segments remain'), ...
    'OxygenDynamics:G4Check','Tissue-support uncertainty was lost.');
failed=false;
try
    loadBOIG4EvidenceBundle(fullfile(EvidenceRoot,'tampered-final'));
catch err
    failed=strcmp(err.identifier,'OxygenDynamics:G4ChangedBundle');
end
assert(failed,'OxygenDynamics:G4Check','Changed portable evidence was not rejected.');
blocked=false;
try
    createBOIG4EvidenceBundle(fullfile(EvidenceRoot,'saved-bundle-final'),'missing',0,'missing',0,'missing','missing');
catch err
    blocked=strcmp(err.identifier,'OxygenDynamics:G4OutputExists');
end
assert(blocked,'OxygenDynamics:G4Check','An existing export folder was not protected from overwrite.');
runPath=fullfile(project,'reference-validation','software-g2-workflow-20260923','gui-run','BOIRun.mat');
auditPath=fullfile(project,'reference-validation','software-g2-workflow-20260923','gui-run','Recording','BOIReview','event-amplitude-audit.mat');
dataPath=fullfile(project,'reference-validation','software-g2-workflow-20260923','gui-run','statistics','Stats_Output_20260923T102730','DataOutput.mat');
reviewPath=fullfile(project,'reference-validation','boi-c02-strict-roi-20260912','audit-01','source-amplitude-audit','event-amplitude-audit.mat');
boundaryPath=fullfile(project,'reference-validation','boi-c02-strict-roi-20260912','audit-01','source-amplitude-audit','BOI-researcher-review-05.json');
priorBoundaryPath=fullfile(project,'reference-validation','boi-c02-strict-roi-20260912','audit-01','source-amplitude-audit','BOI-researcher-review-04.json');
wrongReference=fullfile(project,'reference-validation','boi-researcher-event4-reference-20260915','researcher-reference-judgment.json');
wrongOutput=fullfile(EvidenceRoot,'mismatched-review-must-not-be-created');
assert(~isfolder(wrongOutput),'OxygenDynamics:G4Check','The mismatch check output name is already occupied.');
rejected=false;
try
    createBOIG4EvidenceBundle(wrongOutput,runPath,3,reviewPath,186,boundaryPath,wrongReference);
catch err
    rejected=strcmp(err.identifier,'OxygenDynamics:G4ReviewMismatch')|| ...
        strcmp(err.identifier,'OxygenDynamics:ReferenceJudgmentMismatch');
end
assert(rejected&&~isfolder(wrongOutput),'OxygenDynamics:G4Check', ...
    'A mismatched review was accepted or created an output folder.');
assert(strcmp(oxygenFileSHA256(runPath),'c64b0283671b1afa3581c8312f174522519282b4e5f27c6f41923aa15a51c260')&& ...
    strcmp(oxygenFileSHA256(auditPath),'09763da9204f942836b72dc0c0c9952f7b009f5c6a708152fbfe7072d04ddd35')&& ...
    strcmp(oxygenFileSHA256(dataPath),'ffc449431a5fcd8d5948efde9ac30aa3d4e5081415e8a1e6a6c460502eaa9e56')&& ...
    strcmp(oxygenFileSHA256(reviewPath),'c6ff9c10021068a659053da9be9e8a2092843c7caf19ad9ee8c14086df04776b')&& ...
    strcmp(oxygenFileSHA256(priorBoundaryPath),'16a99333cf9fed005fce1823fdea76161055776dde428e27c642afef0f1df26f')&& ...
    strcmp(oxygenFileSHA256(boundaryPath),'0283e8ce315a958e3ab1403a18738eb163b96fbf72edd523674dadd24adcd7bc'), ...
    'OxygenDynamics:G4Check','An original saved source changed.');
Result=struct('Schema','boi-g4-saved-evidence-check-1','Passed',true, ...
    'EventAmplitudeFraction',amplitude,'RecordingOccupancyFraction',fraction, ...
    'C02AutomaticAmplitude','unavailable','C02ReviewedAmplitude','not_calculated', ...
    'PortableCopyReopened',true,'ChangedCopyRejected',true,'OverwriteRejected',true, ...
    'MismatchedReviewRejectedBeforeOutput',true,'PriorAndCurrentReviewRevisionsPreserved',true, ...
    'OriginalSourcesUnchanged',true,'DetectorExecutions',0,'StatisticsExecutions',0);
end
